package skill

import (
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Mikedev115/Aetox/internal/lsp"
)

func TestImpactValidationAndSandbox(t *testing.T) {
	root := t.TempDir()
	s := &impactSkill{root: root}

	// Missing arguments
	for _, args := range []map[string]any{
		{},
		{"path": "main.go"},
		{"name": "main"},
		{"path": "", "name": ""},
	} {
		out, err := s.ExecuteTool(context.Background(), args)
		if err == nil {
			t.Errorf("args %v should fail validation, got: %q", args, out.Content)
		}
	}

	// Sandbox escape
	_, err := s.ExecuteTool(context.Background(), map[string]any{
		"path": "../../escaped.go",
		"name": "Foo",
	})
	if err == nil {
		t.Error("path escaping sandbox root must be rejected")
	}
}

func TestImpactTruthfulOutcomesWhenLSPUnavailable(t *testing.T) {
	root := t.TempDir()
	s := &impactSkill{root: root}

	// File type with no configured LSP (e.g. .txt)
	txtFile := filepath.Join(root, "notes.txt")
	if err := os.WriteFile(txtFile, []byte("hello world"), 0o644); err != nil {
		t.Fatal(err)
	}
	out, err := s.ExecuteTool(context.Background(), map[string]any{"path": "notes.txt", "name": "hello"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out.Content, "no language server exists for this file type, not checked") {
		t.Errorf("want not checked message, got: %q", out.Content)
	}
}

func TestImpactFormattingAndPartitioning(t *testing.T) {
	root := t.TempDir()

	// Write mock files so isFileHeaderGenerated can inspect if needed
	files := map[string]string{
		"internal/engine/app.go":                     "package engine\nfunc (a *Engine) SendMessage() {}\n",
		"internal/engine/stream_delivery_test.go":   "package engine\n",
		"internal/engine/failed_turn_test.go":       "package engine\n",
		"internal/engine/rpc/server_gen.go":         "// Code generated by gen. DO NOT EDIT.\npackage rpc\n",
		"internal/engine/rpc/client_gen.go":         "// Code generated by gen. DO NOT EDIT.\npackage rpc\n",
		"internal/engine/api_gen.go":                "// Code generated by gen. DO NOT EDIT.\npackage engine\n",
		"internal/engine/regenerate.go":             "package engine\n",
		"internal/engine/testdata/sample.json":      "{}\n",
	}
	for rel, body := range files {
		abs := filepath.Join(root, rel)
		_ = os.MkdirAll(filepath.Dir(abs), 0o755)
		_ = os.WriteFile(abs, []byte(body), 0o644)
	}

	info := &lsp.SymbolInfo{
		DefPath: filepath.Join(root, "internal/engine/app.go"),
		DefLine: 2478,
		Hover:   "func (a *Engine) SendMessage(text, to string) (TurnReply, error)",
		Refs: []lsp.Location{
			{Path: filepath.Join(root, "internal/engine/regenerate.go"), Line: 70},
			{Path: filepath.Join(root, "internal/engine/stream_delivery_test.go"), Line: 67},
			{Path: filepath.Join(root, "internal/engine/failed_turn_test.go"), Line: 138},
			{Path: filepath.Join(root, "internal/engine/rpc/server_gen.go"), Line: 1426},
			{Path: filepath.Join(root, "internal/engine/rpc/client_gen.go"), Line: 1811},
			{Path: filepath.Join(root, "internal/engine/api_gen.go"), Line: 292},
			{Path: filepath.Join(root, "internal/engine/testdata/sample.json"), Line: 2},
		},
	}

	formatted := formatImpact(root, "SendMessage", "internal/engine/app.go", info)

	// Verify Header & Declaration
	if !strings.Contains(formatted, "Impact: engine.Engine.SendMessage") {
		t.Errorf("want 'Impact: engine.Engine.SendMessage', got:\n%s", formatted)
	}
	if !strings.Contains(formatted, "Declared at internal/engine/app.go:2478") {
		t.Errorf("want 'Declared at internal/engine/app.go:2478', got:\n%s", formatted)
	}

	// Verify Production references
	if !strings.Contains(formatted, "Production references (1)\n- internal/engine/regenerate.go:70") {
		t.Errorf("want production reference internal/engine/regenerate.go:70, got:\n%s", formatted)
	}

	// Verify Test references
	if !strings.Contains(formatted, "Test references (2)\n- internal/engine/stream_delivery_test.go:67\n- internal/engine/failed_turn_test.go:138") {
		t.Errorf("want test references stream_delivery and failed_turn, got:\n%s", formatted)
	}

	// Verify Other references (generated + testdata)
	if !strings.Contains(formatted, "Other references (4)") {
		t.Errorf("want 4 other references, got:\n%s", formatted)
	}
	if !strings.Contains(formatted, "- internal/engine/rpc/server_gen.go:1426") ||
		!strings.Contains(formatted, "- internal/engine/rpc/client_gen.go:1811") ||
		!strings.Contains(formatted, "- internal/engine/api_gen.go:292") ||
		!strings.Contains(formatted, "- internal/engine/testdata/sample.json:2") {
		t.Errorf("missing expected other references, got:\n%s", formatted)
	}

	// Verify Generated/RPC surface evidence
	if !strings.Contains(formatted, "Generated/RPC surface evidence\n- internal/engine/rpc/server_gen.go:1426\n- internal/engine/rpc/client_gen.go:1811\n- internal/engine/api_gen.go:292") {
		t.Errorf("missing expected generated/RPC surface evidence, got:\n%s", formatted)
	}

	// Verify Related narrow checks
	if !strings.Contains(formatted, "Related narrow checks") {
		t.Errorf("missing Related narrow checks, got:\n%s", formatted)
	}
	if !strings.Contains(formatted, "- internal/engine/failed_turn_test.go") ||
		!strings.Contains(formatted, "- internal/engine/stream_delivery_test.go") {
		t.Errorf("related test files missing, got:\n%s", formatted)
	}
	if !strings.Contains(formatted, "- go test ./internal/engine/...") {
		t.Errorf("want package-level test command 'go test ./internal/engine/...', got:\n%s", formatted)
	}
}

func TestImpactNoReferencesAndNoChecks(t *testing.T) {
	root := t.TempDir()
	info := &lsp.SymbolInfo{
		DefPath: filepath.Join(root, "pkg/util.go"),
		DefLine: 12,
		Hover:   "func Helper()",
		Refs:    nil,
	}
	formatted := formatImpact(root, "Helper", "pkg/util.go", info)
	if !strings.Contains(formatted, "Production references (0)\n- (none)") {
		t.Errorf("want (none) for production references, got:\n%s", formatted)
	}
	if !strings.Contains(formatted, "Test references (0)\n- (none)") {
		t.Errorf("want (none) for test references, got:\n%s", formatted)
	}
	if !strings.Contains(formatted, "Other references (0)\n- (none)") {
		t.Errorf("want (none) for other references, got:\n%s", formatted)
	}
	if !strings.Contains(formatted, "Generated/RPC surface evidence\n- (none)") {
		t.Errorf("want (none) for generated/RPC evidence, got:\n%s", formatted)
	}
	if !strings.Contains(formatted, "Related narrow checks\n- No narrow automated check was identified.") {
		t.Errorf("want 'No narrow automated check was identified.', got:\n%s", formatted)
	}
}

func TestCodebasePackDispatchesImpactAndNarrows(t *testing.T) {
	root := t.TempDir()
	registry := NewDefaultRegistry(RegistryOptions{SandboxRoot: root})

	// Check codebase pack contains impact
	cbSkill, ok := registry.Get("codebase")
	if !ok {
		t.Fatal("codebase tool is not registered")
	}
	packed, ok := cbSkill.(Packed)
	if !ok {
		t.Fatal("codebase skill does not implement Packed")
	}

	actions := packed.Actions()
	var hasImpact bool
	for _, a := range actions {
		if a == "impact" {
			hasImpact = true
			break
		}
	}
	if !hasImpact {
		t.Errorf("codebase actions %v does not include 'impact'", actions)
	}

	// PackForAction resolution
	toolName, action, perm, found := PackForAction("impact")
	if !found || toolName != "codebase" || action != "impact" || perm != "impact" {
		t.Errorf("PackForAction(impact) = (%s, %s, %s, %v), want (codebase, impact, impact, true)",
			toolName, action, perm, found)
	}

	// Unpack resolution
	if got := Unpack("codebase", map[string]any{"action": "impact"}); got != "impact" {
		t.Errorf("Unpack(codebase, action=impact) = %q, want impact", got)
	}

	// Category check
	if cat := CategoryOf("impact"); cat != CategoryCode {
		t.Errorf("CategoryOf(impact) = %q, want CategoryCode", cat)
	}

	// Narrowing: caller only gets 'impact'
	narrowed := packed.Narrow([]string{"impact"})
	tool := narrowed.(Tool)
	def := tool.ToolDefinition()
	var schema map[string]any
	schemaStr, _ := json.Marshal(def.Function.Parameters)
	_ = json.Unmarshal(schemaStr, &schema)

	props, _ := schema["properties"].(map[string]any)
	if _, hasName := props["name"]; !hasName {
		t.Error("a narrowed codebase holding only 'impact' must still include 'name' in its schema")
	}

	// Call action=symbol on narrowed tool holding only impact -> must be refused
	_, err := tool.ExecuteTool(context.Background(), map[string]any{
		"action": "symbol",
		"path":   "main.go",
		"name":   "main",
	})
	if err == nil || !strings.Contains(err.Error(), "not available here") {
		t.Errorf("expected 'not available here' refusal for symbol on narrowed impact, got: %v", err)
	}
}

func TestImpactLiveRealGopls(t *testing.T) {
	if _, err := exec.LookPath("gopls"); err != nil {
		t.Skip("gopls not installed")
	}
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	registry := NewDefaultRegistry(RegistryOptions{SandboxRoot: root})
	cbSkill, ok := registry.Get("codebase")
	if !ok {
		t.Fatal("codebase tool is not registered")
	}
	tool, ok := cbSkill.(Tool)
	if !ok {
		t.Fatal("codebase does not implement Tool")
	}
	out, err := tool.ExecuteTool(context.Background(), map[string]any{
		"action": "impact",
		"path":   "internal/engine/app.go",
		"name":   "SendMessage",
	})
	if err != nil {
		t.Fatalf("ExecuteTool failed: %v", err)
	}
	t.Logf("Live codebase.impact output:\n%s", out.Content)
	if !strings.Contains(out.Content, "Impact: engine.Engine.SendMessage") {
		t.Errorf("want 'Impact: engine.Engine.SendMessage', got:\n%s", out.Content)
	}
	if !strings.Contains(out.Content, "Declared at internal/engine/app.go:") {
		t.Errorf("want Declared at internal/engine/app.go:, got:\n%s", out.Content)
	}
	if !strings.Contains(out.Content, "Production references") {
		t.Error("missing Production references")
	}
	if !strings.Contains(out.Content, "Test references") {
		t.Error("missing Test references")
	}
	if !strings.Contains(out.Content, "Other references") {
		t.Error("missing Other references")
	}
	if !strings.Contains(out.Content, "Generated/RPC surface evidence") {
		t.Error("missing Generated/RPC surface evidence")
	}
	if !strings.Contains(out.Content, "Related narrow checks") {
		t.Error("missing Related narrow checks")
	}
}

func TestImpactTruncatedReferencesWarning(t *testing.T) {
	root := t.TempDir()
	info := &lsp.SymbolInfo{
		DefPath:       filepath.Join(root, "pkg/core.go"),
		DefLine:       10,
		Hover:         "func Core()",
		RefsTruncated: true,
		Refs: []lsp.Location{
			{Path: filepath.Join(root, "pkg/prod.go"), Line: 20},
			{Path: filepath.Join(root, "pkg/core_test.go"), Line: 15},
			{Path: filepath.Join(root, "pkg/testdata/dummy.txt"), Line: 1},
		},
	}
	out := formatImpact(root, "Core", "pkg/core.go", info)

	if !strings.Contains(out, "Warning: references capped at 3 by language server; blast radius is incomplete and additional callers/tests exist beyond this list") {
		t.Errorf("missing truncated warning banner, got:\n%s", out)
	}
	if !strings.Contains(out, "Production references (1, partial)") {
		t.Errorf("want 'Production references (1, partial)', got:\n%s", out)
	}
	if !strings.Contains(out, "Test references (1, partial)") {
		t.Errorf("want 'Test references (1, partial)', got:\n%s", out)
	}
	if !strings.Contains(out, "Other references (1, partial)") {
		t.Errorf("want 'Other references (1, partial)', got:\n%s", out)
	}
	if !strings.Contains(out, "- Warning: additional test files may exist outside the capped references") {
		t.Errorf("want warning in narrow checks about additional test files, got:\n%s", out)
	}
}

func TestImpactRPCConventionVsConfirmedGenerated(t *testing.T) {
	root := t.TempDir()

	// Write files
	files := map[string]string{
		"internal/engine/rpc/server_gen.go": "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage rpc\n",
		"internal/engine/rpc/handler.go":    "package rpc\n",
		"internal/engine/rpc/rpc_test.go":   "package rpc\n",
	}
	for rel, body := range files {
		abs := filepath.Join(root, rel)
		_ = os.MkdirAll(filepath.Dir(abs), 0o755)
		_ = os.WriteFile(abs, []byte(body), 0o644)
	}

	info := &lsp.SymbolInfo{
		DefPath: filepath.Join(root, "internal/engine/rpc/handler.go"),
		DefLine: 12,
		Hover:   "func HandleCall()",
		Refs: []lsp.Location{
			{Path: filepath.Join(root, "internal/engine/rpc/server_gen.go"), Line: 100},
			{Path: filepath.Join(root, "internal/engine/rpc/handler.go"), Line: 50},
			{Path: filepath.Join(root, "internal/engine/rpc/rpc_test.go"), Line: 25},
		},
	}

	out := formatImpact(root, "HandleCall", "internal/engine/rpc/handler.go", info)

	// handler.go:50 must be a PRODUCTION reference, NOT banished to other!
	if !strings.Contains(out, "Production references (1)\n- internal/engine/rpc/handler.go:50") {
		t.Errorf("handler.go:50 must be classified as a Production reference, got:\n%s", out)
	}

	// server_gen.go:100 is confirmed generated, so it's in other
	if !strings.Contains(out, "Other references (1)\n- internal/engine/rpc/server_gen.go:100") {
		t.Errorf("server_gen.go:100 must be in Other references, got:\n%s", out)
	}

	// rpc_test.go:25 is in tests
	if !strings.Contains(out, "Test references (1)\n- internal/engine/rpc/rpc_test.go:25") {
		t.Errorf("rpc_test.go:25 must be in Test references, got:\n%s", out)
	}

	// Generated/RPC surface evidence:
	// - server_gen.go is confirmed generated (no path convention tag)
	// - handler.go:50 is labeled as path convention only!
	if !strings.Contains(out, "- internal/engine/rpc/server_gen.go:100\n") {
		t.Errorf("server_gen.go:100 should be listed as confirmed generated evidence, got:\n%s", out)
	}
	if !strings.Contains(out, "- internal/engine/rpc/handler.go:50 (path convention only, unconfirmed runtime boundary)") {
		t.Errorf("handler.go:50 must be tagged as path convention only, got:\n%s", out)
	}
}

