// Code generated by internal/engine/gen. DO NOT EDIT.

package engine

import (
	"context"
	"github.com/Mikedev115/Aetox/internal/capability"
	"github.com/Mikedev115/Aetox/internal/command"
	"github.com/Mikedev115/Aetox/internal/config"
	"github.com/Mikedev115/Aetox/internal/connect"
	gh "github.com/Mikedev115/Aetox/internal/github"
	"github.com/Mikedev115/Aetox/internal/mode"
	"github.com/Mikedev115/Aetox/internal/model"
	"github.com/Mikedev115/Aetox/internal/oauth"
	"github.com/Mikedev115/Aetox/internal/ooxml"
	"github.com/Mikedev115/Aetox/internal/skill"
	"github.com/Mikedev115/Aetox/internal/subagent"
)

// API is every exported method of *Engine: what the screen may ask of the
// engine, in one process today and across a socket in phase 2 (§248).
type API interface {
	AcceptsAPIKey(providerName string) bool
	AccountRefresh() (AccountState, error)
	AccountSignOut() error
	AccountStatus() AccountState
	ActiveModelFor(providerName string) (string, string)
	AddCustomProviderRow(name string, baseURL string) (string, error)
	AddLearnedEntry(scope string, text string) error
	AddMCPServer(name string, command []string) error
	AddSpaceContextFiles(name string, picked []string) ([]string, error)
	AddWorkspaceFolderAt(dir string) ([]WorkspaceFolder, error)
	AdoptMemoryScope(scope string, targetRoot string) error
	AgentBlocked(name string) bool
	AgentGate(name string) AgentGate
	AgentHomePath(name string) (string, error)
	AgentNeeds(name string) []subagent.Requirement
	AgentPackageBytes(name string) (ExportFile, error)
	AgentSkills(name string) []AgentSkillInfo
	AgentSkillsFolderPath(name string) (string, error)
	AgentsFolderPath() (string, error)
	AllowComputerApp(name string) error
	AnswerUserQuestion(sessionID string, answer string)
	AppCredit() string
	AppVersion() string
	ApplyMemoryLines(scope string, lines []string) error
	ApprovePendingChange(id int64) error
	ApprovePendingChangeTo(id int64, scope string) error
	ArtifactPath(path string) (string, error)
	ArtifactPreview(path string) (ArtifactPreview, error)
	BackgroundRuns() []BackgroundRun
	BackgroundTasks() []BackgroundTask
	BrowseFolderAt(dir string) (string, error)
	BrowseForComputerApp() (string, error)
	BrowseRoot() string
	BrowserBack(id string)
	BrowserCaptureFullPNG(ctx context.Context, id string) (string, int, error)
	BrowserCapturePNG(id string) (string, error)
	BrowserClickRef(id string, ref int) error
	BrowserClose(id string)
	BrowserCloseForTeardown(id string)
	BrowserDetach(id string)
	BrowserDevices() []DeviceProfile
	BrowserForward(id string)
	BrowserGetText(id string) (string, error)
	BrowserNavigate(id string, url string, fallback string)
	BrowserOpen(id string, url string, fallback string, x int, y int, w int, h int) error
	BrowserOpenDevTools(id string)
	BrowserReload(id string)
	BrowserSetBounds(id string, x int, y int, w int, h int)
	BrowserSetDevice(id string, name string) error
	BrowserSetScreenShape(id string, radius int, notchW int, notchH int, notchY int)
	BrowserSetVisible(id string, visible bool)
	BrowserSetZoom(id string, factor float64)
	BrowserStartPick(id string, opts string) error
	BrowserStopPick(id string)
	BrowserTypeRef(id string, ref int, text string, enter bool) error
	BusySignal() []BusyLayer
	CancelAccountSignIn()
	CancelMCPSignIn(serverName string)
	CancelPendingModel() ModelInfo
	CancelSignIn(providerName string)
	CancelTurn()
	CapabilitiesInstalling() bool
	CapabilityForServer(server string) string
	CapabilityStatuses() []capability.Status
	CatalogModelChoices(canonical string) []string
	ChairStarters(name string, locale string) subagent.StarterSet
	ChairStartersFile(locale string) string
	CheckConnectionServer(id string) (bool, error)
	ClearProjectFocus() (ProjectStatus, error)
	CloseAllBrowserTabs()
	CommandHistory() []string
	CompleteAccountSignIn() (AccountState, error)
	CompleteMCPSignIn(serverName string) error
	CompleteSignIn(providerName string, pasted string) (ModelInfo, error)
	CompressArtifacts(paths []string) (CompressReport, error)
	ComputerControlOn() bool
	ConnectAccount(id string, token string, baseURL string, targets []string) (connect.Account, error)
	Connections() []connect.Status
	ConsolidateMemory(scope string) (MemoryConsolidation, error)
	CreatePullRequest(title string, head string, base string, body string, draft bool) PRCreated
	CreateSpace(name string) (Space, error)
	CurrentSessionID() string
	CurrentShell() ShellOption
	CurrentSpace() string
	CustomProviders() []CustomProviderRow
	DeckCaptureDrawing(relPath string, slide int, ink string) (string, error)
	DeckFormats() []DeckFormat
	DeckPickScript(token string, opts string) string
	DeckStopPickScript() string
	DelegateSwitches() DelegateSettings
	DeleteArtifact(path string) error
	DeleteDeck(relPath string) error
	DeleteIdentityFile(name string) error
	DeletePromptPreset(name string) error
	DeleteSession(id string) error
	DeleteSpace(name string) error
	DeleteSubagentProfile(name string) error
	DisconnectAccount(id string) error
	DismissRecurringRequest(normalized string, sampleText string) error
	DismissTaskChip(id string)
	EnabledProviders() []string
	EnginesFor(family string, agent string) []connect.Status
	ExportDeck(relPath string, format string) (string, error)
	ExportPath(path string) (string, error)
	FileStillThere(relPath string) string
	ForgetMemoryScope(scope string) error
	ForgetProject(root string) (ProjectStatus, error)
	GetContextBreakdown() ContextBreakdown
	GetModelInfo() ModelInfo
	GetProjectStatus() ProjectStatus
	GetRepoMapGraph(maxNodes int) RepoMapGraph
	GitBranches() []GitBranch
	GitChangedFiles() []ChangedFile
	GitCommitChanges(hash string) []GitFileChange
	GitCommitFileDiff(hash string, path string) string
	GitCommitFiles(message string, files []string) error
	GitCreateBranch(name string) (string, error)
	GitFileDiff(path string) string
	GitLog(before string, limit int) GitLogPage
	GitSuggestCommitMessage(files []string) (string, error)
	GitSuggestSplitCommits() ([]GitCommitGroup, error)
	GitSwitchBranch(name string) (string, error)
	GitWorkingTree() ([]GitFileChange, error)
	GrantedComputerApps() []string
	GuideTopics() []model.GuideTopic
	HistoryFault() StoreFault
	ImageStatus() string
	ImportSessionFrom(path string) (string, error)
	ImportSignIn(providerName string) (ModelInfo, error)
	ImportableSignIns() []string
	InstallCapabilities(capabilities []string) bool
	InstallSkillFromGitHub(repoURL string) (string, error)
	InstallSkillsFromZipAt(path string) (string, error)
	InstallVoiceEngine(side string, id string) error
	Interject(text string) error
	LearnedEntries(scope string) []string
	LearnedMemory(scope string) string
	LearnedScopeInfos() []MemoryScopeInfo
	LearnedScopes() []string
	LearningEnabled() bool
	ListAllSessions() []SessionMeta
	ListArtifacts() []Artifact
	ListArtifactsForSession(sessionID string) ArtifactPage
	ListArtifactsIn(want string) ArtifactPage
	ListChairs() []Chair
	ListDecidedChanges(limit int) []PendingChange
	ListDecidedIssues(limit int) []PendingChange
	ListDecidedSkillProposals(limit int) []PendingChange
	ListDecks() []Deck
	ListDecksIn(want string) DeckPage
	ListExternalSkills() []skill.DiscoveredSkill
	ListIdentityFiles() ([]IdentityFile, error)
	ListImageEngines() []VoiceEngineInfo
	ListMCPServers() []MCPServerInfo
	ListModes() []mode.Mode
	ListPendingChanges() []PendingChange
	ListPromptPresets() []command.Preset
	ListReceivedJobs(limit int) []ReceivedJob
	ListRecurringRequests() []RecurringRequest
	ListSessions() []SessionMeta
	ListSessionsAt(desk string) []SessionMeta
	ListSessionsForDoor(filter DeskFilter) []SessionMeta
	ListSkillProposals() []PendingChange
	ListSkills() []SkillInfo
	ListSpeechEngines() []VoiceEngineInfo
	ListSpeechModels() []SpeechModelInfo
	ListSubagentProfiles() []subagent.Profile
	ListSystemIssues() []PendingChange
	ListTTSEngines() []VoiceEngineInfo
	ListTTSVoices() ([]TTSVoiceInfo, error)
	ListTaskChips() []TaskChip
	ListTools() []SkillInfo
	LoadSession(id string) ([]SessionMessage, error)
	LoadSessionAnyProject(id string) ([]SessionMessage, error)
	MCPConfigPath() string
	MCPFolderPath() (string, error)
	MCPSignInStatus(serverName string) oauth.Status
	MarkIssueReported(id int64) error
	MarkVideoCheckSeen()
	MemoryFolderPath() (string, error)
	MobileRemoteQR() string
	MobileRemoteStatus() RemoteStatus
	ModelPriceSource() PriceSource
	ModelStatus() string
	MoveLearnedEntry(fromScope string, toScope string, index int) error
	NewChairSession(chair string) (string, error)
	NewSession() (string, error)
	NewSessionAt(desk string) (string, error)
	NewSessionInSpace(name string) (string, error)
	NoteProviderQuotas(providerName string, quotas []model.Quota)
	OpenComputerApps() []ComputerAppRow
	OpenProjectPath(root string) (ProjectStatus, error)
	PairedDevices() []RemoteDevice
	PausePlanRun(sessionID string)
	PendingChangeByID(id int64) PendingChange
	PendingIssueCount() int
	PendingLearnedCount() int
	PendingRestore(id string) []string
	PendingSkillTuneCount() int
	PendingUndo() []string
	PictureBytes(relPath string) (ExportFile, error)
	PlacementTargets() []PlacementTarget
	PlanRunning(sessionID string) bool
	PreparedReplyOn() bool
	PriceModels(providerName string, models []string) []ModelListing
	ProgramIcon(p0 string) string
	ProjectFilePath(relPath string) (string, error)
	ProjectTree() []TreeNode
	PromptsFolderPath() (string, error)
	ProviderAPIKeyURL(providerName string) string
	ProviderBaseURL(providerName string) string
	ProviderBaseURLIsCustom(providerName string) bool
	ProviderKeyChanged(providerName string) (ModelInfo, error)
	ProviderQuotas(providerName string) ([]model.Quota, bool)
	ProviderWireFormats(providerName string) []string
	PullRequestChecks(sha string) []gh.CheckRun
	PullRequestFiles(number int) []gh.PRFile
	PullRequests() PRRoom
	PullRequestsState(state string) PRRoom
	RateTurn(messageID int64, verdict string)
	ReadFile(relPath string) (string, error)
	ReadIdentityFile(name string) (string, error)
	ReadImageDataURL(relPath string) (string, error)
	ReadSubagentProfile(name string) (string, error)
	ReadWorkbook(relPath string) (*ooxml.WorkbookPreview, error)
	ReadyToRestart() error
	RecentAgentPages(limit int) []AgentPage
	RecentDebugLog() []string
	RecentProjects() []ProjectMeta
	RefreshModelFacts()
	RefreshSkills()
	RegenerateReply(revertFiles bool) (RegenerateResult, error)
	RejectPendingChange(id int64) error
	RelativizePath(absPath string) (string, error)
	RemoveCustomProviderRow(id string) ([]string, error)
	RemoveExternalSkill(name string) error
	RemoveMCPServer(name string) error
	RemovePresetImage(name string) error
	RemoveSpaceContext(name string, file string) ([]string, error)
	RemoveWorkspaceFolder(path string) ([]WorkspaceFolder, error)
	RequiresAPIKey(providerName string) bool
	ResendEdited(text string, revertFiles bool) (TurnReply, error)
	ResolveAddress(input string) Address
	RestorePoints() []RestorePoint
	RestoreRecurringRequest(normalized string) error
	ResumePlanRun(sessionID string)
	RetryActiveProvider() ModelInfo
	RetryFailedTurn(text string) (TurnReply, error)
	ReviewPullRequest(number int) (string, error)
	RevokeComputerApp(name string) error
	RevokeDevice(id string) error
	RewindTo(id string) (UndoResult, error)
	RunChatCommand(command string) (RunBlockResult, error)
	RunChatScript(lang string, source string) (RunBlockResult, error)
	RunSessionReview(sessionID string) (int, error)
	RunSkillTuneup() (int, error)
	RunnableLanguages() map[string]string
	SaveAgentProfile(name string, body string) error
	SaveChairStarters(name string, locale string, set subagent.StarterSet) error
	SaveChatFile(sourcePath string) (string, error)
	SaveChatImage(sourcePath string) (string, error)
	SaveChatImageData(dataURL string) (string, error)
	SaveIdentityFile(name string, content string) error
	SaveLearnedEntry(scope string, index int, text string) error
	SaveMCPServer(originalName string, server config.MCPServerConfig) error
	SavePlanText(sessionID string, text string) string
	SavePromptPreset(name string, body string) error
	SaveSubagentProfile(name string, body string) error
	SearchAllSessions(query string) []SessionMeta
	SearchSessions(query string) []SessionMeta
	SearchSessionsForDoor(query string, filter DeskFilter) []SessionMeta
	SendMessage(text string, to string) (TurnReply, error)
	SessionAgent(id string) string
	SessionEdits(sessionID string) EditPage
	SessionExportBytes(id string, format string) (ExportFile, error)
	SessionMode(id string) string
	SessionPlan(sessionID string) Plan
	SessionPlanReports(sessionID string) []PlanReport
	SessionReviewAuto() bool
	SessionSourceCount(sessionID string) int
	SessionSources(sessionID string) []Source
	SessionSpend(id string) SessionSpend
	SessionTranscript(id string) ([]SessionMessage, error)
	SessionsInSpace(name string) []SessionMeta
	SetAgentOff(name string, off bool) DelegateSettings
	SetBusyLayer(id string, on bool) []BusyLayer
	SetComputerControlOn(on bool) error
	SetConnectionStartCommand(id string, command string) error
	SetConnectionTargets(id string, targets []string) error
	SetDelegateOff(kind string, off bool) DelegateSettings
	SetImageEngine(id string) error
	SetImageModelName(name string) error
	SetLearningEnabled(on bool) error
	SetMCPServerTargets(name string, targets []string) error
	SetPlanStepStop(sessionID string, n int, on bool)
	SetPreparedReplyOn(on bool) error
	SetPresetImageFrom(name string, path string) (string, error)
	SetProviderBaseURL(providerName string, baseURL string) (ModelInfo, error)
	SetProviderEnabled(providerName string, enabled bool) ([]string, error)
	SetProviderWireFormat(format string) (ModelInfo, error)
	SetSessionReviewAuto(on bool) error
	SetShell(setting string) error
	SetSkillTuneAuto(on bool) error
	SetSpeechEngine(id string) error
	SetSpeechModel(path string) error
	SetSpeechModelName(name string) error
	SetStance(name string) (string, error)
	SetSubagentModel(name string, modelName string) error
	SetTTSEngine(id string) error
	SetTTSModelName(name string) error
	SetTTSVoice(id string) error
	SetUILocale(locale string) error
	SetUserName(name string) error
	Shells() []ShellOption
	SignInMethods() []oauth.Method
	SignInStatus(providerName string) oauth.Status
	SignOut(providerName string) (ModelInfo, error)
	SkillScanIssues() []string
	SkillTuneAuto() bool
	SkillsDir() string
	SkillsFolderPath() (string, error)
	SpaceFolderPath(name string) (string, error)
	Spaces() []Space
	SpeakText(text string) (string, error)
	SpeechModelDirPath(dir string) (string, error)
	SpeechModelDirs() []SpeechDirInfo
	SpeechModelFolderPath(path string) (string, error)
	SpeechPlaying(jobID string, seq int)
	SpeechStatus() string
	Stance() string
	Stances() []string
	StartAccountSignIn(provider string) (string, error)
	StartConnectionServer(id string) error
	StartMCPSignIn(serverName string, resourceURL string) (SignInPrompt, error)
	StartMobileRemote() RemoteStatus
	StartPlanRun(sessionID string) PlanRunStart
	StartSignIn(providerName string) (SignInPrompt, error)
	StartSpeech(text string) (string, error)
	StopBackgroundRun(runID string) int
	StopBackgroundTask(id string) bool
	StopBrowsing()
	StopMobileRemote() RemoteStatus
	StopPlanRun(sessionID string)
	StopQueuedTasks() int
	StopSpeech(jobID string)
	SubagentsFolderPath() (string, error)
	SuggestPRDetails(head string, base string) (PRSuggestion, error)
	SupportedProviders() []string
	SupportedThinkLevels() []string
	SwitchApprovalMode(mode string) (ModelInfo, error)
	SwitchModel(modelName string) (ModelInfo, error)
	SwitchProvider(provider string) (ModelInfo, error)
	SwitchThinkLevel(level string) (ModelInfo, error)
	SwitchVariant(index int) (RegenerateResult, error)
	SynthesizeHabit(sessionID string, hint string) (int64, error)
	TTSStatus() string
	TerminalAttach(sessionID string) string
	TerminalClose(sessionID string) error
	TerminalResize(sessionID string, cols int, rows int) error
	TerminalShells() []ShellProfile
	TerminalStart(shellPath string, cols int, rows int) (string, error)
	TerminalWrite(sessionID string, data string) error
	TestMCPServer(name string) MCPServerInfo
	ToggleMCPServer(name string, disabled bool) error
	ToolBlockTokens() int
	ToolCounts() ToolCounts
	ToolInstallPlan(name string) ToolInstallPlan
	TranscribeMicAudio(dataURL string) (string, error)
	TurnInFlight() TurnStatus
	TurnRating(messageID int64) string
	UndoLastTurn() (UndoResult, error)
	UsageStats() (UsageStats, error)
	UseEngine(family string, agent string, id string) error
	UserName() string
	VerifyConnection(id string) (connect.Account, error)
	VideoCheckSeen() bool
	VideoEditorCommand() []string
	VideoEditorEnvironment() map[string]string
	VideoEditorHelpURL(what string) string
	VideoEditorTools() []string
	VideoReadiness(agent string) VideoReadiness
	VideoToolingStatus() VideoToolingStatus
	WorkbenchTabsChanged(sessionID string, tabs []DeskTab)
	WorkspaceFolders() []WorkspaceFolder
	WriteFile(relPath string, content string) error
}

var _ API = (*Engine)(nil)
