// Code generated by internal/engine/gen. DO NOT EDIT.

package engine

import (
	"github.com/Mikedev115/Aetox/internal/capability"
	"github.com/Mikedev115/Aetox/internal/cliagent"
	"github.com/Mikedev115/Aetox/internal/command"
	"github.com/Mikedev115/Aetox/internal/config"
	"github.com/Mikedev115/Aetox/internal/connect"
	gh "github.com/Mikedev115/Aetox/internal/github"
	"github.com/Mikedev115/Aetox/internal/machine"
	"github.com/Mikedev115/Aetox/internal/mode"
	"github.com/Mikedev115/Aetox/internal/model"
	"github.com/Mikedev115/Aetox/internal/oauth"
	"github.com/Mikedev115/Aetox/internal/ooxml"
	"github.com/Mikedev115/Aetox/internal/skill"
	"github.com/Mikedev115/Aetox/internal/subagent"
)

// API is every exported method of *Engine: what the screen may ask of the
// engine, in one process today and across a socket in phase 2 (§248).
type API interface {
	AcceptsAPIKey(providerName string) bool
	ActiveModelFor(providerName string) (string, string)
	AddCustomProviderRow(name string, baseURL string) (string, error)
	AddLearnedEntry(scope string, text string) error
	AddMCPServer(name string, command []string) error
	AddSpaceContextFiles(name string, picked []string) ([]string, error)
	AddStudioLibraryAt(dir string) (bool, error)
	AddWorkspaceFolderAt(dir string) ([]WorkspaceFolder, error)
	AdoptMemoryScope(scope string, targetRoot string) error
	AgentBlocked(name string) bool
	AgentGate(name string) AgentGate
	AgentHomePath(name string) (string, error)
	AgentNeeds(name string) []subagent.Requirement
	AgentPackageBytes(name string) (ExportFile, error)
	AgentSkills(name string) []AgentSkillInfo
	AgentSkillsFolderPath(name string) (string, error)
	AgentsFolderPath() (string, error)
	AnswerUserQuestion(sessionID string, answer string)
	AnyTurnRunning() bool
	AppCredit() string
	AppVersion() string
	ApplyMemoryLines(scope string, lines []string) error
	ApprovePendingChange(id int64) error
	ApprovePendingChangeTo(id int64, scope string) error
	ArtifactPath(path string) (string, error)
	ArtifactPreview(path string) (ArtifactPreview, error)
	BackgroundRuns() []BackgroundRun
	BackgroundTasks() []BackgroundTask
	BrowseFolderAt(dir string) (string, error)
	BrowseRoot() string
	BusySignal() []BusyLayer
	CancelMCPSignIn(serverName string)
	CancelPendingModel() ModelInfo
	CancelStudioScan()
	CancelTurn()
	CapabilitiesInstalling() bool
	CapabilityForServer(server string) string
	CapabilityStatuses() []capability.Status
	CatalogModelChoices(canonical string) []string
	ChairStarters(name string, locale string) subagent.StarterSet
	ChairStartersFile(locale string) string
	CheckConnectionServer(id string) (bool, error)
	ClearProjectFocus() (ProjectStatus, error)
	CodeProjectsDir() string
	CommandHistory() []string
	CompleteMCPSignIn(serverName string) error
	CompressArtifacts(paths []string) (CompressReport, error)
	ComputerControlChanged()
	ConnectAccount(id string, token string, baseURL string, targets []string) (connect.Account, error)
	Connections() []connect.Status
	ConsolidateMemory(scope string) (MemoryConsolidation, error)
	CopySkillToAgent(agent string, name string) error
	CreateCodeProject(name string) (string, error)
	CreatePullRequest(title string, head string, base string, body string, draft bool) PRCreated
	CreateSpace(name string) (Space, error)
	CurrentSessionID() string
	CurrentShell() ShellOption
	CurrentSpace() string
	CustomProviders() []CustomProviderRow
	DeckCaptureDrawing(relPath string, slide int, ink string) (string, error)
	DeckExportFiles(relPath string, format string) (DeckExport, error)
	DeckFormats() []DeckFormat
	DelegateSwitches(team string) DelegateSettings
	DeleteArtifact(path string) error
	DeleteDeck(relPath string) error
	DeleteIdentityFile(head string, name string) error
	DeletePromptPreset(name string) error
	DeleteSession(id string) error
	DeleteSpace(name string) error
	DeleteSubagentProfile(name string) error
	DeleteTeam(name string) error
	DeskStarters(desk string, locale string) subagent.StarterSet
	DisconnectAccount(id string) error
	DismissRecurringRequest(normalized string, sampleText string) error
	DismissTaskChip(id string)
	EnabledProviders() []string
	EnginesFor(family string, agent string) []connect.Status
	ExternalEngineStatus(providerName string) cliagent.Status
	FileStillThere(relPath string) string
	ForgetMemoryScope(scope string) error
	ForgetProject(root string) (ProjectStatus, error)
	GetContextBreakdown() ContextBreakdown
	GetModelInfo() ModelInfo
	GetProjectStatus() ProjectStatus
	GetRepoMapGraph(maxNodes int) RepoMapGraph
	GitBranches() []GitBranch
	GitChangedFiles() []ChangedFile
	GitCommitChanges(hash string) []GitFileChange
	GitCommitFileDiff(hash string, path string) string
	GitCommitFiles(message string, files []string) error
	GitCreateBranch(name string) (string, error)
	GitFileDiff(path string) string
	GitLog(before string, limit int) GitLogPage
	GitSplitCancel()
	GitSuggestCommitMessage(files []string) (string, error)
	GitSuggestSplitCommits() ([]GitCommitGroup, error)
	GitSwitchBranch(name string) (string, error)
	GitWorkingTree() ([]GitFileChange, error)
	GuideTopics() []model.GuideTopic
	HandedOverFile(fileURL string) string
	HistoryFault() StoreFault
	HomeDir() string
	ImageStatus() string
	ImportSessionFrom(path string) (string, error)
	InstallCapabilities(capabilities []string) bool
	InstallSkillFromGitHub(repoURL string) (string, error)
	InstallSkillsFromZipAt(path string) (string, error)
	InstallVoiceEngine(side string, id string) error
	Interject(text string) error
	LearnedEntries(scope string) []string
	LearnedMemory(scope string) string
	LearnedScopeInfos() []MemoryScopeInfo
	LearnedScopes() []string
	LearningEnabled() bool
	ListAllSessions() []SessionMeta
	ListArtifacts() []Artifact
	ListArtifactsForSession(sessionID string) ArtifactPage
	ListArtifactsIn(want string) ArtifactPage
	ListChairs() []Chair
	ListDecidedChanges(limit int) []PendingChange
	ListDecidedIssues(limit int) []PendingChange
	ListDecidedSkillProposals(limit int) []PendingChange
	ListDecks() []Deck
	ListDecksIn(want string) DeckPage
	ListDir(path string) (DirListing, error)
	ListExternalSkills() []skill.DiscoveredSkill
	ListIdentityFiles(head string) ([]IdentityFile, error)
	ListImageEngines() []VoiceEngineInfo
	ListMCPServers() []MCPServerInfo
	ListModes() []mode.Mode
	ListPendingChanges() []PendingChange
	ListPromptPresets() []command.Preset
	ListReceivedJobs(limit int) []ReceivedJob
	ListRecurringRequests() []RecurringRequest
	ListSessions() []SessionMeta
	ListSessionsAt(desk string) []SessionMeta
	ListSessionsForDoor(filter DeskFilter) []SessionMeta
	ListSkillProposals() []PendingChange
	ListSkills() []SkillInfo
	ListSpeechEngines() []VoiceEngineInfo
	ListSpeechModels() []SpeechModelInfo
	ListSubagentProfiles() []subagent.Profile
	ListSystemIssues() []PendingChange
	ListTTSEngines() []VoiceEngineInfo
	ListTaskChips() []TaskChip
	ListTeams(desk string) []TeamCard
	ListTools() []SkillInfo
	LoadSession(id string) ([]SessionMessage, error)
	LoadSessionAnyProject(id string) ([]SessionMessage, error)
	MCPConfigPath() string
	MCPFolderPath() (string, error)
	MCPSignInStatus(serverName string) oauth.Status
	MachineInfo() machine.Info
	MarkIssueReported(id int64) error
	MarkVideoCheckSeen()
	MemoryFolderPath() (string, error)
	MobileRemoteQR() string
	MobileRemoteStatus() RemoteStatus
	ModelPriceSource() PriceSource
	ModelStatus() string
	MoveLearnedEntry(fromScope string, toScope string, index int) error
	NewChairSession(chair string) (string, error)
	NewChairSessionAt(desk string, chair string, team string) (string, error)
	NewSession() (string, error)
	NewSessionAt(desk string) (string, error)
	NewSessionInSpace(name string) (string, error)
	NewTeamSession(desk string, team string) (string, error)
	NoteProviderQuotas(providerName string, quotas []model.Quota)
	OpenProjectPath(root string) (ProjectStatus, error)
	PageMarksOn() bool
	PairedDevices() []RemoteDevice
	PausePlanRun(sessionID string)
	PendingChangeByID(id int64) PendingChange
	PendingIssueCount() int
	PendingLearnedCount() int
	PendingRestore(id string) []string
	PendingSkillTuneCount() int
	PendingUndo() []string
	PictureBytes(relPath string) (ExportFile, error)
	PlacementTargets() []PlacementTarget
	PlanRunning(sessionID string) bool
	PrepareToClose()
	PreparedReplyOn() bool
	PriceModels(providerName string, models []string) []ModelListing
	ProjectFilePath(relPath string) (string, error)
	ProjectTree() []TreeNode
	PromptsFolderPath() (string, error)
	ProviderAPIKeyURL(providerName string) string
	ProviderBaseURL(providerName string) string
	ProviderBaseURLIsCustom(providerName string) bool
	ProviderCredentialChanged(providerName string) (ModelInfo, error)
	ProviderQuotas(providerName string) ([]model.Quota, bool)
	ProviderWireFormats(providerName string) []string
	PullRequestChecks(sha string) []gh.CheckRun
	PullRequestFiles(number int) []gh.PRFile
	PullRequests() PRRoom
	PullRequestsState(state string) PRRoom
	RateTurn(messageID int64, verdict string)
	ReadDeskFile(name string) (DeskFile, error)
	ReadFile(relPath string) (string, error)
	ReadIdentityFile(head string, name string) (string, error)
	ReadImageDataURL(relPath string) (string, error)
	ReadSubagentProfile(name string) (string, error)
	ReadWorkbook(relPath string) (*ooxml.WorkbookPreview, error)
	ReadyToRestart() error
	RecentAgentPages(limit int) []AgentPage
	RecentDebugLog() []string
	RecentProjects() []ProjectMeta
	RefreshModelFacts()
	RefreshSkills()
	RegenerateReply(revertFiles bool) (RegenerateResult, error)
	RejectPendingChange(id int64) error
	RelativizePath(absPath string) (string, error)
	RememberTTSVoice(id string)
	RemoveAgentSkill(agent string, name string) error
	RemoveCustomProviderRow(id string) ([]string, error)
	RemoveExternalSkill(name string) error
	RemoveMCPServer(name string) error
	RemovePresetImage(name string) error
	RemoveSpaceContext(name string, file string) ([]string, error)
	RemoveStudioLibrary(id string) ([]StudioLibraryView, error)
	RemoveWorkspaceFolder(path string) ([]WorkspaceFolder, error)
	RequiresAPIKey(providerName string) bool
	RescanStudioLibrary(id string) (bool, error)
	ResendEdited(text string, revertFiles bool) (TurnReply, error)
	ResetDeskFile(name string) error
	ResolveAddress(input string) Address
	ResolveWorkbenchURL(input string) (string, string)
	RestorePoints() []RestorePoint
	RestoreRecurringRequest(normalized string) error
	ResumePlanRun(sessionID string)
	RetryActiveProvider() ModelInfo
	RetryFailedTurn(text string) (TurnReply, error)
	ReviewPullRequest(number int) (string, error)
	RevokeDevice(id string) error
	RewindTo(id string) (UndoResult, error)
	RunChatCommand(command string) (RunBlockResult, error)
	RunChatScript(lang string, source string) (RunBlockResult, error)
	RunSessionReview(sessionID string) (int, error)
	RunSkillTuneup() (int, error)
	RunnableLanguages() map[string]string
	SandboxFile(request string) (string, error)
	SaveAgentProfile(name string, body string) error
	SaveBrowserShot(png []byte, marked bool) (string, error)
	SaveChairStarters(name string, locale string, set subagent.StarterSet) error
	SaveChatFile(sourcePath string) (string, error)
	SaveChatImage(sourcePath string) (string, error)
	SaveChatImageData(dataURL string) (string, error)
	SaveDeskFile(name string, text string) error
	SaveDeskStarters(desk string, locale string, set subagent.StarterSet) error
	SaveIdentityFile(head string, name string, content string) error
	SaveLearnedEntry(scope string, index int, text string) error
	SaveMCPServer(originalName string, server config.MCPServerConfig) error
	SavePlanText(sessionID string, text string) string
	SavePromptPreset(name string, body string) error
	SaveSubagentProfile(name string, body string) error
	SaveTeam(name string, desk string, description string, members []string) error
	SearchAllSessions(query string) []SessionMeta
	SearchSessions(query string) []SessionMeta
	SearchSessionsForDoor(query string, filter DeskFilter) []SessionMeta
	SendMessage(text string, to string) (TurnReply, error)
	SessionAgent(id string) string
	SessionEdits(sessionID string) EditPage
	SessionExportBytes(id string, format string) (ExportFile, error)
	SessionMode(id string) string
	SessionPlan(sessionID string) Plan
	SessionPlanReports(sessionID string) []PlanReport
	SessionReviewAuto() bool
	SessionSourceCount(sessionID string) int
	SessionSources(sessionID string) []Source
	SessionSpend(id string) SessionSpend
	SessionTeam(id string) string
	SessionTranscript(id string) ([]SessionMessage, error)
	SessionsInSpace(name string) []SessionMeta
	SetAgentOff(team string, name string, off bool) DelegateSettings
	SetBusyLayer(id string, on bool) []BusyLayer
	SetCodeProjectsDir(dir string) error
	SetConnectionStartCommand(id string, command string) error
	SetConnectionTargets(id string, targets []string) error
	SetDelegateOff(kind string, off bool) DelegateSettings
	SetImageEngine(id string) error
	SetImageModelName(name string) error
	SetLearningEnabled(on bool) error
	SetMCPServerTargets(name string, targets []string) error
	SetPlanStepStop(sessionID string, n int, on bool)
	SetPreparedReplyOn(on bool) error
	SetPresetImageFrom(name string, path string) (string, error)
	SetProviderBaseURL(providerName string, baseURL string) (ModelInfo, error)
	SetProviderEnabled(providerName string, enabled bool) ([]string, error)
	SetProviderWireFormat(format string) (ModelInfo, error)
	SetSessionReviewAuto(on bool) error
	SetShell(setting string) error
	SetSkillTuneAuto(on bool) error
	SetSpeechEngine(id string) error
	SetSpeechModel(path string) error
	SetSpeechModelName(name string) error
	SetStance(name string) (string, error)
	SetSubagentModel(name string, modelName string) error
	SetTTSEngine(id string) error
	SetTTSModelName(name string) error
	SetUILocale(locale string) error
	SetUserName(name string) error
	Shells() []ShellOption
	SkillScanIssues() []string
	SkillTuneAuto() bool
	SkillsDir() string
	SkillsFolderPath() (string, error)
	SpaceFolderPath(name string) (string, error)
	Spaces() []Space
	SpeechModelDirPath(dir string) (string, error)
	SpeechModelDirs() []SpeechDirInfo
	SpeechModelFolderPath(path string) (string, error)
	SpeechStatus() string
	Stance() string
	Stances() []string
	StartConnectionServer(id string) error
	StartMCPSignIn(serverName string, resourceURL string) (SignInPrompt, error)
	StartMobileRemote() RemoteStatus
	StartPlanRun(sessionID string) PlanRunStart
	StopBackgroundRun(runID string) int
	StopBackgroundTask(id string) bool
	StopBrowsing()
	StopMobileRemote() RemoteStatus
	StopPlanRun(sessionID string)
	StopQueuedTasks() int
	StudioAssetPath(id string) (string, error)
	StudioAssets(q StudioAssetQuery) StudioAssetPage
	StudioLibraries() []StudioLibraryView
	StudioLibraryPath(id string) (string, error)
	StudioScanning() bool
	StudioSetHidden(id string, hidden bool) error
	StudioSetKind(id string, kind string) error
	StudioThumbs(ids []string) map[string]string
	SubagentsFolderPath() (string, error)
	SuggestPRDetails(head string, base string) (PRSuggestion, error)
	SupportedProviders() []string
	SupportedThinkLevels() []string
	SupportedThinkLevelsFor(provider string, modelName string) []string
	SwitchApprovalMode(mode string) (ModelInfo, error)
	SwitchModel(modelName string) (ModelInfo, error)
	SwitchProvider(provider string) (ModelInfo, error)
	SwitchThinkLevel(level string) (ModelInfo, error)
	SwitchVariant(index int) (RegenerateResult, error)
	SynthesizeHabit(sessionID string, hint string) (int64, error)
	TeamsFolderPath() (string, error)
	TerminalAttach(sessionID string) string
	TerminalClose(sessionID string) error
	TerminalResize(sessionID string, cols int, rows int) error
	TerminalShells() []ShellProfile
	TerminalStart(shellPath string, cols int, rows int) (string, error)
	TerminalWrite(sessionID string, data string) error
	TestMCPServer(name string) MCPServerInfo
	ToggleMCPServer(name string, disabled bool) error
	ToolBlockTokens() int
	ToolCounts() ToolCounts
	ToolInstallPlan(name string) ToolInstallPlan
	TranscribeMicAudio(dataURL string) (string, error)
	TurnInFlight() TurnStatus
	TurnRating(messageID int64) string
	UndoLastTurn() (UndoResult, error)
	UsageStats() (UsageStats, error)
	UseEngine(family string, agent string, id string) error
	UserName() string
	VerifyConnection(id string) (connect.Account, error)
	VideoCheckSeen() bool
	VideoEditorCommand() []string
	VideoEditorEnvironment() map[string]string
	VideoEditorHelpURL(what string) string
	VideoEditorTools() []string
	VideoReadiness(agent string) VideoReadiness
	VideoToolingStatus() VideoToolingStatus
	VoiceSettings() VoiceSettings
	WorkbenchTabsChanged(sessionID string, tabs []DeskTab)
	WorkspaceFolders() []WorkspaceFolder
	WriteFile(relPath string, content string) error
}

var _ API = (*Engine)(nil)
