// Code generated by internal/engine/gen. DO NOT EDIT.

package rpc

// The screen's end of every engine binding (§248 phase 2): *Client is
// engine.API over the wire. A method with no error in its signature
// answers its zero value when the wire fails and tells the failure hook.

import (
	"github.com/Mikedev115/Aetox/internal/capability"
	"github.com/Mikedev115/Aetox/internal/cliagent"
	"github.com/Mikedev115/Aetox/internal/command"
	"github.com/Mikedev115/Aetox/internal/config"
	"github.com/Mikedev115/Aetox/internal/connect"
	"github.com/Mikedev115/Aetox/internal/engine"
	gh "github.com/Mikedev115/Aetox/internal/github"
	"github.com/Mikedev115/Aetox/internal/machine"
	"github.com/Mikedev115/Aetox/internal/mode"
	"github.com/Mikedev115/Aetox/internal/model"
	"github.com/Mikedev115/Aetox/internal/oauth"
	"github.com/Mikedev115/Aetox/internal/ooxml"
	"github.com/Mikedev115/Aetox/internal/skill"
	"github.com/Mikedev115/Aetox/internal/subagent"
)

func (c *Client) AcceptsAPIKey(providerName string) bool {
	var out0 bool
	if err := c.call("AcceptsAPIKey", []any{providerName}, &out0); err != nil {
		c.failed("AcceptsAPIKey", err)
	}
	return out0
}

func (c *Client) ActiveModelFor(providerName string) (string, string) {
	var out0 string
	var out1 string
	if err := c.callN("ActiveModelFor", []any{providerName}, &out0, &out1); err != nil {
		c.failed("ActiveModelFor", err)
	}
	return out0, out1
}

func (c *Client) AddCustomProviderRow(name string, baseURL string) (string, error) {
	var out0 string
	err := c.call("AddCustomProviderRow", []any{name, baseURL}, &out0)
	return out0, err
}

func (c *Client) AddLearnedEntry(scope string, text string) error {
	return c.call("AddLearnedEntry", []any{scope, text}, nil)
}

func (c *Client) AddMCPServer(name string, command []string) error {
	return c.call("AddMCPServer", []any{name, command}, nil)
}

func (c *Client) AddSpaceContextFiles(name string, picked []string) ([]string, error) {
	var out0 []string
	err := c.call("AddSpaceContextFiles", []any{name, picked}, &out0)
	return out0, err
}

func (c *Client) AddStudioLibraryAt(dir string) (bool, error) {
	var out0 bool
	err := c.call("AddStudioLibraryAt", []any{dir}, &out0)
	return out0, err
}

func (c *Client) AddWorkspaceFolderAt(dir string) ([]engine.WorkspaceFolder, error) {
	var out0 []engine.WorkspaceFolder
	err := c.call("AddWorkspaceFolderAt", []any{dir}, &out0)
	return out0, err
}

func (c *Client) AdoptMemoryScope(scope string, targetRoot string) error {
	return c.call("AdoptMemoryScope", []any{scope, targetRoot}, nil)
}

func (c *Client) AgentBlocked(name string) bool {
	var out0 bool
	if err := c.call("AgentBlocked", []any{name}, &out0); err != nil {
		c.failed("AgentBlocked", err)
	}
	return out0
}

func (c *Client) AgentGate(name string) engine.AgentGate {
	var out0 engine.AgentGate
	if err := c.call("AgentGate", []any{name}, &out0); err != nil {
		c.failed("AgentGate", err)
	}
	return out0
}

func (c *Client) AgentHomePath(name string) (string, error) {
	var out0 string
	err := c.call("AgentHomePath", []any{name}, &out0)
	return out0, err
}

func (c *Client) AgentNeeds(name string) []subagent.Requirement {
	var out0 []subagent.Requirement
	if err := c.call("AgentNeeds", []any{name}, &out0); err != nil {
		c.failed("AgentNeeds", err)
	}
	return out0
}

func (c *Client) AgentPackageBytes(name string) (engine.ExportFile, error) {
	var out0 engine.ExportFile
	err := c.call("AgentPackageBytes", []any{name}, &out0)
	return out0, err
}

func (c *Client) AgentSkills(name string) []engine.AgentSkillInfo {
	var out0 []engine.AgentSkillInfo
	if err := c.call("AgentSkills", []any{name}, &out0); err != nil {
		c.failed("AgentSkills", err)
	}
	return out0
}

func (c *Client) AgentSkillsFolderPath(name string) (string, error) {
	var out0 string
	err := c.call("AgentSkillsFolderPath", []any{name}, &out0)
	return out0, err
}

func (c *Client) AgentsFolderPath() (string, error) {
	var out0 string
	err := c.call("AgentsFolderPath", nil, &out0)
	return out0, err
}

func (c *Client) AnswerUserQuestion(sessionID string, answer string) {
	if err := c.call("AnswerUserQuestion", []any{sessionID, answer}, nil); err != nil {
		c.failed("AnswerUserQuestion", err)
	}
}

func (c *Client) AnyTurnRunning() bool {
	var out0 bool
	if err := c.call("AnyTurnRunning", nil, &out0); err != nil {
		c.failed("AnyTurnRunning", err)
	}
	return out0
}

func (c *Client) AppCredit() string {
	var out0 string
	if err := c.call("AppCredit", nil, &out0); err != nil {
		c.failed("AppCredit", err)
	}
	return out0
}

func (c *Client) AppVersion() string {
	var out0 string
	if err := c.call("AppVersion", nil, &out0); err != nil {
		c.failed("AppVersion", err)
	}
	return out0
}

func (c *Client) ApplyMemoryLines(scope string, lines []string) error {
	return c.call("ApplyMemoryLines", []any{scope, lines}, nil)
}

func (c *Client) ApprovePendingChange(id int64) error {
	return c.call("ApprovePendingChange", []any{id}, nil)
}

func (c *Client) ApprovePendingChangeTo(id int64, scope string) error {
	return c.call("ApprovePendingChangeTo", []any{id, scope}, nil)
}

func (c *Client) ArtifactPath(path string) (string, error) {
	var out0 string
	err := c.call("ArtifactPath", []any{path}, &out0)
	return out0, err
}

func (c *Client) ArtifactPreview(path string) (engine.ArtifactPreview, error) {
	var out0 engine.ArtifactPreview
	err := c.call("ArtifactPreview", []any{path}, &out0)
	return out0, err
}

func (c *Client) BackgroundRuns() []engine.BackgroundRun {
	var out0 []engine.BackgroundRun
	if err := c.call("BackgroundRuns", nil, &out0); err != nil {
		c.failed("BackgroundRuns", err)
	}
	return out0
}

func (c *Client) BackgroundTasks() []engine.BackgroundTask {
	var out0 []engine.BackgroundTask
	if err := c.call("BackgroundTasks", nil, &out0); err != nil {
		c.failed("BackgroundTasks", err)
	}
	return out0
}

func (c *Client) BrowseFolderAt(dir string) (string, error) {
	var out0 string
	err := c.call("BrowseFolderAt", []any{dir}, &out0)
	return out0, err
}

func (c *Client) BrowseRoot() string {
	var out0 string
	if err := c.call("BrowseRoot", nil, &out0); err != nil {
		c.failed("BrowseRoot", err)
	}
	return out0
}

func (c *Client) BusySignal() []engine.BusyLayer {
	var out0 []engine.BusyLayer
	if err := c.call("BusySignal", nil, &out0); err != nil {
		c.failed("BusySignal", err)
	}
	return out0
}

func (c *Client) CancelMCPSignIn(serverName string) {
	if err := c.call("CancelMCPSignIn", []any{serverName}, nil); err != nil {
		c.failed("CancelMCPSignIn", err)
	}
}

func (c *Client) CancelPendingModel() engine.ModelInfo {
	var out0 engine.ModelInfo
	if err := c.call("CancelPendingModel", nil, &out0); err != nil {
		c.failed("CancelPendingModel", err)
	}
	return out0
}

func (c *Client) CancelStudioScan() {
	if err := c.call("CancelStudioScan", nil, nil); err != nil {
		c.failed("CancelStudioScan", err)
	}
}

func (c *Client) CancelTurn() {
	if err := c.call("CancelTurn", nil, nil); err != nil {
		c.failed("CancelTurn", err)
	}
}

func (c *Client) CapabilitiesInstalling() bool {
	var out0 bool
	if err := c.call("CapabilitiesInstalling", nil, &out0); err != nil {
		c.failed("CapabilitiesInstalling", err)
	}
	return out0
}

func (c *Client) CapabilityForServer(server string) string {
	var out0 string
	if err := c.call("CapabilityForServer", []any{server}, &out0); err != nil {
		c.failed("CapabilityForServer", err)
	}
	return out0
}

func (c *Client) CapabilityStatuses() []capability.Status {
	var out0 []capability.Status
	if err := c.call("CapabilityStatuses", nil, &out0); err != nil {
		c.failed("CapabilityStatuses", err)
	}
	return out0
}

func (c *Client) CatalogModelChoices(canonical string) []string {
	var out0 []string
	if err := c.call("CatalogModelChoices", []any{canonical}, &out0); err != nil {
		c.failed("CatalogModelChoices", err)
	}
	return out0
}

func (c *Client) ChairStarters(name string, locale string) subagent.StarterSet {
	var out0 subagent.StarterSet
	if err := c.call("ChairStarters", []any{name, locale}, &out0); err != nil {
		c.failed("ChairStarters", err)
	}
	return out0
}

func (c *Client) ChairStartersFile(locale string) string {
	var out0 string
	if err := c.call("ChairStartersFile", []any{locale}, &out0); err != nil {
		c.failed("ChairStartersFile", err)
	}
	return out0
}

func (c *Client) CheckConnectionServer(id string) (bool, error) {
	var out0 bool
	err := c.call("CheckConnectionServer", []any{id}, &out0)
	return out0, err
}

func (c *Client) ClearProjectFocus() (engine.ProjectStatus, error) {
	var out0 engine.ProjectStatus
	err := c.call("ClearProjectFocus", nil, &out0)
	return out0, err
}

func (c *Client) CodeProjectsDir() string {
	var out0 string
	if err := c.call("CodeProjectsDir", nil, &out0); err != nil {
		c.failed("CodeProjectsDir", err)
	}
	return out0
}

func (c *Client) CommandHistory() []string {
	var out0 []string
	if err := c.call("CommandHistory", nil, &out0); err != nil {
		c.failed("CommandHistory", err)
	}
	return out0
}

func (c *Client) CompleteMCPSignIn(serverName string) error {
	return c.call("CompleteMCPSignIn", []any{serverName}, nil)
}

func (c *Client) CompressArtifacts(paths []string) (engine.CompressReport, error) {
	var out0 engine.CompressReport
	err := c.call("CompressArtifacts", []any{paths}, &out0)
	return out0, err
}

func (c *Client) ComputerControlChanged() {
	if err := c.call("ComputerControlChanged", nil, nil); err != nil {
		c.failed("ComputerControlChanged", err)
	}
}

func (c *Client) ConnectAccount(id string, token string, baseURL string, targets []string) (connect.Account, error) {
	var out0 connect.Account
	err := c.call("ConnectAccount", []any{id, token, baseURL, targets}, &out0)
	return out0, err
}

func (c *Client) Connections() []connect.Status {
	var out0 []connect.Status
	if err := c.call("Connections", nil, &out0); err != nil {
		c.failed("Connections", err)
	}
	return out0
}

func (c *Client) ConsolidateMemory(scope string) (engine.MemoryConsolidation, error) {
	var out0 engine.MemoryConsolidation
	err := c.call("ConsolidateMemory", []any{scope}, &out0)
	return out0, err
}

func (c *Client) ContinueInNewSession(sessionID string, points []string) (string, error) {
	var out0 string
	err := c.call("ContinueInNewSession", []any{sessionID, points}, &out0)
	return out0, err
}

func (c *Client) CopySkillToAgent(agent string, name string) error {
	return c.call("CopySkillToAgent", []any{agent, name}, nil)
}

func (c *Client) CreateCodeProject(name string) (string, error) {
	var out0 string
	err := c.call("CreateCodeProject", []any{name}, &out0)
	return out0, err
}

func (c *Client) CreatePullRequest(title string, head string, base string, body string, draft bool) engine.PRCreated {
	var out0 engine.PRCreated
	if err := c.call("CreatePullRequest", []any{title, head, base, body, draft}, &out0); err != nil {
		c.failed("CreatePullRequest", err)
	}
	return out0
}

func (c *Client) CreateSpace(name string) (engine.Space, error) {
	var out0 engine.Space
	err := c.call("CreateSpace", []any{name}, &out0)
	return out0, err
}

func (c *Client) CurrentSessionID() string {
	var out0 string
	if err := c.call("CurrentSessionID", nil, &out0); err != nil {
		c.failed("CurrentSessionID", err)
	}
	return out0
}

func (c *Client) CurrentShell() engine.ShellOption {
	var out0 engine.ShellOption
	if err := c.call("CurrentShell", nil, &out0); err != nil {
		c.failed("CurrentShell", err)
	}
	return out0
}

func (c *Client) CurrentSpace() string {
	var out0 string
	if err := c.call("CurrentSpace", nil, &out0); err != nil {
		c.failed("CurrentSpace", err)
	}
	return out0
}

func (c *Client) CustomProviders() []engine.CustomProviderRow {
	var out0 []engine.CustomProviderRow
	if err := c.call("CustomProviders", nil, &out0); err != nil {
		c.failed("CustomProviders", err)
	}
	return out0
}

func (c *Client) DeckCaptureDrawing(relPath string, slide int, ink string) (string, error) {
	var out0 string
	err := c.call("DeckCaptureDrawing", []any{relPath, slide, ink}, &out0)
	return out0, err
}

func (c *Client) DeckExportFiles(relPath string, format string) (engine.DeckExport, error) {
	var out0 engine.DeckExport
	err := c.call("DeckExportFiles", []any{relPath, format}, &out0)
	return out0, err
}

func (c *Client) DeckFormats() []engine.DeckFormat {
	var out0 []engine.DeckFormat
	if err := c.call("DeckFormats", nil, &out0); err != nil {
		c.failed("DeckFormats", err)
	}
	return out0
}

func (c *Client) DelegateSwitches(team string) engine.DelegateSettings {
	var out0 engine.DelegateSettings
	if err := c.call("DelegateSwitches", []any{team}, &out0); err != nil {
		c.failed("DelegateSwitches", err)
	}
	return out0
}

func (c *Client) DeleteArtifact(path string) error {
	return c.call("DeleteArtifact", []any{path}, nil)
}

func (c *Client) DeleteDeck(relPath string) error {
	return c.call("DeleteDeck", []any{relPath}, nil)
}

func (c *Client) DeleteIdentityFile(head string, name string) error {
	return c.call("DeleteIdentityFile", []any{head, name}, nil)
}

func (c *Client) DeletePromptPreset(name string) error {
	return c.call("DeletePromptPreset", []any{name}, nil)
}

func (c *Client) DeleteSession(id string) error {
	return c.call("DeleteSession", []any{id}, nil)
}

func (c *Client) DeleteSpace(name string) error {
	return c.call("DeleteSpace", []any{name}, nil)
}

func (c *Client) DeleteSubagentProfile(name string) error {
	return c.call("DeleteSubagentProfile", []any{name}, nil)
}

func (c *Client) DeleteTeam(name string) error {
	return c.call("DeleteTeam", []any{name}, nil)
}

func (c *Client) DeskStarters(desk string, locale string) subagent.StarterSet {
	var out0 subagent.StarterSet
	if err := c.call("DeskStarters", []any{desk, locale}, &out0); err != nil {
		c.failed("DeskStarters", err)
	}
	return out0
}

func (c *Client) DisconnectAccount(id string) error {
	return c.call("DisconnectAccount", []any{id}, nil)
}

func (c *Client) DismissRecurringRequest(normalized string, sampleText string) error {
	return c.call("DismissRecurringRequest", []any{normalized, sampleText}, nil)
}

func (c *Client) DismissTaskChip(id string) {
	if err := c.call("DismissTaskChip", []any{id}, nil); err != nil {
		c.failed("DismissTaskChip", err)
	}
}

func (c *Client) DraftHandoff(sessionID string) ([]string, error) {
	var out0 []string
	err := c.call("DraftHandoff", []any{sessionID}, &out0)
	return out0, err
}

func (c *Client) EnabledProviders() []string {
	var out0 []string
	if err := c.call("EnabledProviders", nil, &out0); err != nil {
		c.failed("EnabledProviders", err)
	}
	return out0
}

func (c *Client) EnginesFor(family string, agent string) []connect.Status {
	var out0 []connect.Status
	if err := c.call("EnginesFor", []any{family, agent}, &out0); err != nil {
		c.failed("EnginesFor", err)
	}
	return out0
}

func (c *Client) ExternalEngineStatus(providerName string) cliagent.Status {
	var out0 cliagent.Status
	if err := c.call("ExternalEngineStatus", []any{providerName}, &out0); err != nil {
		c.failed("ExternalEngineStatus", err)
	}
	return out0
}

func (c *Client) FileStillThere(relPath string) string {
	var out0 string
	if err := c.call("FileStillThere", []any{relPath}, &out0); err != nil {
		c.failed("FileStillThere", err)
	}
	return out0
}

func (c *Client) ForgetMemoryScope(scope string) error {
	return c.call("ForgetMemoryScope", []any{scope}, nil)
}

func (c *Client) ForgetProject(root string) (engine.ProjectStatus, error) {
	var out0 engine.ProjectStatus
	err := c.call("ForgetProject", []any{root}, &out0)
	return out0, err
}

func (c *Client) GetContextBreakdown() engine.ContextBreakdown {
	var out0 engine.ContextBreakdown
	if err := c.call("GetContextBreakdown", nil, &out0); err != nil {
		c.failed("GetContextBreakdown", err)
	}
	return out0
}

func (c *Client) GetModelInfo() engine.ModelInfo {
	var out0 engine.ModelInfo
	if err := c.call("GetModelInfo", nil, &out0); err != nil {
		c.failed("GetModelInfo", err)
	}
	return out0
}

func (c *Client) GetProjectStatus() engine.ProjectStatus {
	var out0 engine.ProjectStatus
	if err := c.call("GetProjectStatus", nil, &out0); err != nil {
		c.failed("GetProjectStatus", err)
	}
	return out0
}

func (c *Client) GetRepoMapGraph(maxNodes int) engine.RepoMapGraph {
	var out0 engine.RepoMapGraph
	if err := c.call("GetRepoMapGraph", []any{maxNodes}, &out0); err != nil {
		c.failed("GetRepoMapGraph", err)
	}
	return out0
}

func (c *Client) GitBranches() []engine.GitBranch {
	var out0 []engine.GitBranch
	if err := c.call("GitBranches", nil, &out0); err != nil {
		c.failed("GitBranches", err)
	}
	return out0
}

func (c *Client) GitChangedFiles() []engine.ChangedFile {
	var out0 []engine.ChangedFile
	if err := c.call("GitChangedFiles", nil, &out0); err != nil {
		c.failed("GitChangedFiles", err)
	}
	return out0
}

func (c *Client) GitCommitChanges(hash string) []engine.GitFileChange {
	var out0 []engine.GitFileChange
	if err := c.call("GitCommitChanges", []any{hash}, &out0); err != nil {
		c.failed("GitCommitChanges", err)
	}
	return out0
}

func (c *Client) GitCommitFileDiff(hash string, path string) string {
	var out0 string
	if err := c.call("GitCommitFileDiff", []any{hash, path}, &out0); err != nil {
		c.failed("GitCommitFileDiff", err)
	}
	return out0
}

func (c *Client) GitCommitFiles(message string, files []string) error {
	return c.call("GitCommitFiles", []any{message, files}, nil)
}

func (c *Client) GitCreateBranch(name string) (string, error) {
	var out0 string
	err := c.call("GitCreateBranch", []any{name}, &out0)
	return out0, err
}

func (c *Client) GitFileDiff(path string) string {
	var out0 string
	if err := c.call("GitFileDiff", []any{path}, &out0); err != nil {
		c.failed("GitFileDiff", err)
	}
	return out0
}

func (c *Client) GitLog(before string, limit int) engine.GitLogPage {
	var out0 engine.GitLogPage
	if err := c.call("GitLog", []any{before, limit}, &out0); err != nil {
		c.failed("GitLog", err)
	}
	return out0
}

func (c *Client) GitSplitCancel() {
	if err := c.call("GitSplitCancel", nil, nil); err != nil {
		c.failed("GitSplitCancel", err)
	}
}

func (c *Client) GitSuggestCommitMessage(files []string) (string, error) {
	var out0 string
	err := c.call("GitSuggestCommitMessage", []any{files}, &out0)
	return out0, err
}

func (c *Client) GitSuggestSplitCommits() ([]engine.GitCommitGroup, error) {
	var out0 []engine.GitCommitGroup
	err := c.call("GitSuggestSplitCommits", nil, &out0)
	return out0, err
}

func (c *Client) GitSwitchBranch(name string) (string, error) {
	var out0 string
	err := c.call("GitSwitchBranch", []any{name}, &out0)
	return out0, err
}

func (c *Client) GitWorkingTree() ([]engine.GitFileChange, error) {
	var out0 []engine.GitFileChange
	err := c.call("GitWorkingTree", nil, &out0)
	return out0, err
}

func (c *Client) GuideTopics() []model.GuideTopic {
	var out0 []model.GuideTopic
	if err := c.call("GuideTopics", nil, &out0); err != nil {
		c.failed("GuideTopics", err)
	}
	return out0
}

func (c *Client) HandedOverFile(fileURL string) string {
	var out0 string
	if err := c.call("HandedOverFile", []any{fileURL}, &out0); err != nil {
		c.failed("HandedOverFile", err)
	}
	return out0
}

func (c *Client) HeadName(head string) string {
	var out0 string
	if err := c.call("HeadName", []any{head}, &out0); err != nil {
		c.failed("HeadName", err)
	}
	return out0
}

func (c *Client) HistoryFault() engine.StoreFault {
	var out0 engine.StoreFault
	if err := c.call("HistoryFault", nil, &out0); err != nil {
		c.failed("HistoryFault", err)
	}
	return out0
}

func (c *Client) HomeDir() string {
	var out0 string
	if err := c.call("HomeDir", nil, &out0); err != nil {
		c.failed("HomeDir", err)
	}
	return out0
}

func (c *Client) ImageStatus() string {
	var out0 string
	if err := c.call("ImageStatus", nil, &out0); err != nil {
		c.failed("ImageStatus", err)
	}
	return out0
}

func (c *Client) ImportSessionFrom(path string) (string, error) {
	var out0 string
	err := c.call("ImportSessionFrom", []any{path}, &out0)
	return out0, err
}

func (c *Client) InstallCapabilities(capabilities []string) bool {
	var out0 bool
	if err := c.call("InstallCapabilities", []any{capabilities}, &out0); err != nil {
		c.failed("InstallCapabilities", err)
	}
	return out0
}

func (c *Client) InstallSkillFromGitHub(repoURL string) (string, error) {
	var out0 string
	err := c.call("InstallSkillFromGitHub", []any{repoURL}, &out0)
	return out0, err
}

func (c *Client) InstallSkillsFromZipAt(path string) (string, error) {
	var out0 string
	err := c.call("InstallSkillsFromZipAt", []any{path}, &out0)
	return out0, err
}

func (c *Client) InstallVoiceEngine(side string, id string) error {
	return c.call("InstallVoiceEngine", []any{side, id}, nil)
}

func (c *Client) Interject(text string) error {
	return c.call("Interject", []any{text}, nil)
}

func (c *Client) LearnedEntries(scope string) []string {
	var out0 []string
	if err := c.call("LearnedEntries", []any{scope}, &out0); err != nil {
		c.failed("LearnedEntries", err)
	}
	return out0
}

func (c *Client) LearnedMemory(scope string) string {
	var out0 string
	if err := c.call("LearnedMemory", []any{scope}, &out0); err != nil {
		c.failed("LearnedMemory", err)
	}
	return out0
}

func (c *Client) LearnedScopeInfos() []engine.MemoryScopeInfo {
	var out0 []engine.MemoryScopeInfo
	if err := c.call("LearnedScopeInfos", nil, &out0); err != nil {
		c.failed("LearnedScopeInfos", err)
	}
	return out0
}

func (c *Client) LearnedScopes() []string {
	var out0 []string
	if err := c.call("LearnedScopes", nil, &out0); err != nil {
		c.failed("LearnedScopes", err)
	}
	return out0
}

func (c *Client) LearningEnabled() bool {
	var out0 bool
	if err := c.call("LearningEnabled", nil, &out0); err != nil {
		c.failed("LearningEnabled", err)
	}
	return out0
}

func (c *Client) ListAllSessions() []engine.SessionMeta {
	var out0 []engine.SessionMeta
	if err := c.call("ListAllSessions", nil, &out0); err != nil {
		c.failed("ListAllSessions", err)
	}
	return out0
}

func (c *Client) ListArtifacts() []engine.Artifact {
	var out0 []engine.Artifact
	if err := c.call("ListArtifacts", nil, &out0); err != nil {
		c.failed("ListArtifacts", err)
	}
	return out0
}

func (c *Client) ListArtifactsForSession(sessionID string) engine.ArtifactPage {
	var out0 engine.ArtifactPage
	if err := c.call("ListArtifactsForSession", []any{sessionID}, &out0); err != nil {
		c.failed("ListArtifactsForSession", err)
	}
	return out0
}

func (c *Client) ListArtifactsIn(want string) engine.ArtifactPage {
	var out0 engine.ArtifactPage
	if err := c.call("ListArtifactsIn", []any{want}, &out0); err != nil {
		c.failed("ListArtifactsIn", err)
	}
	return out0
}

func (c *Client) ListChairs() []engine.Chair {
	var out0 []engine.Chair
	if err := c.call("ListChairs", nil, &out0); err != nil {
		c.failed("ListChairs", err)
	}
	return out0
}

func (c *Client) ListDecidedChanges(limit int) []engine.PendingChange {
	var out0 []engine.PendingChange
	if err := c.call("ListDecidedChanges", []any{limit}, &out0); err != nil {
		c.failed("ListDecidedChanges", err)
	}
	return out0
}

func (c *Client) ListDecidedIssues(limit int) []engine.PendingChange {
	var out0 []engine.PendingChange
	if err := c.call("ListDecidedIssues", []any{limit}, &out0); err != nil {
		c.failed("ListDecidedIssues", err)
	}
	return out0
}

func (c *Client) ListDecidedSkillProposals(limit int) []engine.PendingChange {
	var out0 []engine.PendingChange
	if err := c.call("ListDecidedSkillProposals", []any{limit}, &out0); err != nil {
		c.failed("ListDecidedSkillProposals", err)
	}
	return out0
}

func (c *Client) ListDecks() []engine.Deck {
	var out0 []engine.Deck
	if err := c.call("ListDecks", nil, &out0); err != nil {
		c.failed("ListDecks", err)
	}
	return out0
}

func (c *Client) ListDecksIn(want string) engine.DeckPage {
	var out0 engine.DeckPage
	if err := c.call("ListDecksIn", []any{want}, &out0); err != nil {
		c.failed("ListDecksIn", err)
	}
	return out0
}

func (c *Client) ListDir(path string) (engine.DirListing, error) {
	var out0 engine.DirListing
	err := c.call("ListDir", []any{path}, &out0)
	return out0, err
}

func (c *Client) ListExternalSkills() []skill.DiscoveredSkill {
	var out0 []skill.DiscoveredSkill
	if err := c.call("ListExternalSkills", nil, &out0); err != nil {
		c.failed("ListExternalSkills", err)
	}
	return out0
}

func (c *Client) ListIdentityFiles(head string) ([]engine.IdentityFile, error) {
	var out0 []engine.IdentityFile
	err := c.call("ListIdentityFiles", []any{head}, &out0)
	return out0, err
}

func (c *Client) ListImageEngines() []engine.VoiceEngineInfo {
	var out0 []engine.VoiceEngineInfo
	if err := c.call("ListImageEngines", nil, &out0); err != nil {
		c.failed("ListImageEngines", err)
	}
	return out0
}

func (c *Client) ListMCPServers() []engine.MCPServerInfo {
	var out0 []engine.MCPServerInfo
	if err := c.call("ListMCPServers", nil, &out0); err != nil {
		c.failed("ListMCPServers", err)
	}
	return out0
}

func (c *Client) ListModes() []mode.Mode {
	var out0 []mode.Mode
	if err := c.call("ListModes", nil, &out0); err != nil {
		c.failed("ListModes", err)
	}
	return out0
}

func (c *Client) ListPendingChanges() []engine.PendingChange {
	var out0 []engine.PendingChange
	if err := c.call("ListPendingChanges", nil, &out0); err != nil {
		c.failed("ListPendingChanges", err)
	}
	return out0
}

func (c *Client) ListPromptPresets() []command.Preset {
	var out0 []command.Preset
	if err := c.call("ListPromptPresets", nil, &out0); err != nil {
		c.failed("ListPromptPresets", err)
	}
	return out0
}

func (c *Client) ListReceivedJobs(limit int) []engine.ReceivedJob {
	var out0 []engine.ReceivedJob
	if err := c.call("ListReceivedJobs", []any{limit}, &out0); err != nil {
		c.failed("ListReceivedJobs", err)
	}
	return out0
}

func (c *Client) ListRecurringRequests() []engine.RecurringRequest {
	var out0 []engine.RecurringRequest
	if err := c.call("ListRecurringRequests", nil, &out0); err != nil {
		c.failed("ListRecurringRequests", err)
	}
	return out0
}

func (c *Client) ListSessions() []engine.SessionMeta {
	var out0 []engine.SessionMeta
	if err := c.call("ListSessions", nil, &out0); err != nil {
		c.failed("ListSessions", err)
	}
	return out0
}

func (c *Client) ListSessionsAt(desk string) []engine.SessionMeta {
	var out0 []engine.SessionMeta
	if err := c.call("ListSessionsAt", []any{desk}, &out0); err != nil {
		c.failed("ListSessionsAt", err)
	}
	return out0
}

func (c *Client) ListSessionsForDoor(filter engine.DeskFilter) []engine.SessionMeta {
	var out0 []engine.SessionMeta
	if err := c.call("ListSessionsForDoor", []any{filter}, &out0); err != nil {
		c.failed("ListSessionsForDoor", err)
	}
	return out0
}

func (c *Client) ListSkillProposals() []engine.PendingChange {
	var out0 []engine.PendingChange
	if err := c.call("ListSkillProposals", nil, &out0); err != nil {
		c.failed("ListSkillProposals", err)
	}
	return out0
}

func (c *Client) ListSkills() []engine.SkillInfo {
	var out0 []engine.SkillInfo
	if err := c.call("ListSkills", nil, &out0); err != nil {
		c.failed("ListSkills", err)
	}
	return out0
}

func (c *Client) ListSpeechEngines() []engine.VoiceEngineInfo {
	var out0 []engine.VoiceEngineInfo
	if err := c.call("ListSpeechEngines", nil, &out0); err != nil {
		c.failed("ListSpeechEngines", err)
	}
	return out0
}

func (c *Client) ListSpeechModels() []engine.SpeechModelInfo {
	var out0 []engine.SpeechModelInfo
	if err := c.call("ListSpeechModels", nil, &out0); err != nil {
		c.failed("ListSpeechModels", err)
	}
	return out0
}

func (c *Client) ListSubagentProfiles() []subagent.Profile {
	var out0 []subagent.Profile
	if err := c.call("ListSubagentProfiles", nil, &out0); err != nil {
		c.failed("ListSubagentProfiles", err)
	}
	return out0
}

func (c *Client) ListSystemIssues() []engine.PendingChange {
	var out0 []engine.PendingChange
	if err := c.call("ListSystemIssues", nil, &out0); err != nil {
		c.failed("ListSystemIssues", err)
	}
	return out0
}

func (c *Client) ListTTSEngines() []engine.VoiceEngineInfo {
	var out0 []engine.VoiceEngineInfo
	if err := c.call("ListTTSEngines", nil, &out0); err != nil {
		c.failed("ListTTSEngines", err)
	}
	return out0
}

func (c *Client) ListTaskChips() []engine.TaskChip {
	var out0 []engine.TaskChip
	if err := c.call("ListTaskChips", nil, &out0); err != nil {
		c.failed("ListTaskChips", err)
	}
	return out0
}

func (c *Client) ListTeams(desk string) []engine.TeamCard {
	var out0 []engine.TeamCard
	if err := c.call("ListTeams", []any{desk}, &out0); err != nil {
		c.failed("ListTeams", err)
	}
	return out0
}

func (c *Client) ListTools() []engine.SkillInfo {
	var out0 []engine.SkillInfo
	if err := c.call("ListTools", nil, &out0); err != nil {
		c.failed("ListTools", err)
	}
	return out0
}

func (c *Client) LoadSession(id string) ([]engine.SessionMessage, error) {
	var out0 []engine.SessionMessage
	err := c.call("LoadSession", []any{id}, &out0)
	return out0, err
}

func (c *Client) LoadSessionAnyProject(id string) ([]engine.SessionMessage, error) {
	var out0 []engine.SessionMessage
	err := c.call("LoadSessionAnyProject", []any{id}, &out0)
	return out0, err
}

func (c *Client) MCPConfigPath() string {
	var out0 string
	if err := c.call("MCPConfigPath", nil, &out0); err != nil {
		c.failed("MCPConfigPath", err)
	}
	return out0
}

func (c *Client) MCPFolderPath() (string, error) {
	var out0 string
	err := c.call("MCPFolderPath", nil, &out0)
	return out0, err
}

func (c *Client) MCPSignInStatus(serverName string) oauth.Status {
	var out0 oauth.Status
	if err := c.call("MCPSignInStatus", []any{serverName}, &out0); err != nil {
		c.failed("MCPSignInStatus", err)
	}
	return out0
}

func (c *Client) MachineInfo() machine.Info {
	var out0 machine.Info
	if err := c.call("MachineInfo", nil, &out0); err != nil {
		c.failed("MachineInfo", err)
	}
	return out0
}

func (c *Client) MarkIssueReported(id int64) error {
	return c.call("MarkIssueReported", []any{id}, nil)
}

func (c *Client) MarkVideoCheckSeen() {
	if err := c.call("MarkVideoCheckSeen", nil, nil); err != nil {
		c.failed("MarkVideoCheckSeen", err)
	}
}

func (c *Client) MeasureContextFloor() (engine.ContextBreakdown, error) {
	var out0 engine.ContextBreakdown
	err := c.call("MeasureContextFloor", nil, &out0)
	return out0, err
}

func (c *Client) MemoryFolderPath() (string, error) {
	var out0 string
	err := c.call("MemoryFolderPath", nil, &out0)
	return out0, err
}

func (c *Client) MemoryScopeInfo(scope string) engine.MemoryScopeInfo {
	var out0 engine.MemoryScopeInfo
	if err := c.call("MemoryScopeInfo", []any{scope}, &out0); err != nil {
		c.failed("MemoryScopeInfo", err)
	}
	return out0
}

func (c *Client) MobileRemoteQR() string {
	var out0 string
	if err := c.call("MobileRemoteQR", nil, &out0); err != nil {
		c.failed("MobileRemoteQR", err)
	}
	return out0
}

func (c *Client) MobileRemoteStatus() engine.RemoteStatus {
	var out0 engine.RemoteStatus
	if err := c.call("MobileRemoteStatus", nil, &out0); err != nil {
		c.failed("MobileRemoteStatus", err)
	}
	return out0
}

func (c *Client) ModelPriceSource() engine.PriceSource {
	var out0 engine.PriceSource
	if err := c.call("ModelPriceSource", nil, &out0); err != nil {
		c.failed("ModelPriceSource", err)
	}
	return out0
}

func (c *Client) ModelStatus() string {
	var out0 string
	if err := c.call("ModelStatus", nil, &out0); err != nil {
		c.failed("ModelStatus", err)
	}
	return out0
}

func (c *Client) MoveLearnedEntry(fromScope string, toScope string, index int) error {
	return c.call("MoveLearnedEntry", []any{fromScope, toScope, index}, nil)
}

func (c *Client) NewChairSession(chair string) (string, error) {
	var out0 string
	err := c.call("NewChairSession", []any{chair}, &out0)
	return out0, err
}

func (c *Client) NewChairSessionAt(desk string, chair string, team string) (string, error) {
	var out0 string
	err := c.call("NewChairSessionAt", []any{desk, chair, team}, &out0)
	return out0, err
}

func (c *Client) NewSession() (string, error) {
	var out0 string
	err := c.call("NewSession", nil, &out0)
	return out0, err
}

func (c *Client) NewSessionAt(desk string) (string, error) {
	var out0 string
	err := c.call("NewSessionAt", []any{desk}, &out0)
	return out0, err
}

func (c *Client) NewSessionInSpace(name string) (string, error) {
	var out0 string
	err := c.call("NewSessionInSpace", []any{name}, &out0)
	return out0, err
}

func (c *Client) NewTeamSession(desk string, team string) (string, error) {
	var out0 string
	err := c.call("NewTeamSession", []any{desk, team}, &out0)
	return out0, err
}

func (c *Client) NoteProviderQuotas(providerName string, quotas []model.Quota) {
	if err := c.call("NoteProviderQuotas", []any{providerName, quotas}, nil); err != nil {
		c.failed("NoteProviderQuotas", err)
	}
}

func (c *Client) OpenProjectPath(root string) (engine.ProjectStatus, error) {
	var out0 engine.ProjectStatus
	err := c.call("OpenProjectPath", []any{root}, &out0)
	return out0, err
}

func (c *Client) PageMarksOn() bool {
	var out0 bool
	if err := c.call("PageMarksOn", nil, &out0); err != nil {
		c.failed("PageMarksOn", err)
	}
	return out0
}

func (c *Client) PairedDevices() []engine.RemoteDevice {
	var out0 []engine.RemoteDevice
	if err := c.call("PairedDevices", nil, &out0); err != nil {
		c.failed("PairedDevices", err)
	}
	return out0
}

func (c *Client) PausePlanRun(sessionID string) {
	if err := c.call("PausePlanRun", []any{sessionID}, nil); err != nil {
		c.failed("PausePlanRun", err)
	}
}

func (c *Client) PendingChangeByID(id int64) engine.PendingChange {
	var out0 engine.PendingChange
	if err := c.call("PendingChangeByID", []any{id}, &out0); err != nil {
		c.failed("PendingChangeByID", err)
	}
	return out0
}

func (c *Client) PendingIssueCount() int {
	var out0 int
	if err := c.call("PendingIssueCount", nil, &out0); err != nil {
		c.failed("PendingIssueCount", err)
	}
	return out0
}

func (c *Client) PendingLearnedCount() int {
	var out0 int
	if err := c.call("PendingLearnedCount", nil, &out0); err != nil {
		c.failed("PendingLearnedCount", err)
	}
	return out0
}

func (c *Client) PendingRestore(id string) []string {
	var out0 []string
	if err := c.call("PendingRestore", []any{id}, &out0); err != nil {
		c.failed("PendingRestore", err)
	}
	return out0
}

func (c *Client) PendingSkillTuneCount() int {
	var out0 int
	if err := c.call("PendingSkillTuneCount", nil, &out0); err != nil {
		c.failed("PendingSkillTuneCount", err)
	}
	return out0
}

func (c *Client) PendingUndo() []string {
	var out0 []string
	if err := c.call("PendingUndo", nil, &out0); err != nil {
		c.failed("PendingUndo", err)
	}
	return out0
}

func (c *Client) PictureBytes(relPath string) (engine.ExportFile, error) {
	var out0 engine.ExportFile
	err := c.call("PictureBytes", []any{relPath}, &out0)
	return out0, err
}

func (c *Client) PlacementTargets() []engine.PlacementTarget {
	var out0 []engine.PlacementTarget
	if err := c.call("PlacementTargets", nil, &out0); err != nil {
		c.failed("PlacementTargets", err)
	}
	return out0
}

func (c *Client) PlanRunning(sessionID string) bool {
	var out0 bool
	if err := c.call("PlanRunning", []any{sessionID}, &out0); err != nil {
		c.failed("PlanRunning", err)
	}
	return out0
}

func (c *Client) PrepareToClose() {
	if err := c.call("PrepareToClose", nil, nil); err != nil {
		c.failed("PrepareToClose", err)
	}
}

func (c *Client) PreparedReplyOn() bool {
	var out0 bool
	if err := c.call("PreparedReplyOn", nil, &out0); err != nil {
		c.failed("PreparedReplyOn", err)
	}
	return out0
}

func (c *Client) PriceModels(providerName string, models []string) []engine.ModelListing {
	var out0 []engine.ModelListing
	if err := c.call("PriceModels", []any{providerName, models}, &out0); err != nil {
		c.failed("PriceModels", err)
	}
	return out0
}

func (c *Client) ProjectFilePath(relPath string) (string, error) {
	var out0 string
	err := c.call("ProjectFilePath", []any{relPath}, &out0)
	return out0, err
}

func (c *Client) ProjectTree() []engine.TreeNode {
	var out0 []engine.TreeNode
	if err := c.call("ProjectTree", nil, &out0); err != nil {
		c.failed("ProjectTree", err)
	}
	return out0
}

func (c *Client) PromptsFolderPath() (string, error) {
	var out0 string
	err := c.call("PromptsFolderPath", nil, &out0)
	return out0, err
}

func (c *Client) ProviderAPIKeyURL(providerName string) string {
	var out0 string
	if err := c.call("ProviderAPIKeyURL", []any{providerName}, &out0); err != nil {
		c.failed("ProviderAPIKeyURL", err)
	}
	return out0
}

func (c *Client) ProviderBaseURL(providerName string) string {
	var out0 string
	if err := c.call("ProviderBaseURL", []any{providerName}, &out0); err != nil {
		c.failed("ProviderBaseURL", err)
	}
	return out0
}

func (c *Client) ProviderBaseURLIsCustom(providerName string) bool {
	var out0 bool
	if err := c.call("ProviderBaseURLIsCustom", []any{providerName}, &out0); err != nil {
		c.failed("ProviderBaseURLIsCustom", err)
	}
	return out0
}

func (c *Client) ProviderCredentialChanged(providerName string) (engine.ModelInfo, error) {
	var out0 engine.ModelInfo
	err := c.call("ProviderCredentialChanged", []any{providerName}, &out0)
	return out0, err
}

func (c *Client) ProviderQuotas(providerName string) ([]model.Quota, bool) {
	var out0 []model.Quota
	var out1 bool
	if err := c.callN("ProviderQuotas", []any{providerName}, &out0, &out1); err != nil {
		c.failed("ProviderQuotas", err)
	}
	return out0, out1
}

func (c *Client) ProviderWireFormats(providerName string) []string {
	var out0 []string
	if err := c.call("ProviderWireFormats", []any{providerName}, &out0); err != nil {
		c.failed("ProviderWireFormats", err)
	}
	return out0
}

func (c *Client) PullRequestChecks(sha string) []gh.CheckRun {
	var out0 []gh.CheckRun
	if err := c.call("PullRequestChecks", []any{sha}, &out0); err != nil {
		c.failed("PullRequestChecks", err)
	}
	return out0
}

func (c *Client) PullRequestFiles(number int) []gh.PRFile {
	var out0 []gh.PRFile
	if err := c.call("PullRequestFiles", []any{number}, &out0); err != nil {
		c.failed("PullRequestFiles", err)
	}
	return out0
}

func (c *Client) PullRequests() engine.PRRoom {
	var out0 engine.PRRoom
	if err := c.call("PullRequests", nil, &out0); err != nil {
		c.failed("PullRequests", err)
	}
	return out0
}

func (c *Client) PullRequestsState(state string) engine.PRRoom {
	var out0 engine.PRRoom
	if err := c.call("PullRequestsState", []any{state}, &out0); err != nil {
		c.failed("PullRequestsState", err)
	}
	return out0
}

func (c *Client) RateTurn(messageID int64, verdict string) {
	if err := c.call("RateTurn", []any{messageID, verdict}, nil); err != nil {
		c.failed("RateTurn", err)
	}
}

func (c *Client) ReadDeskFile(name string) (engine.DeskFile, error) {
	var out0 engine.DeskFile
	err := c.call("ReadDeskFile", []any{name}, &out0)
	return out0, err
}

func (c *Client) ReadFile(relPath string) (string, error) {
	var out0 string
	err := c.call("ReadFile", []any{relPath}, &out0)
	return out0, err
}

func (c *Client) ReadIdentityFile(head string, name string) (string, error) {
	var out0 string
	err := c.call("ReadIdentityFile", []any{head, name}, &out0)
	return out0, err
}

func (c *Client) ReadImageDataURL(relPath string) (string, error) {
	var out0 string
	err := c.call("ReadImageDataURL", []any{relPath}, &out0)
	return out0, err
}

func (c *Client) ReadSubagentProfile(name string) (string, error) {
	var out0 string
	err := c.call("ReadSubagentProfile", []any{name}, &out0)
	return out0, err
}

func (c *Client) ReadWorkbook(relPath string) (*ooxml.WorkbookPreview, error) {
	var out0 *ooxml.WorkbookPreview
	err := c.call("ReadWorkbook", []any{relPath}, &out0)
	return out0, err
}

func (c *Client) ReadyToRestart() error {
	return c.call("ReadyToRestart", nil, nil)
}

func (c *Client) RecentAgentPages(limit int) []engine.AgentPage {
	var out0 []engine.AgentPage
	if err := c.call("RecentAgentPages", []any{limit}, &out0); err != nil {
		c.failed("RecentAgentPages", err)
	}
	return out0
}

func (c *Client) RecentDebugLog() []string {
	var out0 []string
	if err := c.call("RecentDebugLog", nil, &out0); err != nil {
		c.failed("RecentDebugLog", err)
	}
	return out0
}

func (c *Client) RecentProjects() []engine.ProjectMeta {
	var out0 []engine.ProjectMeta
	if err := c.call("RecentProjects", nil, &out0); err != nil {
		c.failed("RecentProjects", err)
	}
	return out0
}

func (c *Client) RefreshModelFacts() {
	if err := c.call("RefreshModelFacts", nil, nil); err != nil {
		c.failed("RefreshModelFacts", err)
	}
}

func (c *Client) RefreshSkills() {
	if err := c.call("RefreshSkills", nil, nil); err != nil {
		c.failed("RefreshSkills", err)
	}
}

func (c *Client) RegenerateReply(revertFiles bool) (engine.RegenerateResult, error) {
	var out0 engine.RegenerateResult
	err := c.call("RegenerateReply", []any{revertFiles}, &out0)
	return out0, err
}

func (c *Client) RejectPendingChange(id int64) error {
	return c.call("RejectPendingChange", []any{id}, nil)
}

func (c *Client) RelativizePath(absPath string) (string, error) {
	var out0 string
	err := c.call("RelativizePath", []any{absPath}, &out0)
	return out0, err
}

func (c *Client) RememberTTSVoice(id string) {
	if err := c.call("RememberTTSVoice", []any{id}, nil); err != nil {
		c.failed("RememberTTSVoice", err)
	}
}

func (c *Client) RemoveAgentSkill(agent string, name string) error {
	return c.call("RemoveAgentSkill", []any{agent, name}, nil)
}

func (c *Client) RemoveCustomProviderRow(id string) ([]string, error) {
	var out0 []string
	err := c.call("RemoveCustomProviderRow", []any{id}, &out0)
	return out0, err
}

func (c *Client) RemoveExternalSkill(name string) error {
	return c.call("RemoveExternalSkill", []any{name}, nil)
}

func (c *Client) RemoveMCPServer(name string) error {
	return c.call("RemoveMCPServer", []any{name}, nil)
}

func (c *Client) RemovePresetImage(name string) error {
	return c.call("RemovePresetImage", []any{name}, nil)
}

func (c *Client) RemoveSpaceContext(name string, file string) ([]string, error) {
	var out0 []string
	err := c.call("RemoveSpaceContext", []any{name, file}, &out0)
	return out0, err
}

func (c *Client) RemoveStudioLibrary(id string) ([]engine.StudioLibraryView, error) {
	var out0 []engine.StudioLibraryView
	err := c.call("RemoveStudioLibrary", []any{id}, &out0)
	return out0, err
}

func (c *Client) RemoveWorkspaceFolder(path string) ([]engine.WorkspaceFolder, error) {
	var out0 []engine.WorkspaceFolder
	err := c.call("RemoveWorkspaceFolder", []any{path}, &out0)
	return out0, err
}

func (c *Client) RequiresAPIKey(providerName string) bool {
	var out0 bool
	if err := c.call("RequiresAPIKey", []any{providerName}, &out0); err != nil {
		c.failed("RequiresAPIKey", err)
	}
	return out0
}

func (c *Client) RescanStudioLibrary(id string) (bool, error) {
	var out0 bool
	err := c.call("RescanStudioLibrary", []any{id}, &out0)
	return out0, err
}

func (c *Client) ResendEdited(text string, revertFiles bool) (engine.TurnReply, error) {
	var out0 engine.TurnReply
	err := c.call("ResendEdited", []any{text, revertFiles}, &out0)
	return out0, err
}

func (c *Client) ResetDeskFile(name string) error {
	return c.call("ResetDeskFile", []any{name}, nil)
}

func (c *Client) ResolveAddress(input string) engine.Address {
	var out0 engine.Address
	if err := c.call("ResolveAddress", []any{input}, &out0); err != nil {
		c.failed("ResolveAddress", err)
	}
	return out0
}

func (c *Client) ResolveWorkbenchURL(input string) (string, string) {
	var out0 string
	var out1 string
	if err := c.callN("ResolveWorkbenchURL", []any{input}, &out0, &out1); err != nil {
		c.failed("ResolveWorkbenchURL", err)
	}
	return out0, out1
}

func (c *Client) RestorePoints() []engine.RestorePoint {
	var out0 []engine.RestorePoint
	if err := c.call("RestorePoints", nil, &out0); err != nil {
		c.failed("RestorePoints", err)
	}
	return out0
}

func (c *Client) RestoreRecurringRequest(normalized string) error {
	return c.call("RestoreRecurringRequest", []any{normalized}, nil)
}

func (c *Client) ResumePlanRun(sessionID string) {
	if err := c.call("ResumePlanRun", []any{sessionID}, nil); err != nil {
		c.failed("ResumePlanRun", err)
	}
}

func (c *Client) RetryActiveProvider() engine.ModelInfo {
	var out0 engine.ModelInfo
	if err := c.call("RetryActiveProvider", nil, &out0); err != nil {
		c.failed("RetryActiveProvider", err)
	}
	return out0
}

func (c *Client) RetryFailedTurn(text string) (engine.TurnReply, error) {
	var out0 engine.TurnReply
	err := c.call("RetryFailedTurn", []any{text}, &out0)
	return out0, err
}

func (c *Client) ReviewPullRequest(number int) (string, error) {
	var out0 string
	err := c.call("ReviewPullRequest", []any{number}, &out0)
	return out0, err
}

func (c *Client) RevokeDevice(id string) error {
	return c.call("RevokeDevice", []any{id}, nil)
}

func (c *Client) RewindTo(id string) (engine.UndoResult, error) {
	var out0 engine.UndoResult
	err := c.call("RewindTo", []any{id}, &out0)
	return out0, err
}

func (c *Client) RunChatCommand(command string) (engine.RunBlockResult, error) {
	var out0 engine.RunBlockResult
	err := c.call("RunChatCommand", []any{command}, &out0)
	return out0, err
}

func (c *Client) RunChatScript(lang string, source string) (engine.RunBlockResult, error) {
	var out0 engine.RunBlockResult
	err := c.call("RunChatScript", []any{lang, source}, &out0)
	return out0, err
}

func (c *Client) RunSessionReview(sessionID string) (int, error) {
	var out0 int
	err := c.call("RunSessionReview", []any{sessionID}, &out0)
	return out0, err
}

func (c *Client) RunSkillTuneup() (int, error) {
	var out0 int
	err := c.call("RunSkillTuneup", nil, &out0)
	return out0, err
}

func (c *Client) RunnableLanguages() map[string]string {
	var out0 map[string]string
	if err := c.call("RunnableLanguages", nil, &out0); err != nil {
		c.failed("RunnableLanguages", err)
	}
	return out0
}

func (c *Client) SandboxFile(request string) (string, error) {
	var out0 string
	err := c.call("SandboxFile", []any{request}, &out0)
	return out0, err
}

func (c *Client) SaveAgentProfile(name string, body string) error {
	return c.call("SaveAgentProfile", []any{name, body}, nil)
}

func (c *Client) SaveBrowserShot(png []byte, marked bool) (string, error) {
	var out0 string
	err := c.call("SaveBrowserShot", []any{png, marked}, &out0)
	return out0, err
}

func (c *Client) SaveChairStarters(name string, locale string, set subagent.StarterSet) error {
	return c.call("SaveChairStarters", []any{name, locale, set}, nil)
}

func (c *Client) SaveChatFile(sourcePath string) (string, error) {
	var out0 string
	err := c.call("SaveChatFile", []any{sourcePath}, &out0)
	return out0, err
}

func (c *Client) SaveChatImage(sourcePath string) (string, error) {
	var out0 string
	err := c.call("SaveChatImage", []any{sourcePath}, &out0)
	return out0, err
}

func (c *Client) SaveChatImageData(dataURL string) (string, error) {
	var out0 string
	err := c.call("SaveChatImageData", []any{dataURL}, &out0)
	return out0, err
}

func (c *Client) SaveDeskFile(name string, text string) error {
	return c.call("SaveDeskFile", []any{name, text}, nil)
}

func (c *Client) SaveDeskStarters(desk string, locale string, set subagent.StarterSet) error {
	return c.call("SaveDeskStarters", []any{desk, locale, set}, nil)
}

func (c *Client) SaveIdentityFile(head string, name string, content string) error {
	return c.call("SaveIdentityFile", []any{head, name, content}, nil)
}

func (c *Client) SaveLearnedEntry(scope string, index int, text string) error {
	return c.call("SaveLearnedEntry", []any{scope, index, text}, nil)
}

func (c *Client) SaveMCPServer(originalName string, server config.MCPServerConfig) error {
	return c.call("SaveMCPServer", []any{originalName, server}, nil)
}

func (c *Client) SavePlanText(sessionID string, text string) string {
	var out0 string
	if err := c.call("SavePlanText", []any{sessionID, text}, &out0); err != nil {
		c.failed("SavePlanText", err)
	}
	return out0
}

func (c *Client) SavePromptPreset(name string, body string) error {
	return c.call("SavePromptPreset", []any{name, body}, nil)
}

func (c *Client) SaveSubagentProfile(name string, body string) error {
	return c.call("SaveSubagentProfile", []any{name, body}, nil)
}

func (c *Client) SaveTeam(name string, desk string, description string, members []string) error {
	return c.call("SaveTeam", []any{name, desk, description, members}, nil)
}

func (c *Client) SearchAllSessions(query string) []engine.SessionMeta {
	var out0 []engine.SessionMeta
	if err := c.call("SearchAllSessions", []any{query}, &out0); err != nil {
		c.failed("SearchAllSessions", err)
	}
	return out0
}

func (c *Client) SearchSessions(query string) []engine.SessionMeta {
	var out0 []engine.SessionMeta
	if err := c.call("SearchSessions", []any{query}, &out0); err != nil {
		c.failed("SearchSessions", err)
	}
	return out0
}

func (c *Client) SearchSessionsForDoor(query string, filter engine.DeskFilter) []engine.SessionMeta {
	var out0 []engine.SessionMeta
	if err := c.call("SearchSessionsForDoor", []any{query, filter}, &out0); err != nil {
		c.failed("SearchSessionsForDoor", err)
	}
	return out0
}

func (c *Client) SendMessage(text string, to string) (engine.TurnReply, error) {
	var out0 engine.TurnReply
	err := c.call("SendMessage", []any{text, to}, &out0)
	return out0, err
}

func (c *Client) SessionAgent(id string) string {
	var out0 string
	if err := c.call("SessionAgent", []any{id}, &out0); err != nil {
		c.failed("SessionAgent", err)
	}
	return out0
}

func (c *Client) SessionEdits(sessionID string) engine.EditPage {
	var out0 engine.EditPage
	if err := c.call("SessionEdits", []any{sessionID}, &out0); err != nil {
		c.failed("SessionEdits", err)
	}
	return out0
}

func (c *Client) SessionExportBytes(id string, format string) (engine.ExportFile, error) {
	var out0 engine.ExportFile
	err := c.call("SessionExportBytes", []any{id, format}, &out0)
	return out0, err
}

func (c *Client) SessionMode(id string) string {
	var out0 string
	if err := c.call("SessionMode", []any{id}, &out0); err != nil {
		c.failed("SessionMode", err)
	}
	return out0
}

func (c *Client) SessionPlan(sessionID string) engine.Plan {
	var out0 engine.Plan
	if err := c.call("SessionPlan", []any{sessionID}, &out0); err != nil {
		c.failed("SessionPlan", err)
	}
	return out0
}

func (c *Client) SessionPlanReports(sessionID string) []engine.PlanReport {
	var out0 []engine.PlanReport
	if err := c.call("SessionPlanReports", []any{sessionID}, &out0); err != nil {
		c.failed("SessionPlanReports", err)
	}
	return out0
}

func (c *Client) SessionReviewAuto() bool {
	var out0 bool
	if err := c.call("SessionReviewAuto", nil, &out0); err != nil {
		c.failed("SessionReviewAuto", err)
	}
	return out0
}

func (c *Client) SessionSourceCount(sessionID string) int {
	var out0 int
	if err := c.call("SessionSourceCount", []any{sessionID}, &out0); err != nil {
		c.failed("SessionSourceCount", err)
	}
	return out0
}

func (c *Client) SessionSources(sessionID string) []engine.Source {
	var out0 []engine.Source
	if err := c.call("SessionSources", []any{sessionID}, &out0); err != nil {
		c.failed("SessionSources", err)
	}
	return out0
}

func (c *Client) SessionSpend(id string) engine.SessionSpend {
	var out0 engine.SessionSpend
	if err := c.call("SessionSpend", []any{id}, &out0); err != nil {
		c.failed("SessionSpend", err)
	}
	return out0
}

func (c *Client) SessionTeam(id string) string {
	var out0 string
	if err := c.call("SessionTeam", []any{id}, &out0); err != nil {
		c.failed("SessionTeam", err)
	}
	return out0
}

func (c *Client) SessionTranscript(id string) ([]engine.SessionMessage, error) {
	var out0 []engine.SessionMessage
	err := c.call("SessionTranscript", []any{id}, &out0)
	return out0, err
}

func (c *Client) SessionsInSpace(name string) []engine.SessionMeta {
	var out0 []engine.SessionMeta
	if err := c.call("SessionsInSpace", []any{name}, &out0); err != nil {
		c.failed("SessionsInSpace", err)
	}
	return out0
}

func (c *Client) SetAgentOff(team string, name string, off bool) engine.DelegateSettings {
	var out0 engine.DelegateSettings
	if err := c.call("SetAgentOff", []any{team, name, off}, &out0); err != nil {
		c.failed("SetAgentOff", err)
	}
	return out0
}

func (c *Client) SetBusyLayer(id string, on bool) []engine.BusyLayer {
	var out0 []engine.BusyLayer
	if err := c.call("SetBusyLayer", []any{id, on}, &out0); err != nil {
		c.failed("SetBusyLayer", err)
	}
	return out0
}

func (c *Client) SetCodeProjectsDir(dir string) error {
	return c.call("SetCodeProjectsDir", []any{dir}, nil)
}

func (c *Client) SetConnectionStartCommand(id string, command string) error {
	return c.call("SetConnectionStartCommand", []any{id, command}, nil)
}

func (c *Client) SetConnectionTargets(id string, targets []string) error {
	return c.call("SetConnectionTargets", []any{id, targets}, nil)
}

func (c *Client) SetDelegateOff(kind string, off bool) engine.DelegateSettings {
	var out0 engine.DelegateSettings
	if err := c.call("SetDelegateOff", []any{kind, off}, &out0); err != nil {
		c.failed("SetDelegateOff", err)
	}
	return out0
}

func (c *Client) SetHeadName(head string, name string) error {
	return c.call("SetHeadName", []any{head, name}, nil)
}

func (c *Client) SetImageEngine(id string) error {
	return c.call("SetImageEngine", []any{id}, nil)
}

func (c *Client) SetImageModelName(name string) error {
	return c.call("SetImageModelName", []any{name}, nil)
}

func (c *Client) SetLearningEnabled(on bool) error {
	return c.call("SetLearningEnabled", []any{on}, nil)
}

func (c *Client) SetMCPServerTargets(name string, targets []string) error {
	return c.call("SetMCPServerTargets", []any{name, targets}, nil)
}

func (c *Client) SetPlanStepStop(sessionID string, n int, on bool) {
	if err := c.call("SetPlanStepStop", []any{sessionID, n, on}, nil); err != nil {
		c.failed("SetPlanStepStop", err)
	}
}

func (c *Client) SetPreparedReplyOn(on bool) error {
	return c.call("SetPreparedReplyOn", []any{on}, nil)
}

func (c *Client) SetPresetImageFrom(name string, path string) (string, error) {
	var out0 string
	err := c.call("SetPresetImageFrom", []any{name, path}, &out0)
	return out0, err
}

func (c *Client) SetProviderBaseURL(providerName string, baseURL string) (engine.ModelInfo, error) {
	var out0 engine.ModelInfo
	err := c.call("SetProviderBaseURL", []any{providerName, baseURL}, &out0)
	return out0, err
}

func (c *Client) SetProviderEnabled(providerName string, enabled bool) ([]string, error) {
	var out0 []string
	err := c.call("SetProviderEnabled", []any{providerName, enabled}, &out0)
	return out0, err
}

func (c *Client) SetProviderWireFormat(format string) (engine.ModelInfo, error) {
	var out0 engine.ModelInfo
	err := c.call("SetProviderWireFormat", []any{format}, &out0)
	return out0, err
}

func (c *Client) SetSessionReviewAuto(on bool) error {
	return c.call("SetSessionReviewAuto", []any{on}, nil)
}

func (c *Client) SetShell(setting string) error {
	return c.call("SetShell", []any{setting}, nil)
}

func (c *Client) SetSkillTuneAuto(on bool) error {
	return c.call("SetSkillTuneAuto", []any{on}, nil)
}

func (c *Client) SetSpeechEngine(id string) error {
	return c.call("SetSpeechEngine", []any{id}, nil)
}

func (c *Client) SetSpeechModel(path string) error {
	return c.call("SetSpeechModel", []any{path}, nil)
}

func (c *Client) SetSpeechModelName(name string) error {
	return c.call("SetSpeechModelName", []any{name}, nil)
}

func (c *Client) SetStance(name string) (string, error) {
	var out0 string
	err := c.call("SetStance", []any{name}, &out0)
	return out0, err
}

func (c *Client) SetSubagentModel(name string, modelName string) error {
	return c.call("SetSubagentModel", []any{name, modelName}, nil)
}

func (c *Client) SetTTSEngine(id string) error {
	return c.call("SetTTSEngine", []any{id}, nil)
}

func (c *Client) SetTTSModelName(name string) error {
	return c.call("SetTTSModelName", []any{name}, nil)
}

func (c *Client) SetUILocale(locale string) error {
	return c.call("SetUILocale", []any{locale}, nil)
}

func (c *Client) SetUserName(name string) error {
	return c.call("SetUserName", []any{name}, nil)
}

func (c *Client) Shells() []engine.ShellOption {
	var out0 []engine.ShellOption
	if err := c.call("Shells", nil, &out0); err != nil {
		c.failed("Shells", err)
	}
	return out0
}

func (c *Client) SkillScanIssues() []string {
	var out0 []string
	if err := c.call("SkillScanIssues", nil, &out0); err != nil {
		c.failed("SkillScanIssues", err)
	}
	return out0
}

func (c *Client) SkillTuneAuto() bool {
	var out0 bool
	if err := c.call("SkillTuneAuto", nil, &out0); err != nil {
		c.failed("SkillTuneAuto", err)
	}
	return out0
}

func (c *Client) SkillsDir() string {
	var out0 string
	if err := c.call("SkillsDir", nil, &out0); err != nil {
		c.failed("SkillsDir", err)
	}
	return out0
}

func (c *Client) SkillsFolderPath() (string, error) {
	var out0 string
	err := c.call("SkillsFolderPath", nil, &out0)
	return out0, err
}

func (c *Client) SpaceFolderPath(name string) (string, error) {
	var out0 string
	err := c.call("SpaceFolderPath", []any{name}, &out0)
	return out0, err
}

func (c *Client) Spaces() []engine.Space {
	var out0 []engine.Space
	if err := c.call("Spaces", nil, &out0); err != nil {
		c.failed("Spaces", err)
	}
	return out0
}

func (c *Client) SpeechModelDirPath(dir string) (string, error) {
	var out0 string
	err := c.call("SpeechModelDirPath", []any{dir}, &out0)
	return out0, err
}

func (c *Client) SpeechModelDirs() []engine.SpeechDirInfo {
	var out0 []engine.SpeechDirInfo
	if err := c.call("SpeechModelDirs", nil, &out0); err != nil {
		c.failed("SpeechModelDirs", err)
	}
	return out0
}

func (c *Client) SpeechModelFolderPath(path string) (string, error) {
	var out0 string
	err := c.call("SpeechModelFolderPath", []any{path}, &out0)
	return out0, err
}

func (c *Client) SpeechStatus() string {
	var out0 string
	if err := c.call("SpeechStatus", nil, &out0); err != nil {
		c.failed("SpeechStatus", err)
	}
	return out0
}

func (c *Client) Stance() string {
	var out0 string
	if err := c.call("Stance", nil, &out0); err != nil {
		c.failed("Stance", err)
	}
	return out0
}

func (c *Client) Stances() []string {
	var out0 []string
	if err := c.call("Stances", nil, &out0); err != nil {
		c.failed("Stances", err)
	}
	return out0
}

func (c *Client) StartConnectionServer(id string) error {
	return c.call("StartConnectionServer", []any{id}, nil)
}

func (c *Client) StartMCPSignIn(serverName string, resourceURL string) (engine.SignInPrompt, error) {
	var out0 engine.SignInPrompt
	err := c.call("StartMCPSignIn", []any{serverName, resourceURL}, &out0)
	return out0, err
}

func (c *Client) StartMobileRemote() engine.RemoteStatus {
	var out0 engine.RemoteStatus
	if err := c.call("StartMobileRemote", nil, &out0); err != nil {
		c.failed("StartMobileRemote", err)
	}
	return out0
}

func (c *Client) StartPlanRun(sessionID string) engine.PlanRunStart {
	var out0 engine.PlanRunStart
	if err := c.call("StartPlanRun", []any{sessionID}, &out0); err != nil {
		c.failed("StartPlanRun", err)
	}
	return out0
}

func (c *Client) StopBackgroundRun(runID string) int {
	var out0 int
	if err := c.call("StopBackgroundRun", []any{runID}, &out0); err != nil {
		c.failed("StopBackgroundRun", err)
	}
	return out0
}

func (c *Client) StopBackgroundTask(id string) bool {
	var out0 bool
	if err := c.call("StopBackgroundTask", []any{id}, &out0); err != nil {
		c.failed("StopBackgroundTask", err)
	}
	return out0
}

func (c *Client) StopBrowsing() {
	if err := c.call("StopBrowsing", nil, nil); err != nil {
		c.failed("StopBrowsing", err)
	}
}

func (c *Client) StopMobileRemote() engine.RemoteStatus {
	var out0 engine.RemoteStatus
	if err := c.call("StopMobileRemote", nil, &out0); err != nil {
		c.failed("StopMobileRemote", err)
	}
	return out0
}

func (c *Client) StopPlanRun(sessionID string) {
	if err := c.call("StopPlanRun", []any{sessionID}, nil); err != nil {
		c.failed("StopPlanRun", err)
	}
}

func (c *Client) StopQueuedTasks() int {
	var out0 int
	if err := c.call("StopQueuedTasks", nil, &out0); err != nil {
		c.failed("StopQueuedTasks", err)
	}
	return out0
}

func (c *Client) StudioAssetPath(id string) (string, error) {
	var out0 string
	err := c.call("StudioAssetPath", []any{id}, &out0)
	return out0, err
}

func (c *Client) StudioAssets(q engine.StudioAssetQuery) engine.StudioAssetPage {
	var out0 engine.StudioAssetPage
	if err := c.call("StudioAssets", []any{q}, &out0); err != nil {
		c.failed("StudioAssets", err)
	}
	return out0
}

func (c *Client) StudioLibraries() []engine.StudioLibraryView {
	var out0 []engine.StudioLibraryView
	if err := c.call("StudioLibraries", nil, &out0); err != nil {
		c.failed("StudioLibraries", err)
	}
	return out0
}

func (c *Client) StudioLibraryPath(id string) (string, error) {
	var out0 string
	err := c.call("StudioLibraryPath", []any{id}, &out0)
	return out0, err
}

func (c *Client) StudioScanning() bool {
	var out0 bool
	if err := c.call("StudioScanning", nil, &out0); err != nil {
		c.failed("StudioScanning", err)
	}
	return out0
}

func (c *Client) StudioSetHidden(id string, hidden bool) error {
	return c.call("StudioSetHidden", []any{id, hidden}, nil)
}

func (c *Client) StudioSetKind(id string, kind string) error {
	return c.call("StudioSetKind", []any{id, kind}, nil)
}

func (c *Client) StudioThumbs(ids []string) map[string]string {
	var out0 map[string]string
	if err := c.call("StudioThumbs", []any{ids}, &out0); err != nil {
		c.failed("StudioThumbs", err)
	}
	return out0
}

func (c *Client) SubagentsFolderPath() (string, error) {
	var out0 string
	err := c.call("SubagentsFolderPath", nil, &out0)
	return out0, err
}

func (c *Client) SuggestPRDetails(head string, base string) (engine.PRSuggestion, error) {
	var out0 engine.PRSuggestion
	err := c.call("SuggestPRDetails", []any{head, base}, &out0)
	return out0, err
}

func (c *Client) SupportedProviders() []string {
	var out0 []string
	if err := c.call("SupportedProviders", nil, &out0); err != nil {
		c.failed("SupportedProviders", err)
	}
	return out0
}

func (c *Client) SupportedThinkLevels() []string {
	var out0 []string
	if err := c.call("SupportedThinkLevels", nil, &out0); err != nil {
		c.failed("SupportedThinkLevels", err)
	}
	return out0
}

func (c *Client) SupportedThinkLevelsFor(provider string, modelName string) []string {
	var out0 []string
	if err := c.call("SupportedThinkLevelsFor", []any{provider, modelName}, &out0); err != nil {
		c.failed("SupportedThinkLevelsFor", err)
	}
	return out0
}

func (c *Client) SwitchApprovalMode(mode string) (engine.ModelInfo, error) {
	var out0 engine.ModelInfo
	err := c.call("SwitchApprovalMode", []any{mode}, &out0)
	return out0, err
}

func (c *Client) SwitchModel(modelName string) (engine.ModelInfo, error) {
	var out0 engine.ModelInfo
	err := c.call("SwitchModel", []any{modelName}, &out0)
	return out0, err
}

func (c *Client) SwitchProvider(provider string) (engine.ModelInfo, error) {
	var out0 engine.ModelInfo
	err := c.call("SwitchProvider", []any{provider}, &out0)
	return out0, err
}

func (c *Client) SwitchThinkLevel(level string) (engine.ModelInfo, error) {
	var out0 engine.ModelInfo
	err := c.call("SwitchThinkLevel", []any{level}, &out0)
	return out0, err
}

func (c *Client) SwitchVariant(index int) (engine.RegenerateResult, error) {
	var out0 engine.RegenerateResult
	err := c.call("SwitchVariant", []any{index}, &out0)
	return out0, err
}

func (c *Client) SynthesizeHabit(sessionID string, hint string) (int64, error) {
	var out0 int64
	err := c.call("SynthesizeHabit", []any{sessionID, hint}, &out0)
	return out0, err
}

func (c *Client) TeamsFolderPath() (string, error) {
	var out0 string
	err := c.call("TeamsFolderPath", nil, &out0)
	return out0, err
}

func (c *Client) TerminalAttach(sessionID string) string {
	var out0 string
	if err := c.call("TerminalAttach", []any{sessionID}, &out0); err != nil {
		c.failed("TerminalAttach", err)
	}
	return out0
}

func (c *Client) TerminalClose(sessionID string) error {
	return c.call("TerminalClose", []any{sessionID}, nil)
}

func (c *Client) TerminalResize(sessionID string, cols int, rows int) error {
	return c.call("TerminalResize", []any{sessionID, cols, rows}, nil)
}

func (c *Client) TerminalShells() []engine.ShellProfile {
	var out0 []engine.ShellProfile
	if err := c.call("TerminalShells", nil, &out0); err != nil {
		c.failed("TerminalShells", err)
	}
	return out0
}

func (c *Client) TerminalStart(shellPath string, cols int, rows int) (string, error) {
	var out0 string
	err := c.call("TerminalStart", []any{shellPath, cols, rows}, &out0)
	return out0, err
}

func (c *Client) TerminalWrite(sessionID string, data string) error {
	return c.call("TerminalWrite", []any{sessionID, data}, nil)
}

func (c *Client) TestMCPServer(name string) engine.MCPServerInfo {
	var out0 engine.MCPServerInfo
	if err := c.call("TestMCPServer", []any{name}, &out0); err != nil {
		c.failed("TestMCPServer", err)
	}
	return out0
}

func (c *Client) ToggleMCPServer(name string, disabled bool) error {
	return c.call("ToggleMCPServer", []any{name, disabled}, nil)
}

func (c *Client) ToolBlockTokens() int {
	var out0 int
	if err := c.call("ToolBlockTokens", nil, &out0); err != nil {
		c.failed("ToolBlockTokens", err)
	}
	return out0
}

func (c *Client) ToolCounts() engine.ToolCounts {
	var out0 engine.ToolCounts
	if err := c.call("ToolCounts", nil, &out0); err != nil {
		c.failed("ToolCounts", err)
	}
	return out0
}

func (c *Client) ToolInstallPlan(name string) engine.ToolInstallPlan {
	var out0 engine.ToolInstallPlan
	if err := c.call("ToolInstallPlan", []any{name}, &out0); err != nil {
		c.failed("ToolInstallPlan", err)
	}
	return out0
}

func (c *Client) TranscribeMicAudio(dataURL string) (string, error) {
	var out0 string
	err := c.call("TranscribeMicAudio", []any{dataURL}, &out0)
	return out0, err
}

func (c *Client) TurnInFlight() engine.TurnStatus {
	var out0 engine.TurnStatus
	if err := c.call("TurnInFlight", nil, &out0); err != nil {
		c.failed("TurnInFlight", err)
	}
	return out0
}

func (c *Client) TurnRating(messageID int64) string {
	var out0 string
	if err := c.call("TurnRating", []any{messageID}, &out0); err != nil {
		c.failed("TurnRating", err)
	}
	return out0
}

func (c *Client) UndoLastTurn() (engine.UndoResult, error) {
	var out0 engine.UndoResult
	err := c.call("UndoLastTurn", nil, &out0)
	return out0, err
}

func (c *Client) UsageStats() (engine.UsageStats, error) {
	var out0 engine.UsageStats
	err := c.call("UsageStats", nil, &out0)
	return out0, err
}

func (c *Client) UseEngine(family string, agent string, id string) error {
	return c.call("UseEngine", []any{family, agent, id}, nil)
}

func (c *Client) UserName() string {
	var out0 string
	if err := c.call("UserName", nil, &out0); err != nil {
		c.failed("UserName", err)
	}
	return out0
}

func (c *Client) VerifyConnection(id string) (connect.Account, error) {
	var out0 connect.Account
	err := c.call("VerifyConnection", []any{id}, &out0)
	return out0, err
}

func (c *Client) VideoCheckSeen() bool {
	var out0 bool
	if err := c.call("VideoCheckSeen", nil, &out0); err != nil {
		c.failed("VideoCheckSeen", err)
	}
	return out0
}

func (c *Client) VideoEditorCommand() []string {
	var out0 []string
	if err := c.call("VideoEditorCommand", nil, &out0); err != nil {
		c.failed("VideoEditorCommand", err)
	}
	return out0
}

func (c *Client) VideoEditorEnvironment() map[string]string {
	var out0 map[string]string
	if err := c.call("VideoEditorEnvironment", nil, &out0); err != nil {
		c.failed("VideoEditorEnvironment", err)
	}
	return out0
}

func (c *Client) VideoEditorHelpURL(what string) string {
	var out0 string
	if err := c.call("VideoEditorHelpURL", []any{what}, &out0); err != nil {
		c.failed("VideoEditorHelpURL", err)
	}
	return out0
}

func (c *Client) VideoEditorTools() []string {
	var out0 []string
	if err := c.call("VideoEditorTools", nil, &out0); err != nil {
		c.failed("VideoEditorTools", err)
	}
	return out0
}

func (c *Client) VideoReadiness(agent string) engine.VideoReadiness {
	var out0 engine.VideoReadiness
	if err := c.call("VideoReadiness", []any{agent}, &out0); err != nil {
		c.failed("VideoReadiness", err)
	}
	return out0
}

func (c *Client) VideoToolingStatus() engine.VideoToolingStatus {
	var out0 engine.VideoToolingStatus
	if err := c.call("VideoToolingStatus", nil, &out0); err != nil {
		c.failed("VideoToolingStatus", err)
	}
	return out0
}

func (c *Client) VoiceSettings() engine.VoiceSettings {
	var out0 engine.VoiceSettings
	if err := c.call("VoiceSettings", nil, &out0); err != nil {
		c.failed("VoiceSettings", err)
	}
	return out0
}

func (c *Client) WorkbenchTabsChanged(sessionID string, tabs []engine.DeskTab) {
	if err := c.call("WorkbenchTabsChanged", []any{sessionID, tabs}, nil); err != nil {
		c.failed("WorkbenchTabsChanged", err)
	}
}

func (c *Client) WorkspaceFolders() []engine.WorkspaceFolder {
	var out0 []engine.WorkspaceFolder
	if err := c.call("WorkspaceFolders", nil, &out0); err != nil {
		c.failed("WorkspaceFolders", err)
	}
	return out0
}

func (c *Client) WriteFile(relPath string, content string) error {
	return c.call("WriteFile", []any{relPath, content}, nil)
}

var _ engine.API = (*Client)(nil)
