// Code generated by internal/engine/gen. DO NOT EDIT.

package rpc

// The engine's end of every binding (§248 phase 2): positional params in,
// the method's own answer out, exactly as the forwarder would have called it.

import (
	"encoding/json"

	"github.com/Mikedev115/Aetox/internal/config"
	"github.com/Mikedev115/Aetox/internal/engine"
	"github.com/Mikedev115/Aetox/internal/model"
	"github.com/Mikedev115/Aetox/internal/subagent"
)

// dispatch answers one binding call on the engine. ok is false for a
// method that is not a binding, so the caller can try its own first.
func dispatch(e *engine.Engine, method string, params json.RawMessage) (result any, err error, ok bool) {
	switch method {
	case "AcceptsAPIKey":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.AcceptsAPIKey(p0), nil, true
	case "ActiveModelFor":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, r1 := e.ActiveModelFor(p0)
		return []any{r0, r1}, nil, true
	case "AddCustomProviderRow":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.AddCustomProviderRow(p0, p1)
		return r0, err, true
	case "AddLearnedEntry":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.AddLearnedEntry(p0, p1), true
	case "AddMCPServer":
		var p0 string
		var p1 []string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.AddMCPServer(p0, p1), true
	case "AddSpaceContextFiles":
		var p0 string
		var p1 []string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.AddSpaceContextFiles(p0, p1)
		return r0, err, true
	case "AddStudioLibraryAt":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.AddStudioLibraryAt(p0)
		return r0, err, true
	case "AddWorkspaceFolderAt":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.AddWorkspaceFolderAt(p0)
		return r0, err, true
	case "AdoptMemoryScope":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.AdoptMemoryScope(p0, p1), true
	case "AgentBlocked":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.AgentBlocked(p0), nil, true
	case "AgentGate":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.AgentGate(p0), nil, true
	case "AgentHomePath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.AgentHomePath(p0)
		return r0, err, true
	case "AgentNeeds":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.AgentNeeds(p0), nil, true
	case "AgentPackageBytes":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.AgentPackageBytes(p0)
		return r0, err, true
	case "AgentSkills":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.AgentSkills(p0), nil, true
	case "AgentSkillsFolderPath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.AgentSkillsFolderPath(p0)
		return r0, err, true
	case "AgentsFolderPath":
		r0, err := e.AgentsFolderPath()
		return r0, err, true
	case "AnswerUserQuestion":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		e.AnswerUserQuestion(p0, p1)
		return nil, nil, true
	case "AnyTurnRunning":
		return e.AnyTurnRunning(), nil, true
	case "AppCredit":
		return e.AppCredit(), nil, true
	case "AppVersion":
		return e.AppVersion(), nil, true
	case "ApplyMemoryLines":
		var p0 string
		var p1 []string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.ApplyMemoryLines(p0, p1), true
	case "ApprovePendingChange":
		var p0 int64
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.ApprovePendingChange(p0), true
	case "ApprovePendingChangeTo":
		var p0 int64
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.ApprovePendingChangeTo(p0, p1), true
	case "ArtifactPath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ArtifactPath(p0)
		return r0, err, true
	case "ArtifactPreview":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ArtifactPreview(p0)
		return r0, err, true
	case "BackgroundRuns":
		return e.BackgroundRuns(), nil, true
	case "BackgroundTasks":
		return e.BackgroundTasks(), nil, true
	case "BrowseFolderAt":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.BrowseFolderAt(p0)
		return r0, err, true
	case "BrowseRoot":
		return e.BrowseRoot(), nil, true
	case "BusySignal":
		return e.BusySignal(), nil, true
	case "CancelMCPSignIn":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		e.CancelMCPSignIn(p0)
		return nil, nil, true
	case "CancelPendingModel":
		return e.CancelPendingModel(), nil, true
	case "CancelStudioScan":
		e.CancelStudioScan()
		return nil, nil, true
	case "CancelTurn":
		e.CancelTurn()
		return nil, nil, true
	case "CapabilitiesInstalling":
		return e.CapabilitiesInstalling(), nil, true
	case "CapabilityForServer":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.CapabilityForServer(p0), nil, true
	case "CapabilityStatuses":
		return e.CapabilityStatuses(), nil, true
	case "CatalogModelChoices":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.CatalogModelChoices(p0), nil, true
	case "ChairStarters":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return e.ChairStarters(p0, p1), nil, true
	case "ChairStartersFile":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ChairStartersFile(p0), nil, true
	case "CheckConnectionServer":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.CheckConnectionServer(p0)
		return r0, err, true
	case "ClearProjectFocus":
		r0, err := e.ClearProjectFocus()
		return r0, err, true
	case "CommandHistory":
		return e.CommandHistory(), nil, true
	case "CompleteMCPSignIn":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.CompleteMCPSignIn(p0), true
	case "CompressArtifacts":
		var p0 []string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.CompressArtifacts(p0)
		return r0, err, true
	case "ComputerControlChanged":
		e.ComputerControlChanged()
		return nil, nil, true
	case "ConnectAccount":
		var p0 string
		var p1 string
		var p2 string
		var p3 []string
		if err := decodeParams(params, &p0, &p1, &p2, &p3); err != nil {
			return nil, err, true
		}
		r0, err := e.ConnectAccount(p0, p1, p2, p3)
		return r0, err, true
	case "Connections":
		return e.Connections(), nil, true
	case "ConsolidateMemory":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ConsolidateMemory(p0)
		return r0, err, true
	case "CopySkillToAgent":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.CopySkillToAgent(p0, p1), true
	case "CreatePullRequest":
		var p0 string
		var p1 string
		var p2 string
		var p3 string
		var p4 bool
		if err := decodeParams(params, &p0, &p1, &p2, &p3, &p4); err != nil {
			return nil, err, true
		}
		return e.CreatePullRequest(p0, p1, p2, p3, p4), nil, true
	case "CreateSpace":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.CreateSpace(p0)
		return r0, err, true
	case "CurrentSessionID":
		return e.CurrentSessionID(), nil, true
	case "CurrentShell":
		return e.CurrentShell(), nil, true
	case "CurrentSpace":
		return e.CurrentSpace(), nil, true
	case "CustomProviders":
		return e.CustomProviders(), nil, true
	case "DeckCaptureDrawing":
		var p0 string
		var p1 int
		var p2 string
		if err := decodeParams(params, &p0, &p1, &p2); err != nil {
			return nil, err, true
		}
		r0, err := e.DeckCaptureDrawing(p0, p1, p2)
		return r0, err, true
	case "DeckExportFiles":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.DeckExportFiles(p0, p1)
		return r0, err, true
	case "DeckFormats":
		return e.DeckFormats(), nil, true
	case "DelegateSwitches":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.DelegateSwitches(p0), nil, true
	case "DeleteArtifact":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.DeleteArtifact(p0), true
	case "DeleteDeck":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.DeleteDeck(p0), true
	case "DeleteIdentityFile":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.DeleteIdentityFile(p0), true
	case "DeletePromptPreset":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.DeletePromptPreset(p0), true
	case "DeleteSession":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.DeleteSession(p0), true
	case "DeleteSpace":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.DeleteSpace(p0), true
	case "DeleteSubagentProfile":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.DeleteSubagentProfile(p0), true
	case "DeleteTeam":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.DeleteTeam(p0), true
	case "DisconnectAccount":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.DisconnectAccount(p0), true
	case "DismissRecurringRequest":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.DismissRecurringRequest(p0, p1), true
	case "DismissTaskChip":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		e.DismissTaskChip(p0)
		return nil, nil, true
	case "EnabledProviders":
		return e.EnabledProviders(), nil, true
	case "EnginesFor":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return e.EnginesFor(p0, p1), nil, true
	case "ExternalEngineStatus":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ExternalEngineStatus(p0), nil, true
	case "FileStillThere":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.FileStillThere(p0), nil, true
	case "ForgetMemoryScope":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.ForgetMemoryScope(p0), true
	case "ForgetProject":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ForgetProject(p0)
		return r0, err, true
	case "GetContextBreakdown":
		return e.GetContextBreakdown(), nil, true
	case "GetModelInfo":
		return e.GetModelInfo(), nil, true
	case "GetProjectStatus":
		return e.GetProjectStatus(), nil, true
	case "GetRepoMapGraph":
		var p0 int
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.GetRepoMapGraph(p0), nil, true
	case "GitBranches":
		return e.GitBranches(), nil, true
	case "GitChangedFiles":
		return e.GitChangedFiles(), nil, true
	case "GitCommitChanges":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.GitCommitChanges(p0), nil, true
	case "GitCommitFileDiff":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return e.GitCommitFileDiff(p0, p1), nil, true
	case "GitCommitFiles":
		var p0 string
		var p1 []string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.GitCommitFiles(p0, p1), true
	case "GitCreateBranch":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.GitCreateBranch(p0)
		return r0, err, true
	case "GitFileDiff":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.GitFileDiff(p0), nil, true
	case "GitLog":
		var p0 string
		var p1 int
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return e.GitLog(p0, p1), nil, true
	case "GitSplitCancel":
		e.GitSplitCancel()
		return nil, nil, true
	case "GitSuggestCommitMessage":
		var p0 []string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.GitSuggestCommitMessage(p0)
		return r0, err, true
	case "GitSuggestSplitCommits":
		r0, err := e.GitSuggestSplitCommits()
		return r0, err, true
	case "GitSwitchBranch":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.GitSwitchBranch(p0)
		return r0, err, true
	case "GitWorkingTree":
		r0, err := e.GitWorkingTree()
		return r0, err, true
	case "GuideTopics":
		return e.GuideTopics(), nil, true
	case "HandedOverFile":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.HandedOverFile(p0), nil, true
	case "HistoryFault":
		return e.HistoryFault(), nil, true
	case "HomeDir":
		return e.HomeDir(), nil, true
	case "ImageStatus":
		return e.ImageStatus(), nil, true
	case "ImportSessionFrom":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ImportSessionFrom(p0)
		return r0, err, true
	case "InstallCapabilities":
		var p0 []string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.InstallCapabilities(p0), nil, true
	case "InstallSkillFromGitHub":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.InstallSkillFromGitHub(p0)
		return r0, err, true
	case "InstallSkillsFromZipAt":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.InstallSkillsFromZipAt(p0)
		return r0, err, true
	case "InstallVoiceEngine":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.InstallVoiceEngine(p0, p1), true
	case "Interject":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.Interject(p0), true
	case "LearnedEntries":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.LearnedEntries(p0), nil, true
	case "LearnedMemory":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.LearnedMemory(p0), nil, true
	case "LearnedScopeInfos":
		return e.LearnedScopeInfos(), nil, true
	case "LearnedScopes":
		return e.LearnedScopes(), nil, true
	case "LearningEnabled":
		return e.LearningEnabled(), nil, true
	case "ListAllSessions":
		return e.ListAllSessions(), nil, true
	case "ListArtifacts":
		return e.ListArtifacts(), nil, true
	case "ListArtifactsForSession":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ListArtifactsForSession(p0), nil, true
	case "ListArtifactsIn":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ListArtifactsIn(p0), nil, true
	case "ListChairs":
		return e.ListChairs(), nil, true
	case "ListDecidedChanges":
		var p0 int
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ListDecidedChanges(p0), nil, true
	case "ListDecidedIssues":
		var p0 int
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ListDecidedIssues(p0), nil, true
	case "ListDecidedSkillProposals":
		var p0 int
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ListDecidedSkillProposals(p0), nil, true
	case "ListDecks":
		return e.ListDecks(), nil, true
	case "ListDecksIn":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ListDecksIn(p0), nil, true
	case "ListDir":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ListDir(p0)
		return r0, err, true
	case "ListExternalSkills":
		return e.ListExternalSkills(), nil, true
	case "ListIdentityFiles":
		r0, err := e.ListIdentityFiles()
		return r0, err, true
	case "ListImageEngines":
		return e.ListImageEngines(), nil, true
	case "ListMCPServers":
		return e.ListMCPServers(), nil, true
	case "ListModes":
		return e.ListModes(), nil, true
	case "ListPendingChanges":
		return e.ListPendingChanges(), nil, true
	case "ListPromptPresets":
		return e.ListPromptPresets(), nil, true
	case "ListReceivedJobs":
		var p0 int
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ListReceivedJobs(p0), nil, true
	case "ListRecurringRequests":
		return e.ListRecurringRequests(), nil, true
	case "ListSessions":
		return e.ListSessions(), nil, true
	case "ListSessionsAt":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ListSessionsAt(p0), nil, true
	case "ListSessionsForDoor":
		var p0 engine.DeskFilter
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ListSessionsForDoor(p0), nil, true
	case "ListSkillProposals":
		return e.ListSkillProposals(), nil, true
	case "ListSkills":
		return e.ListSkills(), nil, true
	case "ListSpeechEngines":
		return e.ListSpeechEngines(), nil, true
	case "ListSpeechModels":
		return e.ListSpeechModels(), nil, true
	case "ListSubagentProfiles":
		return e.ListSubagentProfiles(), nil, true
	case "ListSystemIssues":
		return e.ListSystemIssues(), nil, true
	case "ListTTSEngines":
		return e.ListTTSEngines(), nil, true
	case "ListTaskChips":
		return e.ListTaskChips(), nil, true
	case "ListTeams":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ListTeams(p0), nil, true
	case "ListTools":
		return e.ListTools(), nil, true
	case "LoadSession":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.LoadSession(p0)
		return r0, err, true
	case "LoadSessionAnyProject":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.LoadSessionAnyProject(p0)
		return r0, err, true
	case "MCPConfigPath":
		return e.MCPConfigPath(), nil, true
	case "MCPFolderPath":
		r0, err := e.MCPFolderPath()
		return r0, err, true
	case "MCPSignInStatus":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.MCPSignInStatus(p0), nil, true
	case "MachineInfo":
		return e.MachineInfo(), nil, true
	case "MarkIssueReported":
		var p0 int64
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.MarkIssueReported(p0), true
	case "MarkVideoCheckSeen":
		e.MarkVideoCheckSeen()
		return nil, nil, true
	case "MemoryFolderPath":
		r0, err := e.MemoryFolderPath()
		return r0, err, true
	case "MobileRemoteQR":
		return e.MobileRemoteQR(), nil, true
	case "MobileRemoteStatus":
		return e.MobileRemoteStatus(), nil, true
	case "ModelPriceSource":
		return e.ModelPriceSource(), nil, true
	case "ModelStatus":
		return e.ModelStatus(), nil, true
	case "MoveLearnedEntry":
		var p0 string
		var p1 string
		var p2 int
		if err := decodeParams(params, &p0, &p1, &p2); err != nil {
			return nil, err, true
		}
		return nil, e.MoveLearnedEntry(p0, p1, p2), true
	case "NewChairSession":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.NewChairSession(p0)
		return r0, err, true
	case "NewChairSessionAt":
		var p0 string
		var p1 string
		var p2 string
		if err := decodeParams(params, &p0, &p1, &p2); err != nil {
			return nil, err, true
		}
		r0, err := e.NewChairSessionAt(p0, p1, p2)
		return r0, err, true
	case "NewSession":
		r0, err := e.NewSession()
		return r0, err, true
	case "NewSessionAt":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.NewSessionAt(p0)
		return r0, err, true
	case "NewSessionInSpace":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.NewSessionInSpace(p0)
		return r0, err, true
	case "NewTeamSession":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.NewTeamSession(p0, p1)
		return r0, err, true
	case "NoteProviderQuotas":
		var p0 string
		var p1 []model.Quota
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		e.NoteProviderQuotas(p0, p1)
		return nil, nil, true
	case "OpenProjectPath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.OpenProjectPath(p0)
		return r0, err, true
	case "PageMarksOn":
		return e.PageMarksOn(), nil, true
	case "PairedDevices":
		return e.PairedDevices(), nil, true
	case "PausePlanRun":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		e.PausePlanRun(p0)
		return nil, nil, true
	case "PendingChangeByID":
		var p0 int64
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.PendingChangeByID(p0), nil, true
	case "PendingIssueCount":
		return e.PendingIssueCount(), nil, true
	case "PendingLearnedCount":
		return e.PendingLearnedCount(), nil, true
	case "PendingRestore":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.PendingRestore(p0), nil, true
	case "PendingSkillTuneCount":
		return e.PendingSkillTuneCount(), nil, true
	case "PendingUndo":
		return e.PendingUndo(), nil, true
	case "PictureBytes":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.PictureBytes(p0)
		return r0, err, true
	case "PlacementTargets":
		return e.PlacementTargets(), nil, true
	case "PlanRunning":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.PlanRunning(p0), nil, true
	case "PrepareToClose":
		e.PrepareToClose()
		return nil, nil, true
	case "PreparedReplyOn":
		return e.PreparedReplyOn(), nil, true
	case "PriceModels":
		var p0 string
		var p1 []string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return e.PriceModels(p0, p1), nil, true
	case "ProjectFilePath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ProjectFilePath(p0)
		return r0, err, true
	case "ProjectTree":
		return e.ProjectTree(), nil, true
	case "PromptsFolderPath":
		r0, err := e.PromptsFolderPath()
		return r0, err, true
	case "ProviderAPIKeyURL":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ProviderAPIKeyURL(p0), nil, true
	case "ProviderBaseURL":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ProviderBaseURL(p0), nil, true
	case "ProviderBaseURLIsCustom":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ProviderBaseURLIsCustom(p0), nil, true
	case "ProviderCredentialChanged":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ProviderCredentialChanged(p0)
		return r0, err, true
	case "ProviderQuotas":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, r1 := e.ProviderQuotas(p0)
		return []any{r0, r1}, nil, true
	case "ProviderWireFormats":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ProviderWireFormats(p0), nil, true
	case "PullRequestChecks":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.PullRequestChecks(p0), nil, true
	case "PullRequestFiles":
		var p0 int
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.PullRequestFiles(p0), nil, true
	case "PullRequests":
		return e.PullRequests(), nil, true
	case "PullRequestsState":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.PullRequestsState(p0), nil, true
	case "RateTurn":
		var p0 int64
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		e.RateTurn(p0, p1)
		return nil, nil, true
	case "ReadFile":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ReadFile(p0)
		return r0, err, true
	case "ReadIdentityFile":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ReadIdentityFile(p0)
		return r0, err, true
	case "ReadImageDataURL":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ReadImageDataURL(p0)
		return r0, err, true
	case "ReadSubagentProfile":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ReadSubagentProfile(p0)
		return r0, err, true
	case "ReadWorkbook":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ReadWorkbook(p0)
		return r0, err, true
	case "ReadyToRestart":
		return nil, e.ReadyToRestart(), true
	case "RecentAgentPages":
		var p0 int
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.RecentAgentPages(p0), nil, true
	case "RecentDebugLog":
		return e.RecentDebugLog(), nil, true
	case "RecentProjects":
		return e.RecentProjects(), nil, true
	case "RefreshModelFacts":
		e.RefreshModelFacts()
		return nil, nil, true
	case "RefreshSkills":
		e.RefreshSkills()
		return nil, nil, true
	case "RegenerateReply":
		var p0 bool
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.RegenerateReply(p0)
		return r0, err, true
	case "RejectPendingChange":
		var p0 int64
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.RejectPendingChange(p0), true
	case "RelativizePath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.RelativizePath(p0)
		return r0, err, true
	case "RememberTTSVoice":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		e.RememberTTSVoice(p0)
		return nil, nil, true
	case "RemoveAgentSkill":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.RemoveAgentSkill(p0, p1), true
	case "RemoveCustomProviderRow":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.RemoveCustomProviderRow(p0)
		return r0, err, true
	case "RemoveExternalSkill":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.RemoveExternalSkill(p0), true
	case "RemoveMCPServer":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.RemoveMCPServer(p0), true
	case "RemovePresetImage":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.RemovePresetImage(p0), true
	case "RemoveSpaceContext":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.RemoveSpaceContext(p0, p1)
		return r0, err, true
	case "RemoveStudioLibrary":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.RemoveStudioLibrary(p0)
		return r0, err, true
	case "RemoveWorkspaceFolder":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.RemoveWorkspaceFolder(p0)
		return r0, err, true
	case "RequiresAPIKey":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.RequiresAPIKey(p0), nil, true
	case "RescanStudioLibrary":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.RescanStudioLibrary(p0)
		return r0, err, true
	case "ResendEdited":
		var p0 string
		var p1 bool
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.ResendEdited(p0, p1)
		return r0, err, true
	case "ResolveAddress":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ResolveAddress(p0), nil, true
	case "ResolveWorkbenchURL":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, r1 := e.ResolveWorkbenchURL(p0)
		return []any{r0, r1}, nil, true
	case "RestorePoints":
		return e.RestorePoints(), nil, true
	case "RestoreRecurringRequest":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.RestoreRecurringRequest(p0), true
	case "ResumePlanRun":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		e.ResumePlanRun(p0)
		return nil, nil, true
	case "RetryActiveProvider":
		return e.RetryActiveProvider(), nil, true
	case "RetryFailedTurn":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.RetryFailedTurn(p0)
		return r0, err, true
	case "ReviewPullRequest":
		var p0 int
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.ReviewPullRequest(p0)
		return r0, err, true
	case "RevokeDevice":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.RevokeDevice(p0), true
	case "RewindTo":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.RewindTo(p0)
		return r0, err, true
	case "RunChatCommand":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.RunChatCommand(p0)
		return r0, err, true
	case "RunChatScript":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.RunChatScript(p0, p1)
		return r0, err, true
	case "RunSessionReview":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.RunSessionReview(p0)
		return r0, err, true
	case "RunSkillTuneup":
		r0, err := e.RunSkillTuneup()
		return r0, err, true
	case "RunnableLanguages":
		return e.RunnableLanguages(), nil, true
	case "SandboxFile":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SandboxFile(p0)
		return r0, err, true
	case "SaveAgentProfile":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.SaveAgentProfile(p0, p1), true
	case "SaveBrowserShot":
		var p0 []byte
		var p1 bool
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.SaveBrowserShot(p0, p1)
		return r0, err, true
	case "SaveChairStarters":
		var p0 string
		var p1 string
		var p2 subagent.StarterSet
		if err := decodeParams(params, &p0, &p1, &p2); err != nil {
			return nil, err, true
		}
		return nil, e.SaveChairStarters(p0, p1, p2), true
	case "SaveChatFile":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SaveChatFile(p0)
		return r0, err, true
	case "SaveChatImage":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SaveChatImage(p0)
		return r0, err, true
	case "SaveChatImageData":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SaveChatImageData(p0)
		return r0, err, true
	case "SaveIdentityFile":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.SaveIdentityFile(p0, p1), true
	case "SaveLearnedEntry":
		var p0 string
		var p1 int
		var p2 string
		if err := decodeParams(params, &p0, &p1, &p2); err != nil {
			return nil, err, true
		}
		return nil, e.SaveLearnedEntry(p0, p1, p2), true
	case "SaveMCPServer":
		var p0 string
		var p1 config.MCPServerConfig
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.SaveMCPServer(p0, p1), true
	case "SavePlanText":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return e.SavePlanText(p0, p1), nil, true
	case "SavePromptPreset":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.SavePromptPreset(p0, p1), true
	case "SaveSubagentProfile":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.SaveSubagentProfile(p0, p1), true
	case "SaveTeam":
		var p0 string
		var p1 string
		var p2 string
		var p3 []string
		if err := decodeParams(params, &p0, &p1, &p2, &p3); err != nil {
			return nil, err, true
		}
		return nil, e.SaveTeam(p0, p1, p2, p3), true
	case "SearchAllSessions":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SearchAllSessions(p0), nil, true
	case "SearchSessions":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SearchSessions(p0), nil, true
	case "SearchSessionsForDoor":
		var p0 string
		var p1 engine.DeskFilter
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return e.SearchSessionsForDoor(p0, p1), nil, true
	case "SendMessage":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.SendMessage(p0, p1)
		return r0, err, true
	case "SessionAgent":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SessionAgent(p0), nil, true
	case "SessionEdits":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SessionEdits(p0), nil, true
	case "SessionExportBytes":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.SessionExportBytes(p0, p1)
		return r0, err, true
	case "SessionMode":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SessionMode(p0), nil, true
	case "SessionPlan":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SessionPlan(p0), nil, true
	case "SessionPlanReports":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SessionPlanReports(p0), nil, true
	case "SessionReviewAuto":
		return e.SessionReviewAuto(), nil, true
	case "SessionSourceCount":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SessionSourceCount(p0), nil, true
	case "SessionSources":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SessionSources(p0), nil, true
	case "SessionSpend":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SessionSpend(p0), nil, true
	case "SessionTeam":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SessionTeam(p0), nil, true
	case "SessionTranscript":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SessionTranscript(p0)
		return r0, err, true
	case "SessionsInSpace":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.SessionsInSpace(p0), nil, true
	case "SetAgentOff":
		var p0 string
		var p1 string
		var p2 bool
		if err := decodeParams(params, &p0, &p1, &p2); err != nil {
			return nil, err, true
		}
		return e.SetAgentOff(p0, p1, p2), nil, true
	case "SetBusyLayer":
		var p0 string
		var p1 bool
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return e.SetBusyLayer(p0, p1), nil, true
	case "SetConnectionStartCommand":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.SetConnectionStartCommand(p0, p1), true
	case "SetConnectionTargets":
		var p0 string
		var p1 []string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.SetConnectionTargets(p0, p1), true
	case "SetDelegateOff":
		var p0 string
		var p1 bool
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return e.SetDelegateOff(p0, p1), nil, true
	case "SetImageEngine":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetImageEngine(p0), true
	case "SetImageModelName":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetImageModelName(p0), true
	case "SetLearningEnabled":
		var p0 bool
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetLearningEnabled(p0), true
	case "SetMCPServerTargets":
		var p0 string
		var p1 []string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.SetMCPServerTargets(p0, p1), true
	case "SetPlanStepStop":
		var p0 string
		var p1 int
		var p2 bool
		if err := decodeParams(params, &p0, &p1, &p2); err != nil {
			return nil, err, true
		}
		e.SetPlanStepStop(p0, p1, p2)
		return nil, nil, true
	case "SetPreparedReplyOn":
		var p0 bool
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetPreparedReplyOn(p0), true
	case "SetPresetImageFrom":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.SetPresetImageFrom(p0, p1)
		return r0, err, true
	case "SetProviderBaseURL":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.SetProviderBaseURL(p0, p1)
		return r0, err, true
	case "SetProviderEnabled":
		var p0 string
		var p1 bool
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.SetProviderEnabled(p0, p1)
		return r0, err, true
	case "SetProviderWireFormat":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SetProviderWireFormat(p0)
		return r0, err, true
	case "SetSessionReviewAuto":
		var p0 bool
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetSessionReviewAuto(p0), true
	case "SetShell":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetShell(p0), true
	case "SetSkillTuneAuto":
		var p0 bool
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetSkillTuneAuto(p0), true
	case "SetSpeechEngine":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetSpeechEngine(p0), true
	case "SetSpeechModel":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetSpeechModel(p0), true
	case "SetSpeechModelName":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetSpeechModelName(p0), true
	case "SetStance":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SetStance(p0)
		return r0, err, true
	case "SetSubagentModel":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.SetSubagentModel(p0, p1), true
	case "SetTTSEngine":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetTTSEngine(p0), true
	case "SetTTSModelName":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetTTSModelName(p0), true
	case "SetUILocale":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetUILocale(p0), true
	case "SetUserName":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.SetUserName(p0), true
	case "Shells":
		return e.Shells(), nil, true
	case "SkillScanIssues":
		return e.SkillScanIssues(), nil, true
	case "SkillTuneAuto":
		return e.SkillTuneAuto(), nil, true
	case "SkillsDir":
		return e.SkillsDir(), nil, true
	case "SkillsFolderPath":
		r0, err := e.SkillsFolderPath()
		return r0, err, true
	case "SpaceFolderPath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SpaceFolderPath(p0)
		return r0, err, true
	case "Spaces":
		return e.Spaces(), nil, true
	case "SpeechModelDirPath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SpeechModelDirPath(p0)
		return r0, err, true
	case "SpeechModelDirs":
		return e.SpeechModelDirs(), nil, true
	case "SpeechModelFolderPath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SpeechModelFolderPath(p0)
		return r0, err, true
	case "SpeechStatus":
		return e.SpeechStatus(), nil, true
	case "Stance":
		return e.Stance(), nil, true
	case "Stances":
		return e.Stances(), nil, true
	case "StartConnectionServer":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.StartConnectionServer(p0), true
	case "StartMCPSignIn":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.StartMCPSignIn(p0, p1)
		return r0, err, true
	case "StartMobileRemote":
		return e.StartMobileRemote(), nil, true
	case "StartPlanRun":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.StartPlanRun(p0), nil, true
	case "StopBackgroundRun":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.StopBackgroundRun(p0), nil, true
	case "StopBackgroundTask":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.StopBackgroundTask(p0), nil, true
	case "StopBrowsing":
		e.StopBrowsing()
		return nil, nil, true
	case "StopMobileRemote":
		return e.StopMobileRemote(), nil, true
	case "StopPlanRun":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		e.StopPlanRun(p0)
		return nil, nil, true
	case "StopQueuedTasks":
		return e.StopQueuedTasks(), nil, true
	case "StudioAssetPath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.StudioAssetPath(p0)
		return r0, err, true
	case "StudioAssets":
		var p0 engine.StudioAssetQuery
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.StudioAssets(p0), nil, true
	case "StudioLibraries":
		return e.StudioLibraries(), nil, true
	case "StudioLibraryPath":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.StudioLibraryPath(p0)
		return r0, err, true
	case "StudioScanning":
		return e.StudioScanning(), nil, true
	case "StudioSetHidden":
		var p0 string
		var p1 bool
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.StudioSetHidden(p0, p1), true
	case "StudioSetKind":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.StudioSetKind(p0, p1), true
	case "StudioThumbs":
		var p0 []string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.StudioThumbs(p0), nil, true
	case "SubagentsFolderPath":
		r0, err := e.SubagentsFolderPath()
		return r0, err, true
	case "SuggestPRDetails":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.SuggestPRDetails(p0, p1)
		return r0, err, true
	case "SupportedProviders":
		return e.SupportedProviders(), nil, true
	case "SupportedThinkLevels":
		return e.SupportedThinkLevels(), nil, true
	case "SupportedThinkLevelsFor":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return e.SupportedThinkLevelsFor(p0, p1), nil, true
	case "SwitchApprovalMode":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SwitchApprovalMode(p0)
		return r0, err, true
	case "SwitchModel":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SwitchModel(p0)
		return r0, err, true
	case "SwitchProvider":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SwitchProvider(p0)
		return r0, err, true
	case "SwitchThinkLevel":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SwitchThinkLevel(p0)
		return r0, err, true
	case "SwitchVariant":
		var p0 int
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.SwitchVariant(p0)
		return r0, err, true
	case "SynthesizeHabit":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		r0, err := e.SynthesizeHabit(p0, p1)
		return r0, err, true
	case "TeamsFolderPath":
		r0, err := e.TeamsFolderPath()
		return r0, err, true
	case "TerminalAttach":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.TerminalAttach(p0), nil, true
	case "TerminalClose":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return nil, e.TerminalClose(p0), true
	case "TerminalResize":
		var p0 string
		var p1 int
		var p2 int
		if err := decodeParams(params, &p0, &p1, &p2); err != nil {
			return nil, err, true
		}
		return nil, e.TerminalResize(p0, p1, p2), true
	case "TerminalShells":
		return e.TerminalShells(), nil, true
	case "TerminalStart":
		var p0 string
		var p1 int
		var p2 int
		if err := decodeParams(params, &p0, &p1, &p2); err != nil {
			return nil, err, true
		}
		r0, err := e.TerminalStart(p0, p1, p2)
		return r0, err, true
	case "TerminalWrite":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.TerminalWrite(p0, p1), true
	case "TestMCPServer":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.TestMCPServer(p0), nil, true
	case "ToggleMCPServer":
		var p0 string
		var p1 bool
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.ToggleMCPServer(p0, p1), true
	case "ToolBlockTokens":
		return e.ToolBlockTokens(), nil, true
	case "ToolCounts":
		return e.ToolCounts(), nil, true
	case "ToolInstallPlan":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.ToolInstallPlan(p0), nil, true
	case "TranscribeMicAudio":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.TranscribeMicAudio(p0)
		return r0, err, true
	case "TurnInFlight":
		return e.TurnInFlight(), nil, true
	case "TurnRating":
		var p0 int64
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.TurnRating(p0), nil, true
	case "UndoLastTurn":
		r0, err := e.UndoLastTurn()
		return r0, err, true
	case "UsageStats":
		r0, err := e.UsageStats()
		return r0, err, true
	case "UseEngine":
		var p0 string
		var p1 string
		var p2 string
		if err := decodeParams(params, &p0, &p1, &p2); err != nil {
			return nil, err, true
		}
		return nil, e.UseEngine(p0, p1, p2), true
	case "UserName":
		return e.UserName(), nil, true
	case "VerifyConnection":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		r0, err := e.VerifyConnection(p0)
		return r0, err, true
	case "VideoCheckSeen":
		return e.VideoCheckSeen(), nil, true
	case "VideoEditorCommand":
		return e.VideoEditorCommand(), nil, true
	case "VideoEditorEnvironment":
		return e.VideoEditorEnvironment(), nil, true
	case "VideoEditorHelpURL":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.VideoEditorHelpURL(p0), nil, true
	case "VideoEditorTools":
		return e.VideoEditorTools(), nil, true
	case "VideoReadiness":
		var p0 string
		if err := decodeParams(params, &p0); err != nil {
			return nil, err, true
		}
		return e.VideoReadiness(p0), nil, true
	case "VideoToolingStatus":
		return e.VideoToolingStatus(), nil, true
	case "VoiceSettings":
		return e.VoiceSettings(), nil, true
	case "WorkbenchTabsChanged":
		var p0 string
		var p1 []engine.DeskTab
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		e.WorkbenchTabsChanged(p0, p1)
		return nil, nil, true
	case "WorkspaceFolders":
		return e.WorkspaceFolders(), nil, true
	case "WriteFile":
		var p0 string
		var p1 string
		if err := decodeParams(params, &p0, &p1); err != nil {
			return nil, err, true
		}
		return nil, e.WriteFile(p0, p1), true
	}
	return nil, nil, false
}
