import type { CatalogEntry, TargetCatalogEntry, ConceptCatalogEntry } from './types'

export const CATALOG_TARGETS: TargetCatalogEntry[] = [
  // ── The guide's own doors (§293) ───────────────────────────────────────────
  { id: 'chat.guide', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§293' }, synonyms: ['ปรึกษาไกด์หน้าแชท', 'guide link chat', 'ถามไกด์'] },
  { id: 'account.guide', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§293' }, synonyms: ['ปรึกษาไกด์', 'ถามไกด์', 'ไกด์', 'guide', 'help', 'ช่วยเหลือ', 'F1'] },
  { id: 'settings.about.guide_btn', kind: 'target', page: 'settings.about', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§293' }, synonyms: ['ปรึกษาไกด์ในตั้งค่า', 'guide button settings', 'about guide'] },

  // ── Area 1: Sidebar ────────────────────────────────────────────────────────
  { id: 'sidebar.projects', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§90' }, synonyms: ['โปรเจกต์', 'projects', 'folder', 'โฟลเดอร์'] },
  { id: 'sidebar.open_folder', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, synonyms: ['เปิดโฟลเดอร์', 'open folder', 'browse'] },
  { id: 'sidebar.create_project', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§90' }, synonyms: ['สร้างโปรเจกต์', 'new project', 'create project'] },
  { id: 'sidebar.create_project_name', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'focus' }, navigation: { via: ['sidebar.create_project'], condition: { selector: '[data-guide="sidebar.create_project_name"]', notOnScreenMessageKey: 'guide.condition.openCreateProjectFirst' } }, synonyms: ['ชื่อโปรเจกต์', 'project name'] },
  { id: 'sidebar.create_project_move', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, navigation: { via: ['sidebar.create_project'] }, synonyms: ['เปลี่ยนที่เก็บ', 'move project', 'project location'] },
  { id: 'sidebar.create_project_submit', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, navigation: { via: ['sidebar.create_project'] }, synonyms: ['ยืนยันสร้างโปรเจกต์', 'create and chat'] },
  { id: 'sidebar.create_project_cancel', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, navigation: { via: ['sidebar.create_project'] }, synonyms: ['ยกเลิกสร้างโปรเจกต์', 'cancel project'] },
  { id: 'sidebar.search', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'focus' }, synonyms: ['ค้นหาแชท', 'search history', 'find chat'] },
  { id: 'sidebar.import_chat', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, synonyms: ['นำเข้าแชท', 'import session', 'load chat'] },
  { id: 'sidebar.new_session', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['แชทใหม่', 'new chat', 'new session'] },
  { id: 'sidebar.history', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['ประวัติ', 'history', 'past chats'] },
  { id: 'sidebar.desk.assistant', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§86' }, synonyms: ['โต๊ะผู้ช่วย', 'assistant desk', 'ผู้ช่วย'] },
  { id: 'sidebar.desk.coding', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§86' }, synonyms: ['โต๊ะโค้ด', 'coding desk', 'โค้ด'] },
  { id: 'sidebar.desk.capability', kind: 'target', page: 'capability.mine', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§265' }, synonyms: ['ความสามารถ', 'capability', 'tools room'] },
  { id: 'sidebar.desk.office', kind: 'target', page: 'office', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§85' }, synonyms: ['ออฟฟิศ', 'office', 'ทีม', 'team'] },
  { id: 'sidebar.desk.artifacts', kind: 'target', page: 'artifacts', policy: { safe: true, actionType: 'click' }, synonyms: ['คลังผลงาน', 'artifacts', 'ผลงาน'] },
  { id: 'sidebar.footer', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§255' }, synonyms: ['เมนูบัญชี', 'profile menu', 'account menu', 'footer'] },

  // ── Area 2: Account Menu ───────────────────────────────────────────────────
  { id: 'account.name', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§255' }, synonyms: ['ชื่อโปรไฟล์', 'your name', 'profile name'] },
  { id: 'account.theme', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['ธีม', 'theme', 'color scheme'] },
  { id: 'account.language', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['ภาษา', 'language', 'locale'] },
  { id: 'account.companion', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, synonyms: ['ตัวช่วยบนจอ', 'companion', 'mascot', 'มาสคอต'] },
  { id: 'account.tour', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§279' }, synonyms: ['รู้จักกับ Aetox', 'tour', 'ทัวร์'] },
  { id: 'account.update_check', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, evidence: { ref: '§107' }, synonyms: ['ตรวจอัปเดต', 'check update', 'version update'] },
  { id: 'account.settings', kind: 'target', page: 'settings.general', policy: { safe: true, actionType: 'click' }, synonyms: ['ตั้งค่า', 'settings', 'preferences'] },

  // ── Area 3: TopBar ─────────────────────────────────────────────────────────
  { id: 'topbar.door', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§86' }, synonyms: ['ประตูสลับหัว', 'door', 'switch head', 'หัว'] },
  { id: 'topbar.door.assistant', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§86' }, synonyms: ['เลือกหัวผู้ช่วย', 'assistant head'] },
  { id: 'topbar.door.coding', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§86' }, synonyms: ['เลือกหัวโค้ด', 'coding head'] },
  { id: 'topbar.sidebar_btn', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['เปิดปิดแถบข้าง', 'toggle sidebar', 'hide sidebar'] },
  { id: 'topbar.inspector_btn', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['เปิดปิดแผงตรวจ', 'toggle inspector', 'side panel'] },
  { id: 'topbar.space', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'none' }, synonyms: ['ป้ายโปรเจกต์', 'project badge', 'space name'] },
  { id: 'topbar.tabs', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บห้องทำงาน', 'workbench tabs'] },
  { id: 'topbar.tab.chat', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บแชท', 'chat tab'] },
  { id: 'topbar.tab.diff', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บ diff', 'diff tab', 'เปรียบเทียบโค้ด'] },
  { id: 'topbar.tab.editor', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บแก้ไขไฟล์', 'editor tab'] },
  { id: 'topbar.tab.browser', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บเบราว์เซอร์', 'browser tab'] },
  { id: 'topbar.tab.terminal', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บเทอร์มินัล', 'terminal tab'] },

  // ── Area 4: Composer & Chat ────────────────────────────────────────────────
  { id: 'composer.input', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'focus' }, synonyms: ['ช่องพิมพ์', 'composer', 'message input', 'พิมพ์ข้อความ'] },
  { id: 'composer.attach', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, evidence: { ref: '§257' }, synonyms: ['แนบไฟล์', 'attach file', 'upload file'] },
  { id: 'composer.mic', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, evidence: { ref: '§215' }, synonyms: ['ไมค์', 'microphone', 'voice input', 'พูด'] },
  { id: 'chat.send', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, evidence: { ref: '§163' }, synonyms: ['ปุ่มส่ง', 'send button', 'stop', 'หยุด'] },
  { id: 'composer.stance', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§106' }, synonyms: ['ระดับการลงมือ', 'stance', 'approval mode', 'สแตนซ์'] },
  { id: 'composer.think', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§275' }, synonyms: ['ระดับความคิด', 'think level', 'reasoning'] },
  { id: 'composer.model', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§185' }, synonyms: ['สลับโมเดล', 'switch model', 'choose model'] },
  { id: 'chat.empty_headline', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'none' }, evidence: { ref: '§255' }, synonyms: ['ข้อความทักทาย', 'greeting', 'room headline'] },
  { id: 'chat.starter', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['ตัวอย่างคำสั่ง', 'starters', 'prompt starter'] },
  { id: 'chat.starter_more', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['ขอตัวอย่างเพิ่ม', 'more starters', 'reroll starters'] },
  { id: 'chat.tour', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§279' }, synonyms: ['ทัวร์หน้าแชท', 'tour link', 'chat tour'] },

  // ── Area 5: Memory Cards ───────────────────────────────────────────────────
  { id: 'memory.card', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'none' }, evidence: { ref: '§279' }, synonyms: ['การ์ดขอจำ', 'memory proposal', 'memory card'] },
  { id: 'memory.card.accept', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, evidence: { ref: '§279' }, synonyms: ['อนุมัติให้จำ', 'accept memory', 'approve memory'] },
  { id: 'memory.card.reject', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, evidence: { ref: '§246' }, synonyms: ['ไม่ให้จำ', 'reject memory', 'dismiss memory'] },
  { id: 'memory.card.edit', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['แก้ไขความจำ', 'edit memory'] },
  { id: 'memory.card.scope', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§116' }, synonyms: ['ขอบเขตความจำ', 'memory scope'] },

  // ── Area 6: Settings Rail & General ────────────────────────────────────────
  { id: 'settings.back', kind: 'target', page: 'settings.general', policy: { safe: true, actionType: 'click' }, synonyms: ['กลับไปแชท', 'back to app', 'close settings'] },
  { id: 'settings.search', kind: 'target', page: 'settings.general', policy: { safe: true, actionType: 'focus' }, synonyms: ['ค้นหาการตั้งค่า', 'search settings'] },
  { id: 'settings.rail.general', kind: 'target', page: 'settings.general', policy: { safe: true, actionType: 'click' }, synonyms: ['ตั้งค่าทั่วไป', 'general settings'] },
  { id: 'settings.rail.appearance', kind: 'target', page: 'settings.appearance', policy: { safe: true, actionType: 'click' }, synonyms: ['รูปลักษณ์', 'appearance', 'theme settings'] },
  { id: 'settings.rail.avatar', kind: 'target', page: 'settings.avatar', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§254' }, synonyms: ['ตั้งค่าอวตาร', 'avatar settings', 'mascot avatar'] },
  { id: 'settings.rail.you', kind: 'target', page: 'settings.you', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§229' }, synonyms: ['เกี่ยวกับคุณ', 'about you', 'user profile'] },
  { id: 'settings.rail.issues', kind: 'target', page: 'settings.issues', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§246' }, synonyms: ['แจ้งปัญหา', 'system issues', 'diagnostics'] },
  { id: 'settings.rail.brain', kind: 'target', page: 'settings.models', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§279' }, synonyms: ['ต่อสมอง', 'connect brain', 'models', 'providers'] },
  { id: 'settings.rail.heads', kind: 'target', page: 'settings.main', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§266' }, synonyms: ['ตัวหลัก', 'heads settings', 'main assistant'] },
  { id: 'settings.rail.teams', kind: 'target', page: 'settings.teams', policy: { safe: true, actionType: 'click' }, synonyms: ['จัดการทีม', 'teams settings'] },
  { id: 'settings.rail.agents', kind: 'target', page: 'settings.team', policy: { safe: true, actionType: 'click' }, synonyms: ['พนักงาน', 'specialists', 'agents'] },
  { id: 'settings.rail.hands', kind: 'target', page: 'settings.agents', policy: { safe: true, actionType: 'click' }, synonyms: ['ลูกมือ', 'helpers', 'subagents'] },
  { id: 'settings.rail.voice', kind: 'target', page: 'settings.voice', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§215' }, synonyms: ['ตั้งค่าเสียง', 'voice settings', 'speech'] },
  { id: 'settings.rail.image', kind: 'target', page: 'settings.image', policy: { safe: true, actionType: 'click' }, synonyms: ['ตั้งค่าภาพ', 'image settings', 'vision'] },
  { id: 'settings.rail.studio', kind: 'target', page: 'settings.studio', policy: { safe: true, actionType: 'click' }, synonyms: ['ตั้งค่าสตูดิโอ', 'studio settings'] },
  { id: 'settings.rail.remote', kind: 'target', page: 'settings.remote', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§248' }, synonyms: ['การเชื่อมต่อทางไกล', 'remote engine'] },
  { id: 'settings.rail.account', kind: 'target', page: 'settings.account', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§162' }, synonyms: ['บัญชี Aetox', 'aetox account'] },
  { id: 'settings.rail.usage', kind: 'target', page: 'settings.usage', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§133' }, synonyms: ['สถิติการใช้งาน', 'token usage', 'metrics'] },
  { id: 'settings.rail.about', kind: 'target', page: 'settings.about', policy: { safe: true, actionType: 'click' }, synonyms: ['เกี่ยวกับ Aetox', 'about app', 'version info'] },
  { id: 'settings.rail.sponsor', kind: 'target', page: 'settings.sponsor', policy: { safe: true, actionType: 'click' }, synonyms: ['ผู้สนับสนุน', 'sponsor'] },
  { id: 'settings.general.theme', kind: 'target', page: 'settings.general', policy: { safe: true, actionType: 'click' }, synonyms: ['เลือกธีม', 'select theme'] },
  { id: 'settings.general.language', kind: 'target', page: 'settings.general', policy: { safe: true, actionType: 'click' }, synonyms: ['เลือกภาษา', 'select language'] },
  { id: 'settings.general.font_scale', kind: 'target', page: 'settings.general', policy: { safe: true, actionType: 'click' }, synonyms: ['ขนาดตัวอักษร', 'font scale', 'text size'] },

  // ── Area 7: Settings Head & Agents ─────────────────────────────────────────
  { id: 'settings.head.hero', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: true, actionType: 'none' }, evidence: { ref: '§267' }, synonyms: ['ข้อมูลตัวหลัก', 'head hero'] },
  { id: 'settings.head.rank', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: false, actionType: 'click' }, synonyms: ['ตรายศ', 'rank badge', 'rank emblem'] },
  { id: 'settings.head.switch_desk', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: true, actionType: 'click' }, synonyms: ['สลับหัวตัวหลัก', 'switch head in settings'] },
  { id: 'settings.head.tab.identity', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§270' }, synonyms: ['แท็บตัวตน', 'identity tab'] },
  { id: 'settings.head.tab.mcp', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บ MCP ประจำหัว', 'head mcp tab'] },
  { id: 'settings.head.tab.skills', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บสกิลประจำหัว', 'head skills tab'] },
  { id: 'settings.head.tab.dialogue', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บเปิดบทสนทนา', 'dialogue starters tab'] },
  { id: 'settings.head.tab.memory', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บความจำ', 'head memory tab', 'ความจำ', 'memory'] },
  { id: 'settings.head.tab.tools', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: true, actionType: 'click' }, synonyms: ['แท็บเครื่องมือ', 'head tools tab'] },
  { id: 'settings.head.save', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: false, actionType: 'click' }, synonyms: ['บันทึกหัว', 'save head profile'] },
  { id: 'settings.head.delete', kind: 'target', page: 'settings.main', head: 'assistant', policy: { safe: false, actionType: 'click' }, synonyms: ['ลบเอเจน', 'delete agent'] },

  // ── Area 8: Settings Brain ─────────────────────────────────────────────────
  { id: 'settings.brain.hero', kind: 'target', page: 'settings.models', policy: { safe: true, actionType: 'none' }, synonyms: ['ข้อมูลต่อสมอง', 'brain hero'] },
  { id: 'settings.brain.provider.ollama', kind: 'target', page: 'settings.models', policy: { safe: true, actionType: 'click' }, synonyms: ['โมเดลในเครื่อง', 'ollama', 'lm studio', 'local model'] },
  { id: 'settings.brain.provider.openai', kind: 'target', page: 'settings.models', policy: { safe: true, actionType: 'click' }, synonyms: ['openai', 'chatgpt', 'gpt-4o'] },
  { id: 'settings.brain.provider.anthropic', kind: 'target', page: 'settings.models', policy: { safe: true, actionType: 'click' }, synonyms: ['anthropic', 'claude'] },
  { id: 'settings.brain.provider.deepseek', kind: 'target', page: 'settings.models', policy: { safe: true, actionType: 'click' }, synonyms: ['deepseek', 'deepseek v3'] },
  { id: 'settings.brain.provider.google', kind: 'target', page: 'settings.models', policy: { safe: true, actionType: 'click' }, synonyms: ['google', 'gemini'] },
  { id: 'settings.brain.provider.groq', kind: 'target', page: 'settings.models', policy: { safe: true, actionType: 'click' }, synonyms: ['groq'] },
  { id: 'settings.brain.provider.openrouter', kind: 'target', page: 'settings.models', policy: { safe: true, actionType: 'click' }, synonyms: ['openrouter'] },
  { id: 'settings.brain.test_connection', kind: 'target', page: 'settings.models', policy: { safe: false, actionType: 'click' }, evidence: { ref: '§108' }, synonyms: ['ทดสอบการเชื่อมต่อ', 'test connection'] },
  { id: 'settings.brain.add_provider', kind: 'target', page: 'settings.models', policy: { safe: true, actionType: 'click' }, synonyms: ['เพิ่มผู้ให้บริการ', 'add provider'] },

  // ── Area 9: You, Voice, Avatar, About ──────────────────────────────────────
  { id: 'settings.you.name_input', kind: 'target', page: 'settings.you', policy: { safe: true, actionType: 'focus' }, synonyms: ['ช่องกรอกชื่อคุณ', 'user name input'] },
  { id: 'settings.you.about_input', kind: 'target', page: 'settings.you', policy: { safe: true, actionType: 'focus' }, synonyms: ['ช่องกรอกข้อมูลคุณ', 'about you notes'] },
  { id: 'settings.you.save', kind: 'target', page: 'settings.you', policy: { safe: false, actionType: 'click' }, synonyms: ['บันทึกข้อมูลคุณ', 'save user profile'] },
  { id: 'settings.voice.switch', kind: 'target', page: 'settings.voice', policy: { safe: false, actionType: 'click' }, synonyms: ['สวิตช์เสียง', 'toggle voice'] },
  { id: 'settings.voice.device_select', kind: 'target', page: 'settings.voice', policy: { safe: true, actionType: 'click' }, synonyms: ['เลือกอุปกรณ์เสียง', 'audio device'] },
  { id: 'settings.voice.test_play', kind: 'target', page: 'settings.voice', policy: { safe: false, actionType: 'click' }, synonyms: ['ทดสอบเสียง', 'test audio'] },
  { id: 'settings.avatar.role_select', kind: 'target', page: 'settings.avatar', policy: { safe: true, actionType: 'click' }, synonyms: ['บทบาทอวตาร', 'avatar role'] },
  { id: 'settings.avatar.accent_select', kind: 'target', page: 'settings.avatar', policy: { safe: true, actionType: 'click' }, synonyms: ['สีเน้นอวตาร', 'avatar accent'] },
  { id: 'settings.avatar.shell_select', kind: 'target', page: 'settings.avatar', policy: { safe: true, actionType: 'click' }, synonyms: ['เปลือกอวตาร', 'avatar shell'] },
  { id: 'settings.avatar.top_select', kind: 'target', page: 'settings.avatar', policy: { safe: true, actionType: 'click' }, synonyms: ['หมวกอวตาร', 'avatar hat', 'antenna'] },
  { id: 'settings.avatar.face_select', kind: 'target', page: 'settings.avatar', policy: { safe: true, actionType: 'click' }, synonyms: ['หน้าตาอวตาร', 'avatar face'] },
  { id: 'settings.avatar.prop_select', kind: 'target', page: 'settings.avatar', policy: { safe: true, actionType: 'click' }, synonyms: ['ของถืออวตาร', 'avatar prop'] },
  { id: 'settings.avatar.save', kind: 'target', page: 'settings.avatar', policy: { safe: false, actionType: 'click' }, synonyms: ['บันทึกอวตาร', 'save avatar'] },
  { id: 'settings.about.version_info', kind: 'target', page: 'settings.about', policy: { safe: true, actionType: 'none' }, synonyms: ['เลขเวอร์ชัน', 'version info'] },
  { id: 'settings.about.update_btn', kind: 'target', page: 'settings.about', policy: { safe: false, actionType: 'click' }, evidence: { ref: '§107' }, synonyms: ['ตรวจอัปเดตเกี่ยวกับ', 'check update in about'] },
  { id: 'settings.about.tour_btn', kind: 'target', page: 'settings.about', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§279' }, synonyms: ['ดูการแนะนำอีกครั้ง', 'replay tour'] },
  { id: 'settings.about.github_btn', kind: 'target', page: 'settings.about', policy: { safe: false, actionType: 'click' }, synonyms: ['github aetox', 'open github'] },
  { id: 'settings.about.license_btn', kind: 'target', page: 'settings.about', policy: { safe: true, actionType: 'click' }, synonyms: ['สัญญาอนุญาต', 'license'] },

  // ── Area 10: Capability Room ───────────────────────────────────────────────
  { id: 'capability.rail.mcp', kind: 'target', page: 'capability.mine', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§253' }, synonyms: ['mcp server', 'หน้า mcp'] },
  { id: 'capability.rail.skills', kind: 'target', page: 'capability.skills', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§265' }, synonyms: ['สกิลของคุณ', 'skills list'] },
  { id: 'capability.rail.builtins', kind: 'target', page: 'capability.tools', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§265' }, synonyms: ['เครื่องมือในตัว', 'builtin tools'] },
  { id: 'capability.rail.computer', kind: 'target', page: 'capability.computer', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§265' }, synonyms: ['การใช้คอมพิวเตอร์', 'computer use'] },
  { id: 'capability.rail.connections', kind: 'target', page: 'capability.connections', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§265' }, synonyms: ['การเชื่อมต่อ', 'external connections'] },
  { id: 'capability.rail.prompts', kind: 'target', page: 'capability.prompts', policy: { safe: true, actionType: 'click' }, synonyms: ['ชุดคำสั่ง', 'prompt presets'] },
  { id: 'capability.mcp.search', kind: 'target', page: 'capability.mine', policy: { safe: true, actionType: 'focus' }, synonyms: ['ค้นหา mcp', 'search mcp'] },
  { id: 'capability.mcp.add_btn', kind: 'target', page: 'capability.mine', policy: { safe: true, actionType: 'click' }, synonyms: ['เพิ่ม mcp', 'add mcp server'] },
  { id: 'capability.mcp.install_action', kind: 'target', page: 'capability.mine', policy: { safe: false, actionType: 'click' }, synonyms: ['ติดตั้ง mcp', 'install mcp'] },
  { id: 'capability.mcp.refresh_btn', kind: 'target', page: 'capability.mine', policy: { safe: false, actionType: 'click' }, synonyms: ['รีเฟรช mcp', 'refresh mcp'] },
  { id: 'capability.skills.search', kind: 'target', page: 'capability.skills', policy: { safe: true, actionType: 'focus' }, synonyms: ['ค้นหาสกิล', 'search skills'] },
  { id: 'capability.skills.add_btn', kind: 'target', page: 'capability.skills', policy: { safe: true, actionType: 'click' }, synonyms: ['เพิ่มสกิล', 'add skill'] },
  { id: 'capability.skills.folder_btn', kind: 'target', page: 'capability.skills', policy: { safe: false, actionType: 'click' }, synonyms: ['เปิดโฟลเดอร์สกิล', 'skills folder'] },
  { id: 'capability.builtins.filter', kind: 'target', page: 'capability.tools', policy: { safe: true, actionType: 'click' }, synonyms: ['กรองเครื่องมือ', 'filter builtin tools'] },
  { id: 'capability.computer.toggle', kind: 'target', page: 'capability.computer', policy: { safe: false, actionType: 'click' }, synonyms: ['สวิตช์ใช้คอมพิวเตอร์', 'toggle computer use'] },
  { id: 'capability.computer.apps_list', kind: 'target', page: 'capability.computer', policy: { safe: true, actionType: 'click' }, synonyms: ['รายการโปรแกรม', 'allowed apps'] },
  { id: 'capability.connections.add_btn', kind: 'target', page: 'capability.connections', policy: { safe: true, actionType: 'click' }, synonyms: ['เพิ่มการเชื่อมต่อ', 'add connection'] },
  { id: 'capability.prompts.new_btn', kind: 'target', page: 'capability.prompts', policy: { safe: true, actionType: 'click' }, synonyms: ['สร้างชุดคำสั่ง', 'new prompt preset'] },

  // ── Area 11: Office & Teams ────────────────────────────────────────────────
  { id: 'office.header', kind: 'target', page: 'office', policy: { safe: true, actionType: 'none' }, evidence: { ref: '§85' }, synonyms: ['ผังองค์กร', 'office roster', 'office view'] },
  { id: 'office.team_tab', kind: 'target', page: 'office', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§256' }, synonyms: ['แท็บทีม', 'teams tab'] },
  { id: 'office.new_agent_btn', kind: 'target', page: 'settings.agents', policy: { safe: true, actionType: 'click' }, synonyms: ['จ้างพนักงานใหม่', 'new agent', 'hire agent'] },
  { id: 'office.member_card', kind: 'target', page: 'office', policy: { safe: true, actionType: 'click' }, synonyms: ['การ์ดพนักงาน', 'agent card', 'member card'] },
  { id: 'office.chat_btn', kind: 'target', page: 'office', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§85' }, synonyms: ['คุยกับพนักงาน', 'chat with agent'] },
  { id: 'team.name_input', kind: 'target', page: 'settings.teams', policy: { safe: true, actionType: 'focus' }, evidence: { ref: '§256' }, synonyms: ['ชื่อทีม', 'team name'] },
  { id: 'team.lead_select', kind: 'target', page: 'settings.teams', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§256' }, synonyms: ['หัวหน้าทีม', 'team lead'] },
  { id: 'team.add_member_btn', kind: 'target', page: 'settings.teams', policy: { safe: true, actionType: 'click' }, evidence: { ref: '§256' }, synonyms: ['เพิ่มสมาชิกทีม', 'add team member'] },
  { id: 'team.save_btn', kind: 'target', page: 'settings.teams', policy: { safe: false, actionType: 'click' }, synonyms: ['บันทึกทีม', 'save team'] },
  { id: 'team.delete_btn', kind: 'target', page: 'settings.teams', policy: { safe: false, actionType: 'click' }, synonyms: ['ลบทีม', 'delete team'] },

  // ── Area 12: Background Work & Studio ──────────────────────────────────────
  { id: 'background.panel', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'none' }, evidence: { ref: '§105' }, synonyms: ['แผงงานเบื้องหลัง', 'background work panel'] },
  { id: 'background.filter_running', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['งานที่กำลังวิ่ง', 'running tasks'] },
  { id: 'background.filter_done', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'click' }, synonyms: ['งานที่เสร็จแล้ว', 'completed tasks'] },
  { id: 'background.clear_btn', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, synonyms: ['ล้างงานเสร็จ', 'clear completed tasks'] },
  { id: 'background.task_item', kind: 'target', page: 'chat', policy: { safe: true, actionType: 'none' }, synonyms: ['รายการงาน', 'task item'] },
  { id: 'background.task_stop', kind: 'target', page: 'chat', policy: { safe: false, actionType: 'click' }, evidence: { ref: '§163' }, synonyms: ['หยุดงานเบื้องหลัง', 'stop background task'] },
  { id: 'studio.browser', kind: 'target', page: 'settings.studio', policy: { safe: true, actionType: 'none' }, synonyms: ['คลังสตูดิโอ', 'studio browser', 'assets'] },
  { id: 'studio.search', kind: 'target', page: 'settings.studio', policy: { safe: true, actionType: 'focus' }, synonyms: ['ค้นหาสื่อ', 'search assets'] },
  { id: 'studio.filter_tab', kind: 'target', page: 'settings.studio', policy: { safe: true, actionType: 'click' }, synonyms: ['กรองสื่อ', 'filter media assets'] },
  { id: 'studio.import_btn', kind: 'target', page: 'settings.studio', policy: { safe: false, actionType: 'click' }, synonyms: ['นำเข้าสื่อ', 'import asset'] },
  { id: 'studio.preview_item', kind: 'target', page: 'settings.studio', policy: { safe: true, actionType: 'click' }, synonyms: ['ดูตัวอย่างสื่อ', 'preview asset'] },
  { id: 'studio.delete_btn', kind: 'target', page: 'settings.studio', policy: { safe: false, actionType: 'click' }, synonyms: ['ลบสื่อ', 'delete asset'] },
]

export const CATALOG_CONCEPTS: ConceptCatalogEntry[] = [
  {
    id: 'concept.stance',
    kind: 'concept',
    relatedTargets: ['composer.stance'],
    preferredPage: 'chat',
    evidence: { ref: '§106', sourceDoc: 'docs/DECISIONS.md' },
    synonyms: ['สแตนซ์', 'ระดับความอิสระ', 'stance', 'autonomy mode', 'approval levels'],
  },
  {
    id: 'concept.desk_separation',
    kind: 'concept',
    relatedTargets: ['sidebar.desk.assistant', 'sidebar.desk.coding', 'topbar.door'],
    preferredPage: 'chat',
    evidence: { ref: '§86', sourceDoc: 'docs/DECISIONS.md' },
    synonyms: ['การแยกโต๊ะ', 'ทำไมมีสองโต๊ะ', 'desk separation', 'assistant vs coding', 'ทำไมไม่ใช้แอปสองตัว'],
  },
  {
    id: 'concept.memory_system',
    kind: 'concept',
    relatedTargets: ['memory.card', 'memory.card.accept', 'memory.card.reject', 'memory.card.scope'],
    preferredPage: 'chat',
    evidence: { ref: '§279', sourceDoc: 'docs/DECISIONS.md' },
    synonyms: ['ระบบความจำ', 'การขอจำ', 'memory system', 'proposal memory', 'ความจำผู้ช่วย'],
  },
  {
    id: 'concept.brain_providers',
    kind: 'concept',
    relatedTargets: ['settings.rail.brain', 'settings.brain.provider.ollama', 'settings.brain.provider.openai', 'settings.brain.test_connection'],
    preferredPage: 'settings.models',
    evidence: { ref: '§279', sourceDoc: 'docs/DECISIONS.md' },
    synonyms: ['ต่อสมอง', 'ผู้ให้บริการโมเดล', 'local models', 'ollama setup', 'api keys'],
  },
  {
    id: 'concept.capability_room',
    kind: 'concept',
    relatedTargets: ['sidebar.desk.capability', 'capability.rail.mcp', 'capability.rail.skills', 'capability.rail.builtins'],
    preferredPage: 'capability.mine',
    evidence: { ref: '§265', sourceDoc: 'docs/DECISIONS.md' },
    synonyms: ['ห้องความสามารถ', 'mcp คืออะไร', 'สกิลทำงานอย่างไร', 'tools and skills'],
  },
]

export const GUIDE_CATALOG: CatalogEntry[] = [
  ...CATALOG_TARGETS,
  ...CATALOG_CONCEPTS,
]
