#!/usr/bin/env python3
"""Build templates/ into the form the shadcn CLI actually fetches.

The item files under templates/<name>/registry-item.json are the SOURCE form:
they name a file by path and stop there. That form is what a person edits and
what git diffs usefully. It is not what `shadcn add` reads.

A published registry serves the BUILT form, where every file's content is
inlined into the JSON, because the CLI fetches one URL and writes files out of
the response — it has no way to resolve `path` against a repository it does not
have. shadcn's own registry does exactly this: apps/v4/public/r/styles/*/*.json
carry `content` beside `path`, generated by their scripts/build-registry.mts.

So this is the same build, for our seven pages, in the language this repo
already uses for tooling. Output goes to templates/r/, which is the directory a
static host serves and the CLI is pointed at.

Run: python scripts/build-template-registry.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "templates"
OUT = SRC / "r"


def build_item(item_path: Path) -> dict:
    item = json.loads(item_path.read_text(encoding="utf-8"))
    built_files = []
    for entry in item.get("files", []):
        # `path` is repo-relative, exactly as the source form declares it, so a
        # mistyped path fails here rather than at install time on someone
        # else's machine.
        src = ROOT / entry["path"]
        if not src.is_file():
            raise SystemExit(f"{item_path}: files[].path does not exist: {entry['path']}")
        built = dict(entry)
        built["content"] = src.read_text(encoding="utf-8")
        built_files.append(built)
    item["files"] = built_files
    return item


def main() -> int:
    if not SRC.is_dir():
        raise SystemExit(f"no templates/ directory at {SRC}")

    OUT.mkdir(parents=True, exist_ok=True)
    items = []
    for item_path in sorted(SRC.glob("*/registry-item.json")):
        item = build_item(item_path)
        (OUT / f"{item['name']}.json").write_text(
            json.dumps(item, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        # The index carries metadata only. A consumer browsing the registry
        # should not have to download every page's markup to read seven titles;
        # it follows the name to the item file when it wants the content.
        items.append({k: v for k, v in item.items() if k != "files"})
        print(f"  {item['name']}.json")

    index = {
        "$schema": "https://ui.shadcn.com/schema/registry.json",
        "name": "aetox",
        "homepage": "https://github.com/Mikedev115/Aetox",
        "items": items,
    }
    (OUT / "index.json").write_text(
        json.dumps(index, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"  index.json ({len(items)} items)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
