// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1, arg2) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2);
}

export function AnswerUserQuestion(arg1) {
  return window['go']['main']['App']['AnswerUserQuestion'](arg1);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function BrowserBack(arg1) {
  return window['go']['main']['App']['BrowserBack'](arg1);
}

export function BrowserClickRef(arg1, arg2) {
  return window['go']['main']['App']['BrowserClickRef'](arg1, arg2);
}

export function BrowserClose(arg1) {
  return window['go']['main']['App']['BrowserClose'](arg1);
}

export function BrowserForward(arg1) {
  return window['go']['main']['App']['BrowserForward'](arg1);
}

export function BrowserGetText(arg1) {
  return window['go']['main']['App']['BrowserGetText'](arg1);
}

export function BrowserNavigate(arg1, arg2) {
  return window['go']['main']['App']['BrowserNavigate'](arg1, arg2);
}

export function BrowserOpen(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['BrowserOpen'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function BrowserOpenDevTools(arg1) {
  return window['go']['main']['App']['BrowserOpenDevTools'](arg1);
}

export function BrowserReload(arg1) {
  return window['go']['main']['App']['BrowserReload'](arg1);
}

export function BrowserSetBounds(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BrowserSetBounds'](arg1, arg2, arg3, arg4, arg5);
}

export function BrowserSetVisible(arg1, arg2) {
  return window['go']['main']['App']['BrowserSetVisible'](arg1, arg2);
}

export function BrowserSetZoom(arg1, arg2) {
  return window['go']['main']['App']['BrowserSetZoom'](arg1, arg2);
}

export function BrowserTypeRef(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowserTypeRef'](arg1, arg2, arg3, arg4);
}

export function CancelSignIn(arg1) {
  return window['go']['main']['App']['CancelSignIn'](arg1);
}

export function CancelTurn() {
  return window['go']['main']['App']['CancelTurn']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearProjectFocus() {
  return window['go']['main']['App']['ClearProjectFocus']();
}

export function CloseAllBrowserTabs() {
  return window['go']['main']['App']['CloseAllBrowserTabs']();
}

export function CommandHistory() {
  return window['go']['main']['App']['CommandHistory']();
}

export function CompleteSignIn(arg1, arg2) {
  return window['go']['main']['App']['CompleteSignIn'](arg1, arg2);
}

export function CurrentSessionID() {
  return window['go']['main']['App']['CurrentSessionID']();
}

export function DeleteIdentityFile(arg1) {
  return window['go']['main']['App']['DeleteIdentityFile'](arg1);
}

export function DeletePromptPreset(arg1) {
  return window['go']['main']['App']['DeletePromptPreset'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSubagentProfile(arg1) {
  return window['go']['main']['App']['DeleteSubagentProfile'](arg1);
}

export function DismissTaskChip(arg1) {
  return window['go']['main']['App']['DismissTaskChip'](arg1);
}

export function EnabledProviders() {
  return window['go']['main']['App']['EnabledProviders']();
}

export function GetContextBreakdown() {
  return window['go']['main']['App']['GetContextBreakdown']();
}

export function GetModelInfo() {
  return window['go']['main']['App']['GetModelInfo']();
}

export function GetProjectStatus() {
  return window['go']['main']['App']['GetProjectStatus']();
}

export function GitChangedFiles() {
  return window['go']['main']['App']['GitChangedFiles']();
}

export function GuideTopics() {
  return window['go']['main']['App']['GuideTopics']();
}

export function HasAPIKey(arg1) {
  return window['go']['main']['App']['HasAPIKey'](arg1);
}

export function ImportSignIn(arg1) {
  return window['go']['main']['App']['ImportSignIn'](arg1);
}

export function ImportableSignIns() {
  return window['go']['main']['App']['ImportableSignIns']();
}

export function InstallSkillFromGitHub(arg1) {
  return window['go']['main']['App']['InstallSkillFromGitHub'](arg1);
}

export function InstallSkillFromZip() {
  return window['go']['main']['App']['InstallSkillFromZip']();
}

export function Interject(arg1) {
  return window['go']['main']['App']['Interject'](arg1);
}

export function ListAllSessions() {
  return window['go']['main']['App']['ListAllSessions']();
}

export function ListExternalSkills() {
  return window['go']['main']['App']['ListExternalSkills']();
}

export function ListIdentityFiles() {
  return window['go']['main']['App']['ListIdentityFiles']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListModelsForProvider(arg1) {
  return window['go']['main']['App']['ListModelsForProvider'](arg1);
}

export function ListPromptPresets() {
  return window['go']['main']['App']['ListPromptPresets']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListSpeechModels() {
  return window['go']['main']['App']['ListSpeechModels']();
}

export function ListSubagentProfiles() {
  return window['go']['main']['App']['ListSubagentProfiles']();
}

export function ListTaskChips() {
  return window['go']['main']['App']['ListTaskChips']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function LoadSessionAnyProject(arg1) {
  return window['go']['main']['App']['LoadSessionAnyProject'](arg1);
}

export function MCPConfigPath() {
  return window['go']['main']['App']['MCPConfigPath']();
}

export function ModelStatus() {
  return window['go']['main']['App']['ModelStatus']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function OpenMCPFolder() {
  return window['go']['main']['App']['OpenMCPFolder']();
}

export function OpenProjectFolder() {
  return window['go']['main']['App']['OpenProjectFolder']();
}

export function OpenProjectPath(arg1) {
  return window['go']['main']['App']['OpenProjectPath'](arg1);
}

export function OpenPromptsFolder() {
  return window['go']['main']['App']['OpenPromptsFolder']();
}

export function OpenSkillsFolder() {
  return window['go']['main']['App']['OpenSkillsFolder']();
}

export function OpenSpeechModelDir(arg1) {
  return window['go']['main']['App']['OpenSpeechModelDir'](arg1);
}

export function OpenSubagentsFolder() {
  return window['go']['main']['App']['OpenSubagentsFolder']();
}

export function PendingUndo() {
  return window['go']['main']['App']['PendingUndo']();
}

export function PickAttachment() {
  return window['go']['main']['App']['PickAttachment']();
}

export function PickAttachmentImage() {
  return window['go']['main']['App']['PickAttachmentImage']();
}

export function PickPresetImage(arg1) {
  return window['go']['main']['App']['PickPresetImage'](arg1);
}

export function ProjectTree() {
  return window['go']['main']['App']['ProjectTree']();
}

export function ProviderBaseURL(arg1) {
  return window['go']['main']['App']['ProviderBaseURL'](arg1);
}

export function ProviderBaseURLIsCustom(arg1) {
  return window['go']['main']['App']['ProviderBaseURLIsCustom'](arg1);
}

export function ProviderWireFormats(arg1) {
  return window['go']['main']['App']['ProviderWireFormats'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadIdentityFile(arg1) {
  return window['go']['main']['App']['ReadIdentityFile'](arg1);
}

export function ReadImageDataURL(arg1) {
  return window['go']['main']['App']['ReadImageDataURL'](arg1);
}

export function ReadSubagentProfile(arg1) {
  return window['go']['main']['App']['ReadSubagentProfile'](arg1);
}

export function RecentProjects() {
  return window['go']['main']['App']['RecentProjects']();
}

export function RefreshSkills() {
  return window['go']['main']['App']['RefreshSkills']();
}

export function RegenerateReply(arg1) {
  return window['go']['main']['App']['RegenerateReply'](arg1);
}

export function RelativizePath(arg1) {
  return window['go']['main']['App']['RelativizePath'](arg1);
}

export function RemoveExternalSkill(arg1) {
  return window['go']['main']['App']['RemoveExternalSkill'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RemovePresetImage(arg1) {
  return window['go']['main']['App']['RemovePresetImage'](arg1);
}

export function RequiresAPIKey(arg1) {
  return window['go']['main']['App']['RequiresAPIKey'](arg1);
}

export function ResendEdited(arg1, arg2) {
  return window['go']['main']['App']['ResendEdited'](arg1, arg2);
}

export function RetryActiveProvider() {
  return window['go']['main']['App']['RetryActiveProvider']();
}

export function RetryFailedTurn(arg1) {
  return window['go']['main']['App']['RetryFailedTurn'](arg1);
}

export function RevealSpeechModel(arg1) {
  return window['go']['main']['App']['RevealSpeechModel'](arg1);
}

export function RunChatCommand(arg1) {
  return window['go']['main']['App']['RunChatCommand'](arg1);
}

export function SaveChatFile(arg1) {
  return window['go']['main']['App']['SaveChatFile'](arg1);
}

export function SaveChatImage(arg1) {
  return window['go']['main']['App']['SaveChatImage'](arg1);
}

export function SaveIdentityFile(arg1, arg2) {
  return window['go']['main']['App']['SaveIdentityFile'](arg1, arg2);
}

export function SaveMCPServer(arg1, arg2) {
  return window['go']['main']['App']['SaveMCPServer'](arg1, arg2);
}

export function SavePromptPreset(arg1, arg2) {
  return window['go']['main']['App']['SavePromptPreset'](arg1, arg2);
}

export function SaveSubagentProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveSubagentProfile'](arg1, arg2);
}

export function SearchAllSessions(arg1) {
  return window['go']['main']['App']['SearchAllSessions'](arg1);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function SetProviderBaseURL(arg1, arg2) {
  return window['go']['main']['App']['SetProviderBaseURL'](arg1, arg2);
}

export function SetProviderEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetProviderEnabled'](arg1, arg2);
}

export function SetProviderWireFormat(arg1) {
  return window['go']['main']['App']['SetProviderWireFormat'](arg1);
}

export function SetSpeechModel(arg1) {
  return window['go']['main']['App']['SetSpeechModel'](arg1);
}

export function SetSubagentModel(arg1, arg2) {
  return window['go']['main']['App']['SetSubagentModel'](arg1, arg2);
}

export function SetUILocale(arg1) {
  return window['go']['main']['App']['SetUILocale'](arg1);
}

export function SetUserName(arg1) {
  return window['go']['main']['App']['SetUserName'](arg1);
}

export function SignInMethods() {
  return window['go']['main']['App']['SignInMethods']();
}

export function SignInStatus(arg1) {
  return window['go']['main']['App']['SignInStatus'](arg1);
}

export function SignOut(arg1) {
  return window['go']['main']['App']['SignOut'](arg1);
}

export function SignedInProviders() {
  return window['go']['main']['App']['SignedInProviders']();
}

export function SkillScanIssues() {
  return window['go']['main']['App']['SkillScanIssues']();
}

export function SkillsDir() {
  return window['go']['main']['App']['SkillsDir']();
}

export function SpeechModelDirs() {
  return window['go']['main']['App']['SpeechModelDirs']();
}

export function SpeechStatus() {
  return window['go']['main']['App']['SpeechStatus']();
}

export function StartSignIn(arg1) {
  return window['go']['main']['App']['StartSignIn'](arg1);
}

export function SupportedProviders() {
  return window['go']['main']['App']['SupportedProviders']();
}

export function SupportedThinkLevels() {
  return window['go']['main']['App']['SupportedThinkLevels']();
}

export function SwitchApprovalMode(arg1) {
  return window['go']['main']['App']['SwitchApprovalMode'](arg1);
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function SwitchProvider(arg1) {
  return window['go']['main']['App']['SwitchProvider'](arg1);
}

export function SwitchThinkLevel(arg1) {
  return window['go']['main']['App']['SwitchThinkLevel'](arg1);
}

export function SwitchVariant(arg1) {
  return window['go']['main']['App']['SwitchVariant'](arg1);
}

export function TerminalClose(arg1) {
  return window['go']['main']['App']['TerminalClose'](arg1);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalShells() {
  return window['go']['main']['App']['TerminalShells']();
}

export function TerminalStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalStart'](arg1, arg2, arg3);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['main']['App']['TerminalWrite'](arg1, arg2);
}

export function TestMCPServer(arg1) {
  return window['go']['main']['App']['TestMCPServer'](arg1);
}

export function TestProviderConnection(arg1, arg2) {
  return window['go']['main']['App']['TestProviderConnection'](arg1, arg2);
}

export function ToggleMCPServer(arg1, arg2) {
  return window['go']['main']['App']['ToggleMCPServer'](arg1, arg2);
}

export function ToolCounts() {
  return window['go']['main']['App']['ToolCounts']();
}

export function UndoLastTurn() {
  return window['go']['main']['App']['UndoLastTurn']();
}

export function UsageStats() {
  return window['go']['main']['App']['UsageStats']();
}

export function UserName() {
  return window['go']['main']['App']['UserName']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
