// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1, arg2) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2);
}

export function BrowserBack(arg1) {
  return window['go']['main']['App']['BrowserBack'](arg1);
}

export function BrowserClickRef(arg1, arg2) {
  return window['go']['main']['App']['BrowserClickRef'](arg1, arg2);
}

export function BrowserClose(arg1) {
  return window['go']['main']['App']['BrowserClose'](arg1);
}

export function BrowserForward(arg1) {
  return window['go']['main']['App']['BrowserForward'](arg1);
}

export function BrowserGetText(arg1) {
  return window['go']['main']['App']['BrowserGetText'](arg1);
}

export function BrowserNavigate(arg1, arg2) {
  return window['go']['main']['App']['BrowserNavigate'](arg1, arg2);
}

export function BrowserOpen(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['BrowserOpen'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function BrowserReload(arg1) {
  return window['go']['main']['App']['BrowserReload'](arg1);
}

export function BrowserSetBounds(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BrowserSetBounds'](arg1, arg2, arg3, arg4, arg5);
}

export function BrowserSetVisible(arg1, arg2) {
  return window['go']['main']['App']['BrowserSetVisible'](arg1, arg2);
}

export function BrowserTypeRef(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowserTypeRef'](arg1, arg2, arg3, arg4);
}

export function CancelTurn() {
  return window['go']['main']['App']['CancelTurn']();
}

export function ClearProjectFocus() {
  return window['go']['main']['App']['ClearProjectFocus']();
}

export function CloseAllBrowserTabs() {
  return window['go']['main']['App']['CloseAllBrowserTabs']();
}

export function CommandHistory() {
  return window['go']['main']['App']['CommandHistory']();
}

export function CurrentSessionID() {
  return window['go']['main']['App']['CurrentSessionID']();
}

export function DeleteIdentityFile(arg1) {
  return window['go']['main']['App']['DeleteIdentityFile'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetContextBreakdown() {
  return window['go']['main']['App']['GetContextBreakdown']();
}

export function GetModelInfo() {
  return window['go']['main']['App']['GetModelInfo']();
}

export function GetProjectStatus() {
  return window['go']['main']['App']['GetProjectStatus']();
}

export function GitChangedFiles() {
  return window['go']['main']['App']['GitChangedFiles']();
}

export function HasAPIKey(arg1) {
  return window['go']['main']['App']['HasAPIKey'](arg1);
}

export function ListAllSessions() {
  return window['go']['main']['App']['ListAllSessions']();
}

export function ListIdentityFiles() {
  return window['go']['main']['App']['ListIdentityFiles']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListModelsForProvider(arg1) {
  return window['go']['main']['App']['ListModelsForProvider'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function LoadSessionAnyProject(arg1) {
  return window['go']['main']['App']['LoadSessionAnyProject'](arg1);
}

export function ModelStatus() {
  return window['go']['main']['App']['ModelStatus']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function OpenProjectFolder() {
  return window['go']['main']['App']['OpenProjectFolder']();
}

export function OpenProjectPath(arg1) {
  return window['go']['main']['App']['OpenProjectPath'](arg1);
}

export function PickAttachmentImage() {
  return window['go']['main']['App']['PickAttachmentImage']();
}

export function ProjectTree() {
  return window['go']['main']['App']['ProjectTree']();
}

export function ProviderBaseURL(arg1) {
  return window['go']['main']['App']['ProviderBaseURL'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadIdentityFile(arg1) {
  return window['go']['main']['App']['ReadIdentityFile'](arg1);
}

export function ReadImageDataURL(arg1) {
  return window['go']['main']['App']['ReadImageDataURL'](arg1);
}

export function RecentProjects() {
  return window['go']['main']['App']['RecentProjects']();
}

export function RelativizePath(arg1) {
  return window['go']['main']['App']['RelativizePath'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RequiresAPIKey(arg1) {
  return window['go']['main']['App']['RequiresAPIKey'](arg1);
}

export function SaveChatImage(arg1) {
  return window['go']['main']['App']['SaveChatImage'](arg1);
}

export function SaveIdentityFile(arg1, arg2) {
  return window['go']['main']['App']['SaveIdentityFile'](arg1, arg2);
}

export function SaveMCPServer(arg1, arg2) {
  return window['go']['main']['App']['SaveMCPServer'](arg1, arg2);
}

export function SearchAllSessions(arg1) {
  return window['go']['main']['App']['SearchAllSessions'](arg1);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function SupportedProviders() {
  return window['go']['main']['App']['SupportedProviders']();
}

export function SupportedThinkLevels() {
  return window['go']['main']['App']['SupportedThinkLevels']();
}

export function SwitchApprovalMode(arg1) {
  return window['go']['main']['App']['SwitchApprovalMode'](arg1);
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function SwitchProvider(arg1) {
  return window['go']['main']['App']['SwitchProvider'](arg1);
}

export function SwitchThinkLevel(arg1) {
  return window['go']['main']['App']['SwitchThinkLevel'](arg1);
}

export function TerminalClose(arg1) {
  return window['go']['main']['App']['TerminalClose'](arg1);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalShells() {
  return window['go']['main']['App']['TerminalShells']();
}

export function TerminalStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalStart'](arg1, arg2, arg3);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['main']['App']['TerminalWrite'](arg1, arg2);
}

export function TestMCPServer(arg1) {
  return window['go']['main']['App']['TestMCPServer'](arg1);
}

export function ToggleMCPServer(arg1, arg2) {
  return window['go']['main']['App']['ToggleMCPServer'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
