// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModelInfo() {
  return window['go']['main']['App']['GetModelInfo']();
}

export function GetProjectStatus() {
  return window['go']['main']['App']['GetProjectStatus']();
}

export function HasAPIKey(arg1) {
  return window['go']['main']['App']['HasAPIKey'](arg1);
}

export function ListModelsForProvider(arg1) {
  return window['go']['main']['App']['ListModelsForProvider'](arg1);
}

export function ModelStatus() {
  return window['go']['main']['App']['ModelStatus']();
}

export function OpenProjectFolder() {
  return window['go']['main']['App']['OpenProjectFolder']();
}

export function RequiresAPIKey(arg1) {
  return window['go']['main']['App']['RequiresAPIKey'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function SupportedProviders() {
  return window['go']['main']['App']['SupportedProviders']();
}

export function SupportedThinkLevels() {
  return window['go']['main']['App']['SupportedThinkLevels']();
}

export function SwitchApprovalMode(arg1) {
  return window['go']['main']['App']['SwitchApprovalMode'](arg1);
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function SwitchProvider(arg1) {
  return window['go']['main']['App']['SwitchProvider'](arg1);
}

export function SwitchThinkLevel(arg1) {
  return window['go']['main']['App']['SwitchThinkLevel'](arg1);
}
