// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {engine} from '../models';
import {subagent} from '../models';
import {context} from '../models';
import {capability} from '../models';
import {update} from '../models';
import {connect} from '../models';
import {cliagent} from '../models';
import {model} from '../models';
import {skill} from '../models';
import {mode} from '../models';
import {command} from '../models';
import {oauth} from '../models';
import {machine} from '../models';
import {github} from '../models';
import {ooxml} from '../models';
import {config} from '../models';

export function APIKeyHint(arg1:string):Promise<string>;

export function AcceptsAPIKey(arg1:string):Promise<boolean>;

export function AccountRefresh():Promise<main.AccountState>;

export function AccountSignOut():Promise<void>;

export function AccountStatus():Promise<main.AccountState>;

export function ActiveModelFor(arg1:string):Promise<string|string>;

export function AddCustomProvider(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function AddCustomProviderRow(arg1:string,arg2:string):Promise<string>;

export function AddLearnedEntry(arg1:string,arg2:string):Promise<void>;

export function AddMCPServer(arg1:string,arg2:Array<string>):Promise<void>;

export function AddSpaceContext(arg1:string):Promise<Array<string>>;

export function AddSpaceContextFiles(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function AddStudioLibrary():Promise<boolean>;

export function AddStudioLibraryAt(arg1:string):Promise<boolean>;

export function AddWorkspaceFolder():Promise<Array<engine.WorkspaceFolder>>;

export function AddWorkspaceFolderAt(arg1:string):Promise<Array<engine.WorkspaceFolder>>;

export function AdoptMemoryScope(arg1:string,arg2:string):Promise<void>;

export function AgentBlocked(arg1:string):Promise<boolean>;

export function AgentGate(arg1:string):Promise<engine.AgentGate>;

export function AgentHomePath(arg1:string):Promise<string>;

export function AgentNeeds(arg1:string):Promise<Array<subagent.Requirement>>;

export function AgentPackageBytes(arg1:string):Promise<engine.ExportFile>;

export function AgentSkills(arg1:string):Promise<Array<engine.AgentSkillInfo>>;

export function AgentSkillsFolderPath(arg1:string):Promise<string>;

export function AgentsFolderPath():Promise<string>;

export function AllowComputerApp(arg1:string):Promise<void>;

export function AnswerUserQuestion(arg1:string,arg2:string):Promise<void>;

export function AnyTurnRunning():Promise<boolean>;

export function AppCredit():Promise<string>;

export function AppVersion():Promise<string>;

export function ApplyMemoryLines(arg1:string,arg2:Array<string>):Promise<void>;

export function ApprovePendingChange(arg1:number):Promise<void>;

export function ApprovePendingChangeTo(arg1:number,arg2:string):Promise<void>;

export function ArtifactPath(arg1:string):Promise<string>;

export function ArtifactPreview(arg1:string):Promise<engine.ArtifactPreview>;

export function AttentionSignal():Promise<Array<engine.BusyLayer>>;

export function BackgroundRuns():Promise<Array<engine.BackgroundRun>>;

export function BackgroundTasks():Promise<Array<engine.BackgroundTask>>;

export function BrowseFolder():Promise<string>;

export function BrowseFolderAt(arg1:string):Promise<string>;

export function BrowseForComputerApp():Promise<string>;

export function BrowseRoot():Promise<string>;

export function BrowserBack(arg1:string):Promise<void>;

export function BrowserCaptureFullPNG(arg1:context.Context,arg2:string):Promise<string>;

export function BrowserCapturePNG(arg1:string):Promise<string>;

export function BrowserClickRef(arg1:string,arg2:number):Promise<void>;

export function BrowserClose(arg1:string):Promise<void>;

export function BrowserCloseForTeardown(arg1:string):Promise<void>;

export function BrowserDetach(arg1:string):Promise<void>;

export function BrowserDevices():Promise<Array<main.DeviceProfile>>;

export function BrowserForward(arg1:string):Promise<void>;

export function BrowserGetText(arg1:string):Promise<string>;

export function BrowserNavigate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BrowserOpen(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number):Promise<void>;

export function BrowserOpenDevTools(arg1:string):Promise<void>;

export function BrowserReload(arg1:string):Promise<void>;

export function BrowserSetBounds(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function BrowserSetDevice(arg1:string,arg2:string):Promise<void>;

export function BrowserSetScreenShape(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function BrowserSetVisible(arg1:string,arg2:boolean):Promise<void>;

export function BrowserSetZoom(arg1:string,arg2:number):Promise<void>;

export function BrowserStartPick(arg1:string,arg2:string):Promise<void>;

export function BrowserStopPick(arg1:string):Promise<void>;

export function BrowserTypeRef(arg1:string,arg2:number,arg3:string,arg4:boolean):Promise<void>;

export function BusySignal():Promise<Array<engine.BusyLayer>>;

export function CancelAccountSignIn():Promise<void>;

export function CancelMCPSignIn(arg1:string):Promise<void>;

export function CancelPendingModel():Promise<engine.ModelInfo>;

export function CancelSignIn(arg1:string):Promise<void>;

export function CancelStudioScan():Promise<void>;

export function CancelTurn():Promise<void>;

export function CapabilitiesInstalling():Promise<boolean>;

export function CapabilityForServer(arg1:string):Promise<string>;

export function CapabilityStatuses():Promise<Array<capability.Status>>;

export function CatalogModelChoices(arg1:string):Promise<Array<string>>;

export function ChairStarters(arg1:string,arg2:string):Promise<subagent.StarterSet>;

export function ChairStartersFile(arg1:string):Promise<string>;

export function CheckConnectionServer(arg1:string):Promise<boolean>;

export function CheckForUpdate():Promise<update.Status>;

export function ClearProjectFocus():Promise<engine.ProjectStatus>;

export function CloseAllBrowserTabs():Promise<void>;

export function CloseCompanionWindow():Promise<void>;

export function CommandHistory():Promise<Array<string>>;

export function CompanionSpriteKeys(arg1:string):Promise<Array<string>>;

export function CompanionSprites(arg1:string,arg2:Array<main.CompanionFrame>):Promise<void>;

export function CompleteAccountSignIn():Promise<main.AccountState>;

export function CompleteMCPSignIn(arg1:string):Promise<void>;

export function CompleteSignIn(arg1:string,arg2:string):Promise<engine.ModelInfo>;

export function CompressArtifacts(arg1:Array<string>):Promise<engine.CompressReport>;

export function ComputerControlChanged():Promise<void>;

export function ComputerControlOn():Promise<boolean>;

export function ConnectAccount(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<connect.Account>;

export function ConnectRemote(arg1:string):Promise<void>;

export function Connections():Promise<Array<connect.Status>>;

export function ConsolidateMemory(arg1:string):Promise<engine.MemoryConsolidation>;

export function CopySkillToAgent(arg1:string,arg2:string):Promise<void>;

export function CreatePullRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<engine.PRCreated>;

export function CreateSpace(arg1:string):Promise<engine.Space>;

export function CurrentSessionID():Promise<string>;

export function CurrentShell():Promise<engine.ShellOption>;

export function CurrentSpace():Promise<string>;

export function CustomProviders():Promise<Array<engine.CustomProviderRow>>;

export function DeckCaptureDrawing(arg1:string,arg2:number,arg3:string):Promise<string>;

export function DeckExportFiles(arg1:string,arg2:string):Promise<engine.DeckExport>;

export function DeckFormats():Promise<Array<engine.DeckFormat>>;

export function DeckPickScript(arg1:string,arg2:string):Promise<string>;

export function DeckStopPickScript():Promise<string>;

export function DelegateSwitches(arg1:string):Promise<engine.DelegateSettings>;

export function DeleteArtifact(arg1:string):Promise<void>;

export function DeleteDeck(arg1:string):Promise<void>;

export function DeleteIdentityFile(arg1:string):Promise<void>;

export function DeletePromptPreset(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSpace(arg1:string):Promise<void>;

export function DeleteSubagentProfile(arg1:string):Promise<void>;

export function DeleteTeam(arg1:string):Promise<void>;

export function DisconnectAccount(arg1:string):Promise<void>;

export function DisconnectRemote():Promise<void>;

export function DismissRecurringRequest(arg1:string,arg2:string):Promise<void>;

export function DismissTaskChip(arg1:string):Promise<void>;

export function EnabledProviders():Promise<Array<string>>;

export function EngineStatus():Promise<main.EngineStatus>;

export function EnginesFor(arg1:string,arg2:string):Promise<Array<connect.Status>>;

export function ExportAgentPackage(arg1:string):Promise<string>;

export function ExportDeck(arg1:string,arg2:string):Promise<string>;

export function ExportSession(arg1:string,arg2:string):Promise<string>;

export function ExternalEngineStatus(arg1:string):Promise<cliagent.Status>;

export function FetchAgentBrief(arg1:string):Promise<string>;

export function FileStillThere(arg1:string):Promise<string>;

export function ForgetMemoryScope(arg1:string):Promise<void>;

export function ForgetProject(arg1:string):Promise<engine.ProjectStatus>;

export function ForgetRemoteHost(arg1:string):Promise<void>;

export function GetContextBreakdown():Promise<engine.ContextBreakdown>;

export function GetModelInfo():Promise<engine.ModelInfo>;

export function GetProjectStatus():Promise<engine.ProjectStatus>;

export function GetRepoMapGraph(arg1:number):Promise<engine.RepoMapGraph>;

export function GitBranches():Promise<Array<engine.GitBranch>>;

export function GitChangedFiles():Promise<Array<engine.ChangedFile>>;

export function GitCommitChanges(arg1:string):Promise<Array<engine.GitFileChange>>;

export function GitCommitFileDiff(arg1:string,arg2:string):Promise<string>;

export function GitCommitFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function GitCreateBranch(arg1:string):Promise<string>;

export function GitFileDiff(arg1:string):Promise<string>;

export function GitLog(arg1:string,arg2:number):Promise<engine.GitLogPage>;

export function GitSplitCancel():Promise<void>;

export function GitSuggestCommitMessage(arg1:Array<string>):Promise<string>;

export function GitSuggestSplitCommits():Promise<Array<engine.GitCommitGroup>>;

export function GitSwitchBranch(arg1:string):Promise<string>;

export function GitWorkingTree():Promise<Array<engine.GitFileChange>>;

export function GrantedComputerApps():Promise<Array<string>>;

export function GuideTopics():Promise<Array<model.GuideTopic>>;

export function HandedOverFile(arg1:string):Promise<string>;

export function HasAPIKey(arg1:string):Promise<boolean>;

export function HistoryFault():Promise<engine.StoreFault>;

export function HomeDir():Promise<string>;

export function ImageStatus():Promise<string>;

export function ImportSession():Promise<string>;

export function ImportSessionFrom(arg1:string):Promise<string>;

export function ImportSignIn(arg1:string):Promise<engine.ModelInfo>;

export function ImportableSignIns():Promise<Array<string>>;

export function InstallCapabilities(arg1:Array<string>):Promise<boolean>;

export function InstallSkillFromGitHub(arg1:string):Promise<string>;

export function InstallSkillFromZip():Promise<string>;

export function InstallSkillsFromZipAt(arg1:string):Promise<string>;

export function InstallVoiceEngine(arg1:string,arg2:string):Promise<void>;

export function Interject(arg1:string):Promise<void>;

export function LearnedEntries(arg1:string):Promise<Array<string>>;

export function LearnedMemory(arg1:string):Promise<string>;

export function LearnedScopeInfos():Promise<Array<engine.MemoryScopeInfo>>;

export function LearnedScopes():Promise<Array<string>>;

export function LearningEnabled():Promise<boolean>;

export function ListAllSessions():Promise<Array<engine.SessionMeta>>;

export function ListArtifacts():Promise<Array<engine.Artifact>>;

export function ListArtifactsForSession(arg1:string):Promise<engine.ArtifactPage>;

export function ListArtifactsIn(arg1:string):Promise<engine.ArtifactPage>;

export function ListChairs():Promise<Array<engine.Chair>>;

export function ListDecidedChanges(arg1:number):Promise<Array<engine.PendingChange>>;

export function ListDecidedIssues(arg1:number):Promise<Array<engine.PendingChange>>;

export function ListDecidedSkillProposals(arg1:number):Promise<Array<engine.PendingChange>>;

export function ListDecks():Promise<Array<engine.Deck>>;

export function ListDecksIn(arg1:string):Promise<engine.DeckPage>;

export function ListDir(arg1:string):Promise<engine.DirListing>;

export function ListExternalSkills():Promise<Array<skill.DiscoveredSkill>>;

export function ListIdentityFiles():Promise<Array<engine.IdentityFile>>;

export function ListImageEngines():Promise<Array<engine.VoiceEngineInfo>>;

export function ListMCPServers():Promise<Array<engine.MCPServerInfo>>;

export function ListModelsForProvider(arg1:string):Promise<Array<string>>;

export function ListModes():Promise<Array<mode.Mode>>;

export function ListPendingChanges():Promise<Array<engine.PendingChange>>;

export function ListPromptPresets():Promise<Array<command.Preset>>;

export function ListReceivedJobs(arg1:number):Promise<Array<engine.ReceivedJob>>;

export function ListRecurringRequests():Promise<Array<engine.RecurringRequest>>;

export function ListSessions():Promise<Array<engine.SessionMeta>>;

export function ListSessionsAt(arg1:string):Promise<Array<engine.SessionMeta>>;

export function ListSessionsForDoor(arg1:engine.DeskFilter):Promise<Array<engine.SessionMeta>>;

export function ListSkillProposals():Promise<Array<engine.PendingChange>>;

export function ListSkills():Promise<Array<engine.SkillInfo>>;

export function ListSpeechEngines():Promise<Array<engine.VoiceEngineInfo>>;

export function ListSpeechModels():Promise<Array<engine.SpeechModelInfo>>;

export function ListSubagentProfiles():Promise<Array<subagent.Profile>>;

export function ListSystemIssues():Promise<Array<engine.PendingChange>>;

export function ListTTSEngines():Promise<Array<engine.VoiceEngineInfo>>;

export function ListTTSVoices():Promise<Array<main.TTSVoiceInfo>>;

export function ListTaskChips():Promise<Array<engine.TaskChip>>;

export function ListTeams(arg1:string):Promise<Array<engine.TeamCard>>;

export function ListTools():Promise<Array<engine.SkillInfo>>;

export function LoadSession(arg1:string):Promise<Array<engine.SessionMessage>>;

export function LoadSessionAnyProject(arg1:string):Promise<Array<engine.SessionMessage>>;

export function MCPConfigPath():Promise<string>;

export function MCPFolderPath():Promise<string>;

export function MCPSignInStatus(arg1:string):Promise<oauth.Status>;

export function MachineInfo():Promise<machine.Info>;

export function MarkIssueReported(arg1:number):Promise<void>;

export function MarkVideoCheckSeen():Promise<void>;

export function MemoryFolderPath():Promise<string>;

export function MobileRemoteQR():Promise<string>;

export function MobileRemoteStatus():Promise<engine.RemoteStatus>;

export function ModelPriceSource():Promise<engine.PriceSource>;

export function ModelStatus():Promise<string>;

export function MoveLearnedEntry(arg1:string,arg2:string,arg3:number):Promise<void>;

export function NewChairSession(arg1:string):Promise<string>;

export function NewChairSessionAt(arg1:string,arg2:string,arg3:string):Promise<string>;

export function NewSession():Promise<string>;

export function NewSessionAt(arg1:string):Promise<string>;

export function NewSessionInSpace(arg1:string):Promise<string>;

export function NewTeamSession(arg1:string,arg2:string):Promise<string>;

export function NoteProviderQuotas(arg1:string,arg2:Array<model.Quota>):Promise<void>;

export function OpenAgentHome(arg1:string):Promise<void>;

export function OpenAgentSkillsFolder(arg1:string):Promise<void>;

export function OpenAgentsFolder():Promise<void>;

export function OpenArtifact(arg1:string):Promise<void>;

export function OpenCompanionWindow(arg1:number,arg2:number,arg3:number):Promise<boolean>;

export function OpenComputerApps():Promise<Array<main.ComputerAppRow>>;

export function OpenExport(arg1:string):Promise<void>;

export function OpenFileExternally(arg1:string):Promise<void>;

export function OpenMCPFolder():Promise<void>;

export function OpenMemoryFolder():Promise<void>;

export function OpenProjectFolder():Promise<engine.ProjectStatus>;

export function OpenProjectPath(arg1:string):Promise<engine.ProjectStatus>;

export function OpenPromptsFolder():Promise<void>;

export function OpenSkillsFolder():Promise<void>;

export function OpenSpaceFolder(arg1:string):Promise<void>;

export function OpenSpeechModelDir(arg1:string):Promise<void>;

export function OpenSubagentsFolder():Promise<void>;

export function OpenTeamsFolder():Promise<void>;

export function PageMarksOn():Promise<boolean>;

export function PairedDevices():Promise<Array<engine.RemoteDevice>>;

export function PausePlanRun(arg1:string):Promise<void>;

export function PendingChangeByID(arg1:number):Promise<engine.PendingChange>;

export function PendingIssueCount():Promise<number>;

export function PendingLearnedCount():Promise<number>;

export function PendingRestore(arg1:string):Promise<Array<string>>;

export function PendingSkillTuneCount():Promise<number>;

export function PendingUndo():Promise<Array<string>>;

export function PickAgentBrief():Promise<string>;

export function PickAttachmentImage():Promise<string>;

export function PickAttachments(arg1:string):Promise<Array<string>>;

export function PickPresetImage(arg1:string):Promise<string>;

export function PictureBytes(arg1:string):Promise<engine.ExportFile>;

export function PlacementTargets():Promise<Array<engine.PlacementTarget>>;

export function PlanRunning(arg1:string):Promise<boolean>;

export function PrepareToClose():Promise<void>;

export function PreparedReplyOn():Promise<boolean>;

export function PriceModels(arg1:string,arg2:Array<string>):Promise<Array<engine.ModelListing>>;

export function ProgramIcon(arg1:string):Promise<string>;

export function ProjectFilePath(arg1:string):Promise<string>;

export function ProjectTree():Promise<Array<engine.TreeNode>>;

export function PromptsFolderPath():Promise<string>;

export function ProviderAPIKeyURL(arg1:string):Promise<string>;

export function ProviderAccountFor(arg1:string):Promise<engine.ProviderAccount>;

export function ProviderBaseURL(arg1:string):Promise<string>;

export function ProviderBaseURLIsCustom(arg1:string):Promise<boolean>;

export function ProviderCredentialChanged(arg1:string):Promise<engine.ModelInfo>;

export function ProviderQuotas(arg1:string):Promise<Array<model.Quota>|boolean>;

export function ProviderReady(arg1:string):Promise<boolean>;

export function ProviderWireFormats(arg1:string):Promise<Array<string>>;

export function PullRequestChecks(arg1:string):Promise<Array<github.CheckRun>>;

export function PullRequestFiles(arg1:number):Promise<Array<github.PRFile>>;

export function PullRequests():Promise<engine.PRRoom>;

export function PullRequestsState(arg1:string):Promise<engine.PRRoom>;

export function RateTurn(arg1:number,arg2:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadIdentityFile(arg1:string):Promise<string>;

export function ReadImageDataURL(arg1:string):Promise<string>;

export function ReadSubagentProfile(arg1:string):Promise<string>;

export function ReadWorkbook(arg1:string):Promise<ooxml.WorkbookPreview>;

export function ReadyToRestart():Promise<void>;

export function RecentAgentPages(arg1:number):Promise<Array<engine.AgentPage>>;

export function RecentDebugLog():Promise<Array<string>>;

export function RecentProjects():Promise<Array<engine.ProjectMeta>>;

export function RefreshModelFacts():Promise<void>;

export function RefreshSkills():Promise<void>;

export function RegenerateReply(arg1:boolean):Promise<engine.RegenerateResult>;

export function RejectPendingChange(arg1:number):Promise<void>;

export function RelativizePath(arg1:string):Promise<string>;

export function RememberTTSVoice(arg1:string):Promise<void>;

export function RemoteEngineLog(arg1:string):Promise<string>;

export function RemoteHosts():Promise<main.RemoteHostsView>;

export function RemoveAgentSkill(arg1:string,arg2:string):Promise<void>;

export function RemoveCustomProvider(arg1:string):Promise<Array<string>>;

export function RemoveCustomProviderRow(arg1:string):Promise<Array<string>>;

export function RemoveExternalSkill(arg1:string):Promise<void>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function RemovePresetImage(arg1:string):Promise<void>;

export function RemoveSpaceContext(arg1:string,arg2:string):Promise<Array<string>>;

export function RemoveStudioLibrary(arg1:string):Promise<Array<engine.StudioLibraryView>>;

export function RemoveWorkspaceFolder(arg1:string):Promise<Array<engine.WorkspaceFolder>>;

export function RequestAttention():Promise<void>;

export function RequiresAPIKey(arg1:string):Promise<boolean>;

export function RescanStudioLibrary(arg1:string):Promise<boolean>;

export function ResendEdited(arg1:string,arg2:boolean):Promise<engine.TurnReply>;

export function ResolveAddress(arg1:string):Promise<engine.Address>;

export function ResolveWorkbenchURL(arg1:string):Promise<string|string>;

export function RestartEngine():Promise<void>;

export function RestartToUpdate():Promise<void>;

export function RestorePoints():Promise<Array<engine.RestorePoint>>;

export function RestoreRecurringRequest(arg1:string):Promise<void>;

export function ResumePlanRun(arg1:string):Promise<void>;

export function RetryActiveProvider():Promise<engine.ModelInfo>;

export function RetryFailedTurn(arg1:string):Promise<engine.TurnReply>;

export function RevealSpeechModel(arg1:string):Promise<void>;

export function RevealStudioAsset(arg1:string):Promise<void>;

export function RevealStudioLibrary(arg1:string):Promise<void>;

export function ReviewPullRequest(arg1:number):Promise<string>;

export function RevokeComputerApp(arg1:string):Promise<void>;

export function RevokeDevice(arg1:string):Promise<void>;

export function RewindTo(arg1:string):Promise<engine.UndoResult>;

export function RunChatCommand(arg1:string):Promise<engine.RunBlockResult>;

export function RunChatScript(arg1:string,arg2:string):Promise<engine.RunBlockResult>;

export function RunSessionReview(arg1:string):Promise<number>;

export function RunSkillTuneup():Promise<number>;

export function RunnableLanguages():Promise<Record<string, string>>;

export function SandboxFile(arg1:string):Promise<string>;

export function SaveAgentProfile(arg1:string,arg2:string):Promise<void>;

export function SaveBrowserShot(arg1:Array<number>,arg2:boolean):Promise<string>;

export function SaveChairStarters(arg1:string,arg2:string,arg3:subagent.StarterSet):Promise<void>;

export function SaveChatFile(arg1:string):Promise<string>;

export function SaveChatImage(arg1:string):Promise<string>;

export function SaveChatImageData(arg1:string):Promise<string>;

export function SaveDrawing(arg1:string):Promise<string>;

export function SaveIdentityFile(arg1:string,arg2:string):Promise<void>;

export function SaveLearnedEntry(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SaveMCPServer(arg1:string,arg2:config.MCPServerConfig):Promise<void>;

export function SavePicture(arg1:string):Promise<string>;

export function SavePlanText(arg1:string,arg2:string):Promise<string>;

export function SavePromptPreset(arg1:string,arg2:string):Promise<void>;

export function SaveRemoteHost(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSubagentProfile(arg1:string,arg2:string):Promise<void>;

export function SaveTeam(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function SearchAllSessions(arg1:string):Promise<Array<engine.SessionMeta>>;

export function SearchSessions(arg1:string):Promise<Array<engine.SessionMeta>>;

export function SearchSessionsForDoor(arg1:string,arg2:engine.DeskFilter):Promise<Array<engine.SessionMeta>>;

export function SendMessage(arg1:string,arg2:string):Promise<engine.TurnReply>;

export function SessionAgent(arg1:string):Promise<string>;

export function SessionEdits(arg1:string):Promise<engine.EditPage>;

export function SessionExportBytes(arg1:string,arg2:string):Promise<engine.ExportFile>;

export function SessionMode(arg1:string):Promise<string>;

export function SessionPlan(arg1:string):Promise<engine.Plan>;

export function SessionPlanReports(arg1:string):Promise<Array<engine.PlanReport>>;

export function SessionReviewAuto():Promise<boolean>;

export function SessionSourceCount(arg1:string):Promise<number>;

export function SessionSources(arg1:string):Promise<Array<engine.Source>>;

export function SessionSpend(arg1:string):Promise<engine.SessionSpend>;

export function SessionTeam(arg1:string):Promise<string>;

export function SessionTranscript(arg1:string):Promise<Array<engine.SessionMessage>>;

export function SessionsInSpace(arg1:string):Promise<Array<engine.SessionMeta>>;

export function SetAPIKey(arg1:string,arg2:string):Promise<engine.ModelInfo>;

export function SetAgentOff(arg1:string,arg2:string,arg3:boolean):Promise<engine.DelegateSettings>;

export function SetAttentionSignal(arg1:string,arg2:boolean):Promise<Array<engine.BusyLayer>>;

export function SetBusyLayer(arg1:string,arg2:boolean):Promise<Array<engine.BusyLayer>>;

export function SetCompanionState(arg1:main.CompanionState):Promise<void>;

export function SetComputerControlOn(arg1:boolean):Promise<void>;

export function SetConnectionStartCommand(arg1:string,arg2:string):Promise<void>;

export function SetConnectionTargets(arg1:string,arg2:Array<string>):Promise<void>;

export function SetDelegateOff(arg1:string,arg2:boolean):Promise<engine.DelegateSettings>;

export function SetImageEngine(arg1:string):Promise<void>;

export function SetImageModelName(arg1:string):Promise<void>;

export function SetLearningEnabled(arg1:boolean):Promise<void>;

export function SetMCPServerTargets(arg1:string,arg2:Array<string>):Promise<void>;

export function SetPlanStepStop(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SetPreparedReplyOn(arg1:boolean):Promise<void>;

export function SetPresetImageFrom(arg1:string,arg2:string):Promise<string>;

export function SetProviderBaseURL(arg1:string,arg2:string):Promise<engine.ModelInfo>;

export function SetProviderEnabled(arg1:string,arg2:boolean):Promise<Array<string>>;

export function SetProviderWireFormat(arg1:string):Promise<engine.ModelInfo>;

export function SetSessionReviewAuto(arg1:boolean):Promise<void>;

export function SetShell(arg1:string):Promise<void>;

export function SetSkillTuneAuto(arg1:boolean):Promise<void>;

export function SetSpeechEngine(arg1:string):Promise<void>;

export function SetSpeechModel(arg1:string):Promise<void>;

export function SetSpeechModelName(arg1:string):Promise<void>;

export function SetStance(arg1:string):Promise<string>;

export function SetSubagentModel(arg1:string,arg2:string):Promise<void>;

export function SetTTSEngine(arg1:string):Promise<void>;

export function SetTTSModelName(arg1:string):Promise<void>;

export function SetTTSVoice(arg1:string):Promise<void>;

export function SetUILocale(arg1:string):Promise<void>;

export function SetUserName(arg1:string):Promise<void>;

export function Shells():Promise<Array<engine.ShellOption>>;

export function SignInMethods():Promise<Array<oauth.Method>>;

export function SignInStatus(arg1:string):Promise<oauth.Status>;

export function SignOut(arg1:string):Promise<engine.ModelInfo>;

export function SkillScanIssues():Promise<Array<string>>;

export function SkillTuneAuto():Promise<boolean>;

export function SkillsDir():Promise<string>;

export function SkillsFolderPath():Promise<string>;

export function SpaceFolderPath(arg1:string):Promise<string>;

export function Spaces():Promise<Array<engine.Space>>;

export function SpeakText(arg1:string):Promise<string>;

export function SpeechModelDirPath(arg1:string):Promise<string>;

export function SpeechModelDirs():Promise<Array<engine.SpeechDirInfo>>;

export function SpeechModelFolderPath(arg1:string):Promise<string>;

export function SpeechPlaying(arg1:string,arg2:number):Promise<void>;

export function SpeechStatus():Promise<string>;

export function StageUpdate():Promise<void>;

export function StagedUpdate():Promise<main.StagedInfo>;

export function Stance():Promise<string>;

export function Stances():Promise<Array<string>>;

export function StartAccountSignIn(arg1:string):Promise<string>;

export function StartConnectionServer(arg1:string):Promise<void>;

export function StartMCPSignIn(arg1:string,arg2:string):Promise<engine.SignInPrompt>;

export function StartMobileRemote():Promise<engine.RemoteStatus>;

export function StartPlanRun(arg1:string):Promise<engine.PlanRunStart>;

export function StartSignIn(arg1:string):Promise<engine.SignInPrompt>;

export function StartSpeech(arg1:string):Promise<string>;

export function StopBackgroundRun(arg1:string):Promise<number>;

export function StopBackgroundTask(arg1:string):Promise<boolean>;

export function StopBrowsing():Promise<void>;

export function StopMobileRemote():Promise<engine.RemoteStatus>;

export function StopPlanRun(arg1:string):Promise<void>;

export function StopQueuedTasks():Promise<number>;

export function StopRemoteEngine(arg1:string):Promise<void>;

export function StopSpeech(arg1:string):Promise<void>;

export function StudioAssetPath(arg1:string):Promise<string>;

export function StudioAssets(arg1:engine.StudioAssetQuery):Promise<engine.StudioAssetPage>;

export function StudioLibraries():Promise<Array<engine.StudioLibraryView>>;

export function StudioLibraryPath(arg1:string):Promise<string>;

export function StudioScanning():Promise<boolean>;

export function StudioSetHidden(arg1:string,arg2:boolean):Promise<void>;

export function StudioSetKind(arg1:string,arg2:string):Promise<void>;

export function StudioThumbs(arg1:Array<string>):Promise<Record<string, string>>;

export function SubagentsFolderPath():Promise<string>;

export function SuggestPRDetails(arg1:string,arg2:string):Promise<engine.PRSuggestion>;

export function SupportedProviders():Promise<Array<string>>;

export function SupportedThinkLevels():Promise<Array<string>>;

export function SwitchApprovalMode(arg1:string):Promise<engine.ModelInfo>;

export function SwitchModel(arg1:string):Promise<engine.ModelInfo>;

export function SwitchProvider(arg1:string):Promise<engine.ModelInfo>;

export function SwitchThinkLevel(arg1:string):Promise<engine.ModelInfo>;

export function SwitchVariant(arg1:number):Promise<engine.RegenerateResult>;

export function SynthesizeHabit(arg1:string,arg2:string):Promise<number>;

export function TTSStatus():Promise<string>;

export function TeamsFolderPath():Promise<string>;

export function TerminalAttach(arg1:string):Promise<string>;

export function TerminalClose(arg1:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalShells():Promise<Array<engine.ShellProfile>>;

export function TerminalStart(arg1:string,arg2:number,arg3:number):Promise<string>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;

export function TestMCPServer(arg1:string):Promise<engine.MCPServerInfo>;

export function TestProviderConnection(arg1:string,arg2:string):Promise<string>;

export function ToggleMCPServer(arg1:string,arg2:boolean):Promise<void>;

export function ToolBlockTokens():Promise<number>;

export function ToolCounts():Promise<engine.ToolCounts>;

export function ToolInstallPlan(arg1:string):Promise<engine.ToolInstallPlan>;

export function TranscribeMicAudio(arg1:string):Promise<string>;

export function TurnInFlight():Promise<engine.TurnStatus>;

export function TurnRating(arg1:number):Promise<string>;

export function UndoLastTurn():Promise<engine.UndoResult>;

export function UsageStats():Promise<engine.UsageStats>;

export function UseEngine(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UserName():Promise<string>;

export function VerifyConnection(arg1:string):Promise<connect.Account>;

export function VideoCheckSeen():Promise<boolean>;

export function VideoEditorCommand():Promise<Array<string>>;

export function VideoEditorEnvironment():Promise<Record<string, string>>;

export function VideoEditorHelpURL(arg1:string):Promise<string>;

export function VideoEditorTools():Promise<Array<string>>;

export function VideoReadiness(arg1:string):Promise<engine.VideoReadiness>;

export function VideoToolingStatus():Promise<engine.VideoToolingStatus>;

export function VoiceSettings():Promise<engine.VoiceSettings>;

export function WorkbenchTabsChanged(arg1:string,arg2:Array<engine.DeskTab>):Promise<void>;

export function WorkspaceFolders():Promise<Array<engine.WorkspaceFolder>>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
