// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetModelInfo():Promise<main.ModelInfo>;

export function GetProjectStatus():Promise<main.ProjectStatus>;

export function HasAPIKey(arg1:string):Promise<boolean>;

export function ListModelsForProvider(arg1:string):Promise<Array<string>>;

export function ModelStatus():Promise<string>;

export function OpenProjectFolder():Promise<main.ProjectStatus>;

export function RequiresAPIKey(arg1:string):Promise<boolean>;

export function SendMessage(arg1:string):Promise<string>;

export function SetAPIKey(arg1:string,arg2:string):Promise<main.ModelInfo>;

export function SupportedProviders():Promise<Array<string>>;

export function SupportedThinkLevels():Promise<Array<string>>;

export function SwitchApprovalMode(arg1:string):Promise<main.ModelInfo>;

export function SwitchModel(arg1:string):Promise<main.ModelInfo>;

export function SwitchProvider(arg1:string):Promise<main.ModelInfo>;

export function SwitchThinkLevel(arg1:string):Promise<main.ModelInfo>;
