// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {skill} from '../models';
import {config} from '../models';

export function AddMCPServer(arg1:string,arg2:Array<string>):Promise<void>;

export function BrowserBack(arg1:string):Promise<void>;

export function BrowserClickRef(arg1:string,arg2:number):Promise<void>;

export function BrowserClose(arg1:string):Promise<void>;

export function BrowserForward(arg1:string):Promise<void>;

export function BrowserGetText(arg1:string):Promise<string>;

export function BrowserNavigate(arg1:string,arg2:string):Promise<void>;

export function BrowserOpen(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number):Promise<void>;

export function BrowserReload(arg1:string):Promise<void>;

export function BrowserSetBounds(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function BrowserSetVisible(arg1:string,arg2:boolean):Promise<void>;

export function BrowserTypeRef(arg1:string,arg2:number,arg3:string,arg4:boolean):Promise<void>;

export function CancelTurn():Promise<void>;

export function ClearProjectFocus():Promise<main.ProjectStatus>;

export function CloseAllBrowserTabs():Promise<void>;

export function CommandHistory():Promise<Array<string>>;

export function CurrentSessionID():Promise<string>;

export function DeleteIdentityFile(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetContextBreakdown():Promise<main.ContextBreakdown>;

export function GetModelInfo():Promise<main.ModelInfo>;

export function GetProjectStatus():Promise<main.ProjectStatus>;

export function GitChangedFiles():Promise<Array<main.ChangedFile>>;

export function HasAPIKey(arg1:string):Promise<boolean>;

export function InstallSkillFromGitHub(arg1:string):Promise<string>;

export function ListAllSessions():Promise<Array<main.SessionMeta>>;

export function ListExternalSkills():Promise<Array<skill.DiscoveredSkill>>;

export function ListIdentityFiles():Promise<Array<main.IdentityFile>>;

export function ListMCPServers():Promise<Array<main.MCPServerInfo>>;

export function ListModelsForProvider(arg1:string):Promise<Array<string>>;

export function ListSessions():Promise<Array<main.SessionMeta>>;

export function ListSkills():Promise<Array<main.SkillInfo>>;

export function LoadSession(arg1:string):Promise<Array<main.SessionMessage>>;

export function LoadSessionAnyProject(arg1:string):Promise<Array<main.SessionMessage>>;

export function ModelStatus():Promise<string>;

export function NewSession():Promise<string>;

export function OpenProjectFolder():Promise<main.ProjectStatus>;

export function OpenProjectPath(arg1:string):Promise<main.ProjectStatus>;

export function PickAttachmentImage():Promise<string>;

export function ProjectTree():Promise<Array<main.TreeNode>>;

export function ProviderBaseURL(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadIdentityFile(arg1:string):Promise<string>;

export function ReadImageDataURL(arg1:string):Promise<string>;

export function RecentProjects():Promise<Array<main.ProjectMeta>>;

export function RefreshSkills():Promise<void>;

export function RelativizePath(arg1:string):Promise<string>;

export function RemoveExternalSkill(arg1:string):Promise<void>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function RequiresAPIKey(arg1:string):Promise<boolean>;

export function SaveChatImage(arg1:string):Promise<string>;

export function SaveIdentityFile(arg1:string,arg2:string):Promise<void>;

export function SaveMCPServer(arg1:string,arg2:config.MCPServerConfig):Promise<void>;

export function SearchAllSessions(arg1:string):Promise<Array<main.SessionMeta>>;

export function SearchSessions(arg1:string):Promise<Array<main.SessionMeta>>;

export function SendMessage(arg1:string):Promise<string>;

export function SetAPIKey(arg1:string,arg2:string):Promise<main.ModelInfo>;

export function SupportedProviders():Promise<Array<string>>;

export function SupportedThinkLevels():Promise<Array<string>>;

export function SwitchApprovalMode(arg1:string):Promise<main.ModelInfo>;

export function SwitchModel(arg1:string):Promise<main.ModelInfo>;

export function SwitchProvider(arg1:string):Promise<main.ModelInfo>;

export function SwitchThinkLevel(arg1:string):Promise<main.ModelInfo>;

export function TerminalClose(arg1:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalShells():Promise<Array<main.ShellProfile>>;

export function TerminalStart(arg1:string,arg2:number,arg3:number):Promise<string>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;

export function TestMCPServer(arg1:string):Promise<main.MCPServerInfo>;

export function ToggleMCPServer(arg1:string,arg2:boolean):Promise<void>;

export function UsageStats():Promise<main.UsageStats>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
