// Code generated by internal/engine/gen. DO NOT EDIT.

package main

// Every engine binding the frontend calls, forwarded (§248 B1). A binding
// the screen implements itself is not here — the generator skips any
// method desktop/ defines on App.

import (
	"github.com/Mikedev115/Aetox/internal/capability"
	"github.com/Mikedev115/Aetox/internal/cliagent"
	"github.com/Mikedev115/Aetox/internal/command"
	"github.com/Mikedev115/Aetox/internal/config"
	"github.com/Mikedev115/Aetox/internal/connect"
	"github.com/Mikedev115/Aetox/internal/engine"
	gh "github.com/Mikedev115/Aetox/internal/github"
	"github.com/Mikedev115/Aetox/internal/machine"
	"github.com/Mikedev115/Aetox/internal/mode"
	"github.com/Mikedev115/Aetox/internal/model"
	"github.com/Mikedev115/Aetox/internal/oauth"
	"github.com/Mikedev115/Aetox/internal/ooxml"
	"github.com/Mikedev115/Aetox/internal/skill"
	"github.com/Mikedev115/Aetox/internal/subagent"
)

func (a *App) AcceptsAPIKey(providerName string) bool {
	return a.api.AcceptsAPIKey(providerName)
}

func (a *App) ActiveModelFor(providerName string) (string, string) {
	return a.api.ActiveModelFor(providerName)
}

func (a *App) AddCustomProviderRow(name string, baseURL string) (string, error) {
	return a.api.AddCustomProviderRow(name, baseURL)
}

func (a *App) AddLearnedEntry(scope string, text string) error {
	return a.api.AddLearnedEntry(scope, text)
}

func (a *App) AddMCPServer(name string, command []string) error {
	return a.api.AddMCPServer(name, command)
}

func (a *App) AddStudioLibraryAt(dir string) (bool, error) {
	return a.api.AddStudioLibraryAt(dir)
}

func (a *App) AddWorkspaceFolderAt(dir string) ([]engine.WorkspaceFolder, error) {
	return a.api.AddWorkspaceFolderAt(dir)
}

func (a *App) AdoptMemoryScope(scope string, targetRoot string) error {
	return a.api.AdoptMemoryScope(scope, targetRoot)
}

func (a *App) AgentBlocked(name string) bool {
	return a.api.AgentBlocked(name)
}

func (a *App) AgentGate(name string) engine.AgentGate {
	return a.api.AgentGate(name)
}

func (a *App) AgentHomePath(name string) (string, error) {
	return a.api.AgentHomePath(name)
}

func (a *App) AgentNeeds(name string) []subagent.Requirement {
	return a.api.AgentNeeds(name)
}

func (a *App) AgentPackageBytes(name string) (engine.ExportFile, error) {
	return a.api.AgentPackageBytes(name)
}

func (a *App) AgentSkills(name string) []engine.AgentSkillInfo {
	return a.api.AgentSkills(name)
}

func (a *App) AgentSkillsFolderPath(name string) (string, error) {
	return a.api.AgentSkillsFolderPath(name)
}

func (a *App) AgentsFolderPath() (string, error) {
	return a.api.AgentsFolderPath()
}

func (a *App) AnswerUserQuestion(sessionID string, answer string) {
	a.api.AnswerUserQuestion(sessionID, answer)
}

func (a *App) AnyTurnRunning() bool {
	return a.api.AnyTurnRunning()
}

func (a *App) AppCredit() string {
	return a.api.AppCredit()
}

func (a *App) AppVersion() string {
	return a.api.AppVersion()
}

func (a *App) ApplyMemoryLines(scope string, lines []string) error {
	return a.api.ApplyMemoryLines(scope, lines)
}

func (a *App) ApprovePendingChange(id int64) error {
	return a.api.ApprovePendingChange(id)
}

func (a *App) ApprovePendingChangeTo(id int64, scope string) error {
	return a.api.ApprovePendingChangeTo(id, scope)
}

func (a *App) ArtifactPath(path string) (string, error) {
	return a.api.ArtifactPath(path)
}

func (a *App) ArtifactPreview(path string) (engine.ArtifactPreview, error) {
	return a.api.ArtifactPreview(path)
}

func (a *App) BackgroundRuns() []engine.BackgroundRun {
	return a.api.BackgroundRuns()
}

func (a *App) BackgroundTasks() []engine.BackgroundTask {
	return a.api.BackgroundTasks()
}

func (a *App) BrowseFolderAt(dir string) (string, error) {
	return a.api.BrowseFolderAt(dir)
}

func (a *App) BrowseRoot() string {
	return a.api.BrowseRoot()
}

func (a *App) BusySignal() []engine.BusyLayer {
	return a.api.BusySignal()
}

func (a *App) CancelMCPSignIn(serverName string) {
	a.api.CancelMCPSignIn(serverName)
}

func (a *App) CancelPendingModel() engine.ModelInfo {
	return a.api.CancelPendingModel()
}

func (a *App) CancelStudioScan() {
	a.api.CancelStudioScan()
}

func (a *App) CancelTurn() {
	a.api.CancelTurn()
}

func (a *App) CapabilitiesInstalling() bool {
	return a.api.CapabilitiesInstalling()
}

func (a *App) CapabilityForServer(server string) string {
	return a.api.CapabilityForServer(server)
}

func (a *App) CapabilityStatuses() []capability.Status {
	return a.api.CapabilityStatuses()
}

func (a *App) CatalogModelChoices(canonical string) []string {
	return a.api.CatalogModelChoices(canonical)
}

func (a *App) ChairStarters(name string, locale string) subagent.StarterSet {
	return a.api.ChairStarters(name, locale)
}

func (a *App) ChairStartersFile(locale string) string {
	return a.api.ChairStartersFile(locale)
}

func (a *App) CheckConnectionServer(id string) (bool, error) {
	return a.api.CheckConnectionServer(id)
}

func (a *App) ClearProjectFocus() (engine.ProjectStatus, error) {
	return a.api.ClearProjectFocus()
}

func (a *App) CodeProjectsDir() string {
	return a.api.CodeProjectsDir()
}

func (a *App) CommandHistory() []string {
	return a.api.CommandHistory()
}

func (a *App) CompleteMCPSignIn(serverName string) error {
	return a.api.CompleteMCPSignIn(serverName)
}

func (a *App) CompressArtifacts(paths []string) (engine.CompressReport, error) {
	return a.api.CompressArtifacts(paths)
}

func (a *App) ComputerControlChanged() {
	a.api.ComputerControlChanged()
}

func (a *App) ConnectAccount(id string, token string, baseURL string, targets []string) (connect.Account, error) {
	return a.api.ConnectAccount(id, token, baseURL, targets)
}

func (a *App) Connections() []connect.Status {
	return a.api.Connections()
}

func (a *App) ConsolidateMemory(scope string) (engine.MemoryConsolidation, error) {
	return a.api.ConsolidateMemory(scope)
}

func (a *App) CopySkillToAgent(agent string, name string) error {
	return a.api.CopySkillToAgent(agent, name)
}

func (a *App) CreateCodeProject(name string) (string, error) {
	return a.api.CreateCodeProject(name)
}

func (a *App) CreatePullRequest(title string, head string, base string, body string, draft bool) engine.PRCreated {
	return a.api.CreatePullRequest(title, head, base, body, draft)
}

func (a *App) CreateSpace(name string) (engine.Space, error) {
	return a.api.CreateSpace(name)
}

func (a *App) CurrentSessionID() string {
	return a.api.CurrentSessionID()
}

func (a *App) CurrentShell() engine.ShellOption {
	return a.api.CurrentShell()
}

func (a *App) CurrentSpace() string {
	return a.api.CurrentSpace()
}

func (a *App) CustomProviders() []engine.CustomProviderRow {
	return a.api.CustomProviders()
}

func (a *App) DeckCaptureDrawing(relPath string, slide int, ink string) (string, error) {
	return a.api.DeckCaptureDrawing(relPath, slide, ink)
}

func (a *App) DeckExportFiles(relPath string, format string) (engine.DeckExport, error) {
	return a.api.DeckExportFiles(relPath, format)
}

func (a *App) DeckFormats() []engine.DeckFormat {
	return a.api.DeckFormats()
}

func (a *App) DelegateSwitches(team string) engine.DelegateSettings {
	return a.api.DelegateSwitches(team)
}

func (a *App) DeleteArtifact(path string) error {
	return a.api.DeleteArtifact(path)
}

func (a *App) DeleteDeck(relPath string) error {
	return a.api.DeleteDeck(relPath)
}

func (a *App) DeleteIdentityFile(head string, name string) error {
	return a.api.DeleteIdentityFile(head, name)
}

func (a *App) DeletePromptPreset(name string) error {
	return a.api.DeletePromptPreset(name)
}

func (a *App) DeleteSession(id string) error {
	return a.api.DeleteSession(id)
}

func (a *App) DeleteSpace(name string) error {
	return a.api.DeleteSpace(name)
}

func (a *App) DeleteSubagentProfile(name string) error {
	return a.api.DeleteSubagentProfile(name)
}

func (a *App) DeleteTeam(name string) error {
	return a.api.DeleteTeam(name)
}

func (a *App) DeskStarters(desk string, locale string) subagent.StarterSet {
	return a.api.DeskStarters(desk, locale)
}

func (a *App) DisconnectAccount(id string) error {
	return a.api.DisconnectAccount(id)
}

func (a *App) DismissRecurringRequest(normalized string, sampleText string) error {
	return a.api.DismissRecurringRequest(normalized, sampleText)
}

func (a *App) DismissTaskChip(id string) {
	a.api.DismissTaskChip(id)
}

func (a *App) EnabledProviders() []string {
	return a.api.EnabledProviders()
}

func (a *App) EnginesFor(family string, agent string) []connect.Status {
	return a.api.EnginesFor(family, agent)
}

func (a *App) ExternalEngineStatus(providerName string) cliagent.Status {
	return a.api.ExternalEngineStatus(providerName)
}

func (a *App) FileStillThere(relPath string) string {
	return a.api.FileStillThere(relPath)
}

func (a *App) ForgetMemoryScope(scope string) error {
	return a.api.ForgetMemoryScope(scope)
}

func (a *App) ForgetProject(root string) (engine.ProjectStatus, error) {
	return a.api.ForgetProject(root)
}

func (a *App) GetContextBreakdown() engine.ContextBreakdown {
	return a.api.GetContextBreakdown()
}

func (a *App) GetModelInfo() engine.ModelInfo {
	return a.api.GetModelInfo()
}

func (a *App) GetProjectStatus() engine.ProjectStatus {
	return a.api.GetProjectStatus()
}

func (a *App) GetRepoMapGraph(maxNodes int) engine.RepoMapGraph {
	return a.api.GetRepoMapGraph(maxNodes)
}

func (a *App) GitBranches() []engine.GitBranch {
	return a.api.GitBranches()
}

func (a *App) GitChangedFiles() []engine.ChangedFile {
	return a.api.GitChangedFiles()
}

func (a *App) GitCommitChanges(hash string) []engine.GitFileChange {
	return a.api.GitCommitChanges(hash)
}

func (a *App) GitCommitFileDiff(hash string, path string) string {
	return a.api.GitCommitFileDiff(hash, path)
}

func (a *App) GitCommitFiles(message string, files []string) error {
	return a.api.GitCommitFiles(message, files)
}

func (a *App) GitCreateBranch(name string) (string, error) {
	return a.api.GitCreateBranch(name)
}

func (a *App) GitFileDiff(path string) string {
	return a.api.GitFileDiff(path)
}

func (a *App) GitLog(before string, limit int) engine.GitLogPage {
	return a.api.GitLog(before, limit)
}

func (a *App) GitSplitCancel() {
	a.api.GitSplitCancel()
}

func (a *App) GitSuggestCommitMessage(files []string) (string, error) {
	return a.api.GitSuggestCommitMessage(files)
}

func (a *App) GitSuggestSplitCommits() ([]engine.GitCommitGroup, error) {
	return a.api.GitSuggestSplitCommits()
}

func (a *App) GitSwitchBranch(name string) (string, error) {
	return a.api.GitSwitchBranch(name)
}

func (a *App) GitWorkingTree() ([]engine.GitFileChange, error) {
	return a.api.GitWorkingTree()
}

func (a *App) GuideTopics() []model.GuideTopic {
	return a.api.GuideTopics()
}

func (a *App) HandedOverFile(fileURL string) string {
	return a.api.HandedOverFile(fileURL)
}

func (a *App) HeadName(head string) string {
	return a.api.HeadName(head)
}

func (a *App) HistoryFault() engine.StoreFault {
	return a.api.HistoryFault()
}

func (a *App) HomeDir() string {
	return a.api.HomeDir()
}

func (a *App) ImageStatus() string {
	return a.api.ImageStatus()
}

func (a *App) ImportSessionFrom(path string) (string, error) {
	return a.api.ImportSessionFrom(path)
}

func (a *App) InstallCapabilities(capabilities []string) bool {
	return a.api.InstallCapabilities(capabilities)
}

func (a *App) InstallSkillFromGitHub(repoURL string) (string, error) {
	return a.api.InstallSkillFromGitHub(repoURL)
}

func (a *App) InstallSkillsFromZipAt(path string) (string, error) {
	return a.api.InstallSkillsFromZipAt(path)
}

func (a *App) InstallVoiceEngine(side string, id string) error {
	return a.api.InstallVoiceEngine(side, id)
}

func (a *App) Interject(text string) error {
	return a.api.Interject(text)
}

func (a *App) LearnedEntries(scope string) []string {
	return a.api.LearnedEntries(scope)
}

func (a *App) LearnedMemory(scope string) string {
	return a.api.LearnedMemory(scope)
}

func (a *App) LearnedScopeInfos() []engine.MemoryScopeInfo {
	return a.api.LearnedScopeInfos()
}

func (a *App) LearnedScopes() []string {
	return a.api.LearnedScopes()
}

func (a *App) LearningEnabled() bool {
	return a.api.LearningEnabled()
}

func (a *App) ListAllSessions() []engine.SessionMeta {
	return a.api.ListAllSessions()
}

func (a *App) ListArtifacts() []engine.Artifact {
	return a.api.ListArtifacts()
}

func (a *App) ListArtifactsForSession(sessionID string) engine.ArtifactPage {
	return a.api.ListArtifactsForSession(sessionID)
}

func (a *App) ListArtifactsIn(want string) engine.ArtifactPage {
	return a.api.ListArtifactsIn(want)
}

func (a *App) ListChairs() []engine.Chair {
	return a.api.ListChairs()
}

func (a *App) ListDecidedChanges(limit int) []engine.PendingChange {
	return a.api.ListDecidedChanges(limit)
}

func (a *App) ListDecidedIssues(limit int) []engine.PendingChange {
	return a.api.ListDecidedIssues(limit)
}

func (a *App) ListDecidedSkillProposals(limit int) []engine.PendingChange {
	return a.api.ListDecidedSkillProposals(limit)
}

func (a *App) ListDecks() []engine.Deck {
	return a.api.ListDecks()
}

func (a *App) ListDecksIn(want string) engine.DeckPage {
	return a.api.ListDecksIn(want)
}

func (a *App) ListDir(path string) (engine.DirListing, error) {
	return a.api.ListDir(path)
}

func (a *App) ListExternalSkills() []skill.DiscoveredSkill {
	return a.api.ListExternalSkills()
}

func (a *App) ListIdentityFiles(head string) ([]engine.IdentityFile, error) {
	return a.api.ListIdentityFiles(head)
}

func (a *App) ListImageEngines() []engine.VoiceEngineInfo {
	return a.api.ListImageEngines()
}

func (a *App) ListMCPServers() []engine.MCPServerInfo {
	return a.api.ListMCPServers()
}

func (a *App) ListModes() []mode.Mode {
	return a.api.ListModes()
}

func (a *App) ListPendingChanges() []engine.PendingChange {
	return a.api.ListPendingChanges()
}

func (a *App) ListPromptPresets() []command.Preset {
	return a.api.ListPromptPresets()
}

func (a *App) ListReceivedJobs(limit int) []engine.ReceivedJob {
	return a.api.ListReceivedJobs(limit)
}

func (a *App) ListRecurringRequests() []engine.RecurringRequest {
	return a.api.ListRecurringRequests()
}

func (a *App) ListSessions() []engine.SessionMeta {
	return a.api.ListSessions()
}

func (a *App) ListSessionsAt(desk string) []engine.SessionMeta {
	return a.api.ListSessionsAt(desk)
}

func (a *App) ListSessionsForDoor(filter engine.DeskFilter) []engine.SessionMeta {
	return a.api.ListSessionsForDoor(filter)
}

func (a *App) ListSkillProposals() []engine.PendingChange {
	return a.api.ListSkillProposals()
}

func (a *App) ListSkills() []engine.SkillInfo {
	return a.api.ListSkills()
}

func (a *App) ListSpeechEngines() []engine.VoiceEngineInfo {
	return a.api.ListSpeechEngines()
}

func (a *App) ListSpeechModels() []engine.SpeechModelInfo {
	return a.api.ListSpeechModels()
}

func (a *App) ListSubagentProfiles() []subagent.Profile {
	return a.api.ListSubagentProfiles()
}

func (a *App) ListSystemIssues() []engine.PendingChange {
	return a.api.ListSystemIssues()
}

func (a *App) ListTTSEngines() []engine.VoiceEngineInfo {
	return a.api.ListTTSEngines()
}

func (a *App) ListTaskChips() []engine.TaskChip {
	return a.api.ListTaskChips()
}

func (a *App) ListTeams(desk string) []engine.TeamCard {
	return a.api.ListTeams(desk)
}

func (a *App) ListTools() []engine.SkillInfo {
	return a.api.ListTools()
}

func (a *App) LoadSession(id string) ([]engine.SessionMessage, error) {
	return a.api.LoadSession(id)
}

func (a *App) LoadSessionAnyProject(id string) ([]engine.SessionMessage, error) {
	return a.api.LoadSessionAnyProject(id)
}

func (a *App) MCPConfigPath() string {
	return a.api.MCPConfigPath()
}

func (a *App) MCPFolderPath() (string, error) {
	return a.api.MCPFolderPath()
}

func (a *App) MCPSignInStatus(serverName string) oauth.Status {
	return a.api.MCPSignInStatus(serverName)
}

func (a *App) MachineInfo() machine.Info {
	return a.api.MachineInfo()
}

func (a *App) MarkIssueReported(id int64) error {
	return a.api.MarkIssueReported(id)
}

func (a *App) MarkVideoCheckSeen() {
	a.api.MarkVideoCheckSeen()
}

func (a *App) MemoryFolderPath() (string, error) {
	return a.api.MemoryFolderPath()
}

func (a *App) MemoryScopeInfo(scope string) engine.MemoryScopeInfo {
	return a.api.MemoryScopeInfo(scope)
}

func (a *App) MobileRemoteQR() string {
	return a.api.MobileRemoteQR()
}

func (a *App) MobileRemoteStatus() engine.RemoteStatus {
	return a.api.MobileRemoteStatus()
}

func (a *App) ModelPriceSource() engine.PriceSource {
	return a.api.ModelPriceSource()
}

func (a *App) ModelStatus() string {
	return a.api.ModelStatus()
}

func (a *App) MoveLearnedEntry(fromScope string, toScope string, index int) error {
	return a.api.MoveLearnedEntry(fromScope, toScope, index)
}

func (a *App) NewChairSession(chair string) (string, error) {
	return a.api.NewChairSession(chair)
}

func (a *App) NewChairSessionAt(desk string, chair string, team string) (string, error) {
	return a.api.NewChairSessionAt(desk, chair, team)
}

func (a *App) NewSession() (string, error) {
	return a.api.NewSession()
}

func (a *App) NewSessionAt(desk string) (string, error) {
	return a.api.NewSessionAt(desk)
}

func (a *App) NewSessionInSpace(name string) (string, error) {
	return a.api.NewSessionInSpace(name)
}

func (a *App) NewTeamSession(desk string, team string) (string, error) {
	return a.api.NewTeamSession(desk, team)
}

func (a *App) NoteProviderQuotas(providerName string, quotas []model.Quota) {
	a.api.NoteProviderQuotas(providerName, quotas)
}

func (a *App) OpenProjectPath(root string) (engine.ProjectStatus, error) {
	return a.api.OpenProjectPath(root)
}

func (a *App) PageMarksOn() bool {
	return a.api.PageMarksOn()
}

func (a *App) PairedDevices() []engine.RemoteDevice {
	return a.api.PairedDevices()
}

func (a *App) PausePlanRun(sessionID string) {
	a.api.PausePlanRun(sessionID)
}

func (a *App) PendingChangeByID(id int64) engine.PendingChange {
	return a.api.PendingChangeByID(id)
}

func (a *App) PendingIssueCount() int {
	return a.api.PendingIssueCount()
}

func (a *App) PendingLearnedCount() int {
	return a.api.PendingLearnedCount()
}

func (a *App) PendingRestore(id string) []string {
	return a.api.PendingRestore(id)
}

func (a *App) PendingSkillTuneCount() int {
	return a.api.PendingSkillTuneCount()
}

func (a *App) PendingUndo() []string {
	return a.api.PendingUndo()
}

func (a *App) PictureBytes(relPath string) (engine.ExportFile, error) {
	return a.api.PictureBytes(relPath)
}

func (a *App) PlacementTargets() []engine.PlacementTarget {
	return a.api.PlacementTargets()
}

func (a *App) PlanRunning(sessionID string) bool {
	return a.api.PlanRunning(sessionID)
}

func (a *App) PrepareToClose() {
	a.api.PrepareToClose()
}

func (a *App) PreparedReplyOn() bool {
	return a.api.PreparedReplyOn()
}

func (a *App) PriceModels(providerName string, models []string) []engine.ModelListing {
	return a.api.PriceModels(providerName, models)
}

func (a *App) ProjectFilePath(relPath string) (string, error) {
	return a.api.ProjectFilePath(relPath)
}

func (a *App) ProjectTree() []engine.TreeNode {
	return a.api.ProjectTree()
}

func (a *App) PromptsFolderPath() (string, error) {
	return a.api.PromptsFolderPath()
}

func (a *App) ProviderAPIKeyURL(providerName string) string {
	return a.api.ProviderAPIKeyURL(providerName)
}

func (a *App) ProviderBaseURL(providerName string) string {
	return a.api.ProviderBaseURL(providerName)
}

func (a *App) ProviderBaseURLIsCustom(providerName string) bool {
	return a.api.ProviderBaseURLIsCustom(providerName)
}

func (a *App) ProviderCredentialChanged(providerName string) (engine.ModelInfo, error) {
	return a.api.ProviderCredentialChanged(providerName)
}

func (a *App) ProviderQuotas(providerName string) ([]model.Quota, bool) {
	return a.api.ProviderQuotas(providerName)
}

func (a *App) ProviderWireFormats(providerName string) []string {
	return a.api.ProviderWireFormats(providerName)
}

func (a *App) PullRequestChecks(sha string) []gh.CheckRun {
	return a.api.PullRequestChecks(sha)
}

func (a *App) PullRequestFiles(number int) []gh.PRFile {
	return a.api.PullRequestFiles(number)
}

func (a *App) PullRequests() engine.PRRoom {
	return a.api.PullRequests()
}

func (a *App) PullRequestsState(state string) engine.PRRoom {
	return a.api.PullRequestsState(state)
}

func (a *App) RateTurn(messageID int64, verdict string) {
	a.api.RateTurn(messageID, verdict)
}

func (a *App) ReadDeskFile(name string) (engine.DeskFile, error) {
	return a.api.ReadDeskFile(name)
}

func (a *App) ReadFile(relPath string) (string, error) {
	return a.api.ReadFile(relPath)
}

func (a *App) ReadIdentityFile(head string, name string) (string, error) {
	return a.api.ReadIdentityFile(head, name)
}

func (a *App) ReadImageDataURL(relPath string) (string, error) {
	return a.api.ReadImageDataURL(relPath)
}

func (a *App) ReadSubagentProfile(name string) (string, error) {
	return a.api.ReadSubagentProfile(name)
}

func (a *App) ReadWorkbook(relPath string) (*ooxml.WorkbookPreview, error) {
	return a.api.ReadWorkbook(relPath)
}

func (a *App) ReadyToRestart() error {
	return a.api.ReadyToRestart()
}

func (a *App) RecentAgentPages(limit int) []engine.AgentPage {
	return a.api.RecentAgentPages(limit)
}

func (a *App) RecentDebugLog() []string {
	return a.api.RecentDebugLog()
}

func (a *App) RecentProjects() []engine.ProjectMeta {
	return a.api.RecentProjects()
}

func (a *App) RefreshModelFacts() {
	a.api.RefreshModelFacts()
}

func (a *App) RefreshSkills() {
	a.api.RefreshSkills()
}

func (a *App) RegenerateReply(revertFiles bool) (engine.RegenerateResult, error) {
	return a.api.RegenerateReply(revertFiles)
}

func (a *App) RejectPendingChange(id int64) error {
	return a.api.RejectPendingChange(id)
}

func (a *App) RelativizePath(absPath string) (string, error) {
	return a.api.RelativizePath(absPath)
}

func (a *App) RememberTTSVoice(id string) {
	a.api.RememberTTSVoice(id)
}

func (a *App) RemoveAgentSkill(agent string, name string) error {
	return a.api.RemoveAgentSkill(agent, name)
}

func (a *App) RemoveCustomProviderRow(id string) ([]string, error) {
	return a.api.RemoveCustomProviderRow(id)
}

func (a *App) RemoveExternalSkill(name string) error {
	return a.api.RemoveExternalSkill(name)
}

func (a *App) RemoveMCPServer(name string) error {
	return a.api.RemoveMCPServer(name)
}

func (a *App) RemovePresetImage(name string) error {
	return a.api.RemovePresetImage(name)
}

func (a *App) RemoveSpaceContext(name string, file string) ([]string, error) {
	return a.api.RemoveSpaceContext(name, file)
}

func (a *App) RemoveStudioLibrary(id string) ([]engine.StudioLibraryView, error) {
	return a.api.RemoveStudioLibrary(id)
}

func (a *App) RemoveWorkspaceFolder(path string) ([]engine.WorkspaceFolder, error) {
	return a.api.RemoveWorkspaceFolder(path)
}

func (a *App) RequiresAPIKey(providerName string) bool {
	return a.api.RequiresAPIKey(providerName)
}

func (a *App) RescanStudioLibrary(id string) (bool, error) {
	return a.api.RescanStudioLibrary(id)
}

func (a *App) ResendEdited(text string, revertFiles bool) (engine.TurnReply, error) {
	return a.api.ResendEdited(text, revertFiles)
}

func (a *App) ResetDeskFile(name string) error {
	return a.api.ResetDeskFile(name)
}

func (a *App) ResolveAddress(input string) engine.Address {
	return a.api.ResolveAddress(input)
}

func (a *App) ResolveWorkbenchURL(input string) (string, string) {
	return a.api.ResolveWorkbenchURL(input)
}

func (a *App) RestorePoints() []engine.RestorePoint {
	return a.api.RestorePoints()
}

func (a *App) RestoreRecurringRequest(normalized string) error {
	return a.api.RestoreRecurringRequest(normalized)
}

func (a *App) ResumePlanRun(sessionID string) {
	a.api.ResumePlanRun(sessionID)
}

func (a *App) RetryActiveProvider() engine.ModelInfo {
	return a.api.RetryActiveProvider()
}

func (a *App) RetryFailedTurn(text string) (engine.TurnReply, error) {
	return a.api.RetryFailedTurn(text)
}

func (a *App) ReviewPullRequest(number int) (string, error) {
	return a.api.ReviewPullRequest(number)
}

func (a *App) RevokeDevice(id string) error {
	return a.api.RevokeDevice(id)
}

func (a *App) RewindTo(id string) (engine.UndoResult, error) {
	return a.api.RewindTo(id)
}

func (a *App) RunChatCommand(command string) (engine.RunBlockResult, error) {
	return a.api.RunChatCommand(command)
}

func (a *App) RunChatScript(lang string, source string) (engine.RunBlockResult, error) {
	return a.api.RunChatScript(lang, source)
}

func (a *App) RunSessionReview(sessionID string) (int, error) {
	return a.api.RunSessionReview(sessionID)
}

func (a *App) RunSkillTuneup() (int, error) {
	return a.api.RunSkillTuneup()
}

func (a *App) RunnableLanguages() map[string]string {
	return a.api.RunnableLanguages()
}

func (a *App) SandboxFile(request string) (string, error) {
	return a.api.SandboxFile(request)
}

func (a *App) SaveAgentProfile(name string, body string) error {
	return a.api.SaveAgentProfile(name, body)
}

func (a *App) SaveBrowserShot(png []byte, marked bool) (string, error) {
	return a.api.SaveBrowserShot(png, marked)
}

func (a *App) SaveChairStarters(name string, locale string, set subagent.StarterSet) error {
	return a.api.SaveChairStarters(name, locale, set)
}

func (a *App) SaveChatImageData(dataURL string) (string, error) {
	return a.api.SaveChatImageData(dataURL)
}

func (a *App) SaveDeskFile(name string, text string) error {
	return a.api.SaveDeskFile(name, text)
}

func (a *App) SaveDeskStarters(desk string, locale string, set subagent.StarterSet) error {
	return a.api.SaveDeskStarters(desk, locale, set)
}

func (a *App) SaveIdentityFile(head string, name string, content string) error {
	return a.api.SaveIdentityFile(head, name, content)
}

func (a *App) SaveLearnedEntry(scope string, index int, text string) error {
	return a.api.SaveLearnedEntry(scope, index, text)
}

func (a *App) SaveMCPServer(originalName string, server config.MCPServerConfig) error {
	return a.api.SaveMCPServer(originalName, server)
}

func (a *App) SavePlanText(sessionID string, text string) string {
	return a.api.SavePlanText(sessionID, text)
}

func (a *App) SavePromptPreset(name string, body string) error {
	return a.api.SavePromptPreset(name, body)
}

func (a *App) SaveSubagentProfile(name string, body string) error {
	return a.api.SaveSubagentProfile(name, body)
}

func (a *App) SaveTeam(name string, desk string, description string, members []string) error {
	return a.api.SaveTeam(name, desk, description, members)
}

func (a *App) SearchAllSessions(query string) []engine.SessionMeta {
	return a.api.SearchAllSessions(query)
}

func (a *App) SearchSessions(query string) []engine.SessionMeta {
	return a.api.SearchSessions(query)
}

func (a *App) SearchSessionsForDoor(query string, filter engine.DeskFilter) []engine.SessionMeta {
	return a.api.SearchSessionsForDoor(query, filter)
}

func (a *App) SendMessage(text string, to string) (engine.TurnReply, error) {
	return a.api.SendMessage(text, to)
}

func (a *App) SessionAgent(id string) string {
	return a.api.SessionAgent(id)
}

func (a *App) SessionEdits(sessionID string) engine.EditPage {
	return a.api.SessionEdits(sessionID)
}

func (a *App) SessionExportBytes(id string, format string) (engine.ExportFile, error) {
	return a.api.SessionExportBytes(id, format)
}

func (a *App) SessionMode(id string) string {
	return a.api.SessionMode(id)
}

func (a *App) SessionPlan(sessionID string) engine.Plan {
	return a.api.SessionPlan(sessionID)
}

func (a *App) SessionPlanReports(sessionID string) []engine.PlanReport {
	return a.api.SessionPlanReports(sessionID)
}

func (a *App) SessionReviewAuto() bool {
	return a.api.SessionReviewAuto()
}

func (a *App) SessionSourceCount(sessionID string) int {
	return a.api.SessionSourceCount(sessionID)
}

func (a *App) SessionSources(sessionID string) []engine.Source {
	return a.api.SessionSources(sessionID)
}

func (a *App) SessionSpend(id string) engine.SessionSpend {
	return a.api.SessionSpend(id)
}

func (a *App) SessionTeam(id string) string {
	return a.api.SessionTeam(id)
}

func (a *App) SessionTranscript(id string) ([]engine.SessionMessage, error) {
	return a.api.SessionTranscript(id)
}

func (a *App) SessionsInSpace(name string) []engine.SessionMeta {
	return a.api.SessionsInSpace(name)
}

func (a *App) SetAgentOff(team string, name string, off bool) engine.DelegateSettings {
	return a.api.SetAgentOff(team, name, off)
}

func (a *App) SetBusyLayer(id string, on bool) []engine.BusyLayer {
	return a.api.SetBusyLayer(id, on)
}

func (a *App) SetCodeProjectsDir(dir string) error {
	return a.api.SetCodeProjectsDir(dir)
}

func (a *App) SetConnectionStartCommand(id string, command string) error {
	return a.api.SetConnectionStartCommand(id, command)
}

func (a *App) SetConnectionTargets(id string, targets []string) error {
	return a.api.SetConnectionTargets(id, targets)
}

func (a *App) SetDelegateOff(kind string, off bool) engine.DelegateSettings {
	return a.api.SetDelegateOff(kind, off)
}

func (a *App) SetHeadName(head string, name string) error {
	return a.api.SetHeadName(head, name)
}

func (a *App) SetImageEngine(id string) error {
	return a.api.SetImageEngine(id)
}

func (a *App) SetImageModelName(name string) error {
	return a.api.SetImageModelName(name)
}

func (a *App) SetLearningEnabled(on bool) error {
	return a.api.SetLearningEnabled(on)
}

func (a *App) SetMCPServerTargets(name string, targets []string) error {
	return a.api.SetMCPServerTargets(name, targets)
}

func (a *App) SetPlanStepStop(sessionID string, n int, on bool) {
	a.api.SetPlanStepStop(sessionID, n, on)
}

func (a *App) SetPreparedReplyOn(on bool) error {
	return a.api.SetPreparedReplyOn(on)
}

func (a *App) SetPresetImageFrom(name string, path string) (string, error) {
	return a.api.SetPresetImageFrom(name, path)
}

func (a *App) SetProviderBaseURL(providerName string, baseURL string) (engine.ModelInfo, error) {
	return a.api.SetProviderBaseURL(providerName, baseURL)
}

func (a *App) SetProviderEnabled(providerName string, enabled bool) ([]string, error) {
	return a.api.SetProviderEnabled(providerName, enabled)
}

func (a *App) SetProviderWireFormat(format string) (engine.ModelInfo, error) {
	return a.api.SetProviderWireFormat(format)
}

func (a *App) SetSessionReviewAuto(on bool) error {
	return a.api.SetSessionReviewAuto(on)
}

func (a *App) SetShell(setting string) error {
	return a.api.SetShell(setting)
}

func (a *App) SetSkillTuneAuto(on bool) error {
	return a.api.SetSkillTuneAuto(on)
}

func (a *App) SetSpeechEngine(id string) error {
	return a.api.SetSpeechEngine(id)
}

func (a *App) SetSpeechModel(path string) error {
	return a.api.SetSpeechModel(path)
}

func (a *App) SetSpeechModelName(name string) error {
	return a.api.SetSpeechModelName(name)
}

func (a *App) SetStance(name string) (string, error) {
	return a.api.SetStance(name)
}

func (a *App) SetSubagentModel(name string, modelName string) error {
	return a.api.SetSubagentModel(name, modelName)
}

func (a *App) SetTTSEngine(id string) error {
	return a.api.SetTTSEngine(id)
}

func (a *App) SetTTSModelName(name string) error {
	return a.api.SetTTSModelName(name)
}

func (a *App) SetUILocale(locale string) error {
	return a.api.SetUILocale(locale)
}

func (a *App) SetUserName(name string) error {
	return a.api.SetUserName(name)
}

func (a *App) Shells() []engine.ShellOption {
	return a.api.Shells()
}

func (a *App) SkillScanIssues() []string {
	return a.api.SkillScanIssues()
}

func (a *App) SkillTuneAuto() bool {
	return a.api.SkillTuneAuto()
}

func (a *App) SkillsDir() string {
	return a.api.SkillsDir()
}

func (a *App) SkillsFolderPath() (string, error) {
	return a.api.SkillsFolderPath()
}

func (a *App) SpaceFolderPath(name string) (string, error) {
	return a.api.SpaceFolderPath(name)
}

func (a *App) Spaces() []engine.Space {
	return a.api.Spaces()
}

func (a *App) SpeechModelDirPath(dir string) (string, error) {
	return a.api.SpeechModelDirPath(dir)
}

func (a *App) SpeechModelDirs() []engine.SpeechDirInfo {
	return a.api.SpeechModelDirs()
}

func (a *App) SpeechModelFolderPath(path string) (string, error) {
	return a.api.SpeechModelFolderPath(path)
}

func (a *App) SpeechStatus() string {
	return a.api.SpeechStatus()
}

func (a *App) Stance() string {
	return a.api.Stance()
}

func (a *App) Stances() []string {
	return a.api.Stances()
}

func (a *App) StartConnectionServer(id string) error {
	return a.api.StartConnectionServer(id)
}

func (a *App) StartMCPSignIn(serverName string, resourceURL string) (engine.SignInPrompt, error) {
	return a.api.StartMCPSignIn(serverName, resourceURL)
}

func (a *App) StartMobileRemote() engine.RemoteStatus {
	return a.api.StartMobileRemote()
}

func (a *App) StartPlanRun(sessionID string) engine.PlanRunStart {
	return a.api.StartPlanRun(sessionID)
}

func (a *App) StopBackgroundRun(runID string) int {
	return a.api.StopBackgroundRun(runID)
}

func (a *App) StopBackgroundTask(id string) bool {
	return a.api.StopBackgroundTask(id)
}

func (a *App) StopBrowsing() {
	a.api.StopBrowsing()
}

func (a *App) StopMobileRemote() engine.RemoteStatus {
	return a.api.StopMobileRemote()
}

func (a *App) StopPlanRun(sessionID string) {
	a.api.StopPlanRun(sessionID)
}

func (a *App) StopQueuedTasks() int {
	return a.api.StopQueuedTasks()
}

func (a *App) StudioAssetPath(id string) (string, error) {
	return a.api.StudioAssetPath(id)
}

func (a *App) StudioAssets(q engine.StudioAssetQuery) engine.StudioAssetPage {
	return a.api.StudioAssets(q)
}

func (a *App) StudioLibraries() []engine.StudioLibraryView {
	return a.api.StudioLibraries()
}

func (a *App) StudioLibraryPath(id string) (string, error) {
	return a.api.StudioLibraryPath(id)
}

func (a *App) StudioScanning() bool {
	return a.api.StudioScanning()
}

func (a *App) StudioSetHidden(id string, hidden bool) error {
	return a.api.StudioSetHidden(id, hidden)
}

func (a *App) StudioSetKind(id string, kind string) error {
	return a.api.StudioSetKind(id, kind)
}

func (a *App) StudioThumbs(ids []string) map[string]string {
	return a.api.StudioThumbs(ids)
}

func (a *App) SubagentsFolderPath() (string, error) {
	return a.api.SubagentsFolderPath()
}

func (a *App) SuggestPRDetails(head string, base string) (engine.PRSuggestion, error) {
	return a.api.SuggestPRDetails(head, base)
}

func (a *App) SupportedProviders() []string {
	return a.api.SupportedProviders()
}

func (a *App) SupportedThinkLevels() []string {
	return a.api.SupportedThinkLevels()
}

func (a *App) SupportedThinkLevelsFor(provider string, modelName string) []string {
	return a.api.SupportedThinkLevelsFor(provider, modelName)
}

func (a *App) SwitchApprovalMode(mode string) (engine.ModelInfo, error) {
	return a.api.SwitchApprovalMode(mode)
}

func (a *App) SwitchModel(modelName string) (engine.ModelInfo, error) {
	return a.api.SwitchModel(modelName)
}

func (a *App) SwitchProvider(provider string) (engine.ModelInfo, error) {
	return a.api.SwitchProvider(provider)
}

func (a *App) SwitchThinkLevel(level string) (engine.ModelInfo, error) {
	return a.api.SwitchThinkLevel(level)
}

func (a *App) SwitchVariant(index int) (engine.RegenerateResult, error) {
	return a.api.SwitchVariant(index)
}

func (a *App) SynthesizeHabit(sessionID string, hint string) (int64, error) {
	return a.api.SynthesizeHabit(sessionID, hint)
}

func (a *App) TeamsFolderPath() (string, error) {
	return a.api.TeamsFolderPath()
}

func (a *App) TerminalAttach(sessionID string) string {
	return a.api.TerminalAttach(sessionID)
}

func (a *App) TerminalClose(sessionID string) error {
	return a.api.TerminalClose(sessionID)
}

func (a *App) TerminalResize(sessionID string, cols int, rows int) error {
	return a.api.TerminalResize(sessionID, cols, rows)
}

func (a *App) TerminalShells() []engine.ShellProfile {
	return a.api.TerminalShells()
}

func (a *App) TerminalStart(shellPath string, cols int, rows int) (string, error) {
	return a.api.TerminalStart(shellPath, cols, rows)
}

func (a *App) TerminalWrite(sessionID string, data string) error {
	return a.api.TerminalWrite(sessionID, data)
}

func (a *App) TestMCPServer(name string) engine.MCPServerInfo {
	return a.api.TestMCPServer(name)
}

func (a *App) ToggleMCPServer(name string, disabled bool) error {
	return a.api.ToggleMCPServer(name, disabled)
}

func (a *App) ToolBlockTokens() int {
	return a.api.ToolBlockTokens()
}

func (a *App) ToolCounts() engine.ToolCounts {
	return a.api.ToolCounts()
}

func (a *App) ToolInstallPlan(name string) engine.ToolInstallPlan {
	return a.api.ToolInstallPlan(name)
}

func (a *App) TranscribeMicAudio(dataURL string) (string, error) {
	return a.api.TranscribeMicAudio(dataURL)
}

func (a *App) TurnInFlight() engine.TurnStatus {
	return a.api.TurnInFlight()
}

func (a *App) TurnRating(messageID int64) string {
	return a.api.TurnRating(messageID)
}

func (a *App) UndoLastTurn() (engine.UndoResult, error) {
	return a.api.UndoLastTurn()
}

func (a *App) UsageStats() (engine.UsageStats, error) {
	return a.api.UsageStats()
}

func (a *App) UseEngine(family string, agent string, id string) error {
	return a.api.UseEngine(family, agent, id)
}

func (a *App) UserName() string {
	return a.api.UserName()
}

func (a *App) VerifyConnection(id string) (connect.Account, error) {
	return a.api.VerifyConnection(id)
}

func (a *App) VideoCheckSeen() bool {
	return a.api.VideoCheckSeen()
}

func (a *App) VideoEditorCommand() []string {
	return a.api.VideoEditorCommand()
}

func (a *App) VideoEditorEnvironment() map[string]string {
	return a.api.VideoEditorEnvironment()
}

func (a *App) VideoEditorHelpURL(what string) string {
	return a.api.VideoEditorHelpURL(what)
}

func (a *App) VideoEditorTools() []string {
	return a.api.VideoEditorTools()
}

func (a *App) VideoReadiness(agent string) engine.VideoReadiness {
	return a.api.VideoReadiness(agent)
}

func (a *App) VideoToolingStatus() engine.VideoToolingStatus {
	return a.api.VideoToolingStatus()
}

func (a *App) VoiceSettings() engine.VoiceSettings {
	return a.api.VoiceSettings()
}

func (a *App) WorkbenchTabsChanged(sessionID string, tabs []engine.DeskTab) {
	a.api.WorkbenchTabsChanged(sessionID, tabs)
}

func (a *App) WorkspaceFolders() []engine.WorkspaceFolder {
	return a.api.WorkspaceFolders()
}

func (a *App) WriteFile(relPath string, content string) error {
	return a.api.WriteFile(relPath, content)
}
