package main

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"testing"

	"github.com/Mike0165115321/Aetox/internal/config"
	"github.com/Mike0165115321/Aetox/internal/connect"
	"github.com/Mike0165115321/Aetox/internal/safety"
	"github.com/Mike0165115321/Aetox/internal/skill"
)

// TestPrintReadmeToolTable is a generator, not an assertion. `go test ./desktop
// -run TestPrintReadmeToolTable -v` prints the README's tool table exactly as it
// should appear, read from the same registry the model is handed.
//
// The table used to be maintained by hand and drifted: it listed `shell_output`,
// `shell_kill` and four `github_*` names as separate tools months after they
// were packed into one entry each, and never grew the `n8n` and `windmill` rows
// it should have. A hand-kept list of what the program contains is a second
// source of truth for a question the program can answer.
func TestPrintReadmeToolTable(t *testing.T) {
	t.Setenv("AETOX_DATA_ROOT", t.TempDir())
	a := seed(&App{ctx: context.Background(), emit: func(string, ...any) {}, dbDir: t.TempDir()}, &conversation{id: newSessionID()})
	t.Cleanup(func() {
		if a.db != nil {
			_ = a.db.Close()
		}
	})
	a.applyConfig(a.cur(), config.Config{
		SandboxRoot:   t.TempDir(),
		ModelProvider: "aetox",
		ModelName:     "aetox-tools:test",
		ApprovalMode:  string(safety.ApprovalFullAccess),
	})

	// Same gate as the budget test: every connection held, no account for any of
	// them, which is what a fresh install actually sends.
	held := connect.IDs()

	// The action names a packed tool gates on inside itself. They are not
	// registry entries, so the registry cannot report them, but leaving them out
	// would describe `shell` as one undifferentiated verb.
	packed := map[string][]string{
		"shell":    {"run", "output", "kill", "list"},
		"github":   {"repo_summary", "search", "read_file", "list_files"},
		"browser":  {"open", "read", "click", "type"},
		"n8n":      {"list", "read", "create", "update", "activate"},
		"windmill": {"workspaces", "list", "read", "create", "update"},
	}

	byCategory := map[string][]string{}
	count := 0
	for _, d := range skill.NewDispatcher(a.cur().registry).ToolDefinitions() {
		name := d.Function.Name
		if !connect.Allows(name, held) {
			continue
		}
		count++
		cell := "`" + name + "`"
		if actions, ok := packed[name]; ok {
			cell = "`" + name + "` *(" + strings.Join(actions, " · ") + ")*"
		}
		c := skill.CategoryOf(name)
		byCategory[c] = append(byCategory[c], cell)
	}

	// The user-facing name of each category. internal/skill/category.go owns the
	// grouping; only the English wording lives here.
	label := map[string]string{
		skill.CategoryFiles:        "**Files**",
		skill.CategoryShell:        "**Running commands**",
		skill.CategoryDeliverables: "**Handing back files**",
		skill.CategoryMedia:        "**Reading media**",
		skill.CategoryWeb:          "**Web and automation**",
		skill.CategoryCode:         "**Code work**",
		skill.CategoryAgent:        "**How the assistant works**",
	}

	var b strings.Builder
	fmt.Fprintf(&b, "\n<!-- generated by TestPrintReadmeToolTable — do not hand-edit -->\n\n")
	fmt.Fprintf(&b, "| Group | Tools |\n|:---|:---|\n")
	for _, c := range skill.CategoryOrder {
		names := byCategory[c]
		if len(names) == 0 {
			continue
		}
		sort.Strings(names)
		fmt.Fprintf(&b, "| %s | %s |\n", label[c], strings.Join(names, " "))
	}
	fmt.Fprintf(&b, "\nTotal: %d tools on a fresh install.\n", count)
	t.Log(b.String())
}
